import {
  HealthEvent,
  Diagnosis,
  Treatment,
  MedicationAdministration,
  VaccineCatalog,
  VaccinationEvent,
  PreventiveCareEvent,
  BreedingCycle,
  BreedingEvent,
  PregnancyCheck,
  Pregnancy,
  CalvingEvent,
  CalvingOffspring,
  ProductionPeriod,
  AnimalProductionRecord,
  SensorDevice,
  AnimalDeviceAssignment,
  SensorReading,
  DailySensorSummary,
  MaternalDevelopmentRecord,
  WeaningDevelopmentRecord,
  YearlingDevelopmentRecord,
  ReproductiveProcess,
  RecipientEvaluation,
} from './bovine-types';

export const initialHealthEvents: HealthEvent[] = [
  {
    id: 'he-1',
    animalId: 'anim-1',
    farmId: 'farm-1',
    openedAt: '2026-09-02T08:00:00Z',
    status: 'UNDER_TREATMENT',
    reason: 'Post-partum acute coliform mastitis',
    severity: 'HIGH',
    notes: 'Elevated somatic cell count >480k, heat and edema in right rear quarter. Intake down 15%.',
    originObservationId: 'obs-mast-1',
  },
  {
    id: 'he-2',
    animalId: 'anim-3',
    farmId: 'farm-1',
    openedAt: '2026-09-03T10:30:00Z',
    status: 'OPEN',
    reason: 'Sole ulcer and moderate lameness',
    severity: 'MODERATE',
    notes: 'Locomotion score 3.5, reduced walking steps on pedometer telemetry. Scheduled for trimming chute.',
  },
  {
    id: 'he-3',
    animalId: 'anim-2',
    farmId: 'farm-2',
    openedAt: '2026-08-20T09:00:00Z',
    closedAt: '2026-08-28T14:00:00Z',
    status: 'RESOLVED',
    reason: 'Subclinical metabolic ketosis',
    severity: 'MILD',
    notes: 'Blood BHB normalized to 0.7 mmol/L following propylene glycol oral drench protocol.',
  },
  {
    id: 'he-4',
    animalId: 'anim-4',
    farmId: 'farm-3',
    openedAt: '2026-09-04T07:15:00Z',
    status: 'OPEN',
    reason: 'Bovine respiratory disease complex (BRD)',
    severity: 'CRITICAL',
    notes: 'Body temperature 40.1°C, tachypneic shallow respiration, bilateral nasal serous discharge.',
  },
];

export const initialDiagnoses: Diagnosis[] = [
  {
    id: 'diag-1',
    healthEventId: 'he-1',
    animalId: 'anim-1',
    diagnosisCode: 'MAST-COLI',
    diagnosisName: 'Coliform Mastitis (E. coli)',
    diagnosedAt: '2026-09-02T09:00:00Z',
    labConfirmed: true,
    recordedByName: 'Dr. Evelyn Sterling',
    notes: 'On-farm culture confirmed gram-negative lactose fermenter.',
  },
  {
    id: 'diag-2',
    healthEventId: 'he-2',
    animalId: 'anim-3',
    diagnosisCode: 'LAME-ULC',
    diagnosisName: 'Solar Ulcer (Rusterholz)',
    diagnosedAt: '2026-09-03T11:00:00Z',
    labConfirmed: false,
    recordedByName: 'Carlos Mendez (Certified Trimmer)',
    notes: 'Lateral claw of right hind foot affected; corrective block placed on medial claw.',
  },
  {
    id: 'diag-3',
    healthEventId: 'he-4',
    animalId: 'anim-4',
    diagnosisCode: 'RESP-MANN',
    diagnosisName: 'Bovine Pneumonic Mannheimiosis',
    diagnosedAt: '2026-09-04T08:00:00Z',
    labConfirmed: true,
    recordedByName: 'Dr. Sarah Jenkins',
    notes: 'Thoracic ultrasonography revealed 4cm consolidation zone in cranial lobe.',
  },
];

export const initialTreatments: Treatment[] = [
  {
    id: 'treat-1',
    healthEventId: 'he-1',
    animalId: 'anim-1',
    treatmentName: 'Intramammary Ceftiofur & Flunixin',
    medication: 'Spectramast LC & Banamine Injectable',
    dose: 10,
    doseUnit: 'mL',
    route: 'INTRAMAMMARY',
    startedAt: '2026-09-02T10:00:00Z',
    endedAt: '2026-09-07T10:00:00Z',
    withdrawalEnd: '2026-09-11T00:00:00Z',
    recordedByName: 'Dr. Evelyn Sterling',
    notes: 'Milk discard mandatory for 96 hours post-treatment. Meat withdrawal 2 days.',
  },
  {
    id: 'treat-2',
    healthEventId: 'he-4',
    animalId: 'anim-4',
    treatmentName: 'Tulathromycin Long-Acting',
    medication: 'Draxxin 100mg/mL',
    dose: 12.5,
    doseUnit: 'mL',
    route: 'SUBCUTANEOUS',
    startedAt: '2026-09-04T08:30:00Z',
    endedAt: '2026-09-04T08:30:00Z',
    withdrawalEnd: '2026-09-22T00:00:00Z',
    recordedByName: 'Dr. Sarah Jenkins',
    notes: 'Single dose administered in left neck cervical triangle. 18-day meat withdrawal.',
  },
];

export const initialMedicationAdministrations: MedicationAdministration[] = [
  {
    id: 'med-adm-1',
    animalId: 'anim-1',
    treatmentId: 'treat-1',
    administeredAt: '2026-09-02T10:00:00Z',
    medication: 'Spectramast LC',
    dose: 10,
    doseUnit: 'mL',
    route: 'INTRAMAMMARY',
    batchNumber: 'LOT-9821A',
    status: 'GIVEN',
    administeredByName: 'Tech Alex Ramos',
    notes: 'Infused after complete strippings and teat sanitization.',
  },
  {
    id: 'med-adm-2',
    animalId: 'anim-1',
    treatmentId: 'treat-1',
    administeredAt: '2026-09-03T10:00:00Z',
    medication: 'Spectramast LC',
    dose: 10,
    doseUnit: 'mL',
    route: 'INTRAMAMMARY',
    batchNumber: 'LOT-9821A',
    status: 'GIVEN',
    administeredByName: 'Tech Alex Ramos',
    notes: 'Quarter softened, milk clots diminished.',
  },
  {
    id: 'med-adm-3',
    animalId: 'anim-1',
    treatmentId: 'treat-1',
    administeredAt: '2026-09-04T10:00:00Z',
    medication: 'Spectramast LC',
    dose: 10,
    doseUnit: 'mL',
    route: 'INTRAMAMMARY',
    batchNumber: 'LOT-9821A',
    status: 'GIVEN',
    administeredByName: 'Tech Alex Ramos',
    notes: 'Day 3 tube administered on schedule.',
  },
  {
    id: 'med-adm-4',
    animalId: 'anim-1',
    treatmentId: 'treat-1',
    administeredAt: '2026-09-05T10:00:00Z',
    medication: 'Spectramast LC',
    dose: 10,
    doseUnit: 'mL',
    route: 'INTRAMAMMARY',
    batchNumber: 'LOT-9821A',
    status: 'PENDING',
    administeredByName: 'Scheduled Day 4 Shift',
  },
  {
    id: 'med-adm-5',
    animalId: 'anim-4',
    treatmentId: 'treat-2',
    administeredAt: '2026-09-04T08:30:00Z',
    medication: 'Draxxin 100mg/mL',
    dose: 12.5,
    doseUnit: 'mL',
    route: 'SUBCUTANEOUS',
    batchNumber: 'LOT-TRX441',
    status: 'GIVEN',
    administeredByName: 'Dr. Sarah Jenkins',
    notes: 'Injected with 16G 3/4 needle.',
  },
];

export const initialVaccineCatalog: VaccineCatalog[] = [
  {
    id: 'vac-cat-1',
    code: 'Bovi-Shield-Gold',
    name: 'Bovi-Shield GOLD FP 5 L5',
    manufacturer: 'Zoetis Animal Health',
    diseaseTarget: 'IBR, BVD Types 1 & 2, PI3, BRSV, 5 Lepto strains',
    recommendedDose: 2,
    doseUnit: 'mL',
    route: 'SUBCUTANEOUS',
    active: true,
  },
  {
    id: 'vac-cat-2',
    code: 'Scourguard-4KC',
    name: 'ScourGuard 4(K)C',
    manufacturer: 'Zoetis Animal Health',
    diseaseTarget: 'Bovine Rotavirus, Coronavirus, E. coli K99, Clostridium perfringens Type C',
    recommendedDose: 2,
    doseUnit: 'mL',
    route: 'INTRAMUSCULAR',
    active: true,
  },
  {
    id: 'vac-cat-3',
    code: 'Alpha-7-MB',
    name: 'Alpha-7 / MB-1',
    manufacturer: 'Boehringer Ingelheim',
    diseaseTarget: 'Blackleg, Malignant Edema, Moraxella bovis (Pinkeye)',
    recommendedDose: 2,
    doseUnit: 'mL',
    route: 'SUBCUTANEOUS',
    active: true,
  },
  {
    id: 'vac-cat-4',
    code: 'J-VAC',
    name: 'J-VAC Endotoxemia Vaccine',
    manufacturer: 'Merial / Boehringer Ingelheim',
    diseaseTarget: 'E. coli J5 Mastitis and Endotoxin Complex',
    recommendedDose: 2,
    doseUnit: 'mL',
    route: 'SUBCUTANEOUS',
    active: true,
  },
];

export const initialVaccinationEvents: VaccinationEvent[] = [
  {
    id: 'vac-ev-1',
    animalId: 'anim-1',
    vaccineId: 'vac-cat-1',
    administeredAt: '2026-01-15T09:00:00Z',
    dose: 2,
    doseUnit: 'mL',
    route: 'SUBCUTANEOUS',
    batchNumber: 'V-55902',
    expiryDate: '2027-06-30',
    administeredByName: 'Dr. Evelyn Sterling',
    nextDueAt: '2027-01-15T09:00:00Z',
    notes: 'Annual herd booster given prior to breeding season.',
  },
  {
    id: 'vac-ev-2',
    animalId: 'anim-2',
    vaccineId: 'vac-cat-1',
    administeredAt: '2026-01-15T09:30:00Z',
    dose: 2,
    doseUnit: 'mL',
    route: 'SUBCUTANEOUS',
    batchNumber: 'V-55902',
    expiryDate: '2027-06-30',
    administeredByName: 'Dr. Evelyn Sterling',
    nextDueAt: '2027-01-15T09:00:00Z',
  },
  {
    id: 'vac-ev-3',
    animalId: 'anim-3',
    vaccineId: 'vac-cat-2',
    administeredAt: '2025-08-10T11:00:00Z',
    dose: 2,
    doseUnit: 'mL',
    route: 'INTRAMUSCULAR',
    batchNumber: 'V-11048',
    expiryDate: '2026-10-31',
    administeredByName: 'Tech Alex Ramos',
    nextDueAt: '2026-08-10T11:00:00Z',
    notes: 'Booster overdue by 25 days. Scheduled for next pen visit.',
  },
  {
    id: 'vac-ev-4',
    animalId: 'anim-4',
    vaccineId: 'vac-cat-3',
    administeredAt: '2026-03-01T10:00:00Z',
    dose: 2,
    doseUnit: 'mL',
    route: 'SUBCUTANEOUS',
    batchNumber: 'LOT-AL7-99',
    expiryDate: '2027-09-01',
    administeredByName: 'Dr. Sarah Jenkins',
    nextDueAt: '2027-03-01T10:00:00Z',
  },
];

export const initialPreventiveCareEvents: PreventiveCareEvent[] = [
  {
    id: 'prev-1',
    animalId: 'anim-1',
    farmId: 'farm-1',
    type: 'HOOF_TRIM',
    performedAt: '2026-05-12T14:00:00Z',
    product: 'Functional 5-Step Dutch Hoof Trim',
    performedByName: 'Carlos Mendez',
    nextDueAt: '2026-11-12T14:00:00Z',
    notes: 'Claw length balanced, sole thickness verified with gauge. Zero white line disease.',
  },
  {
    id: 'prev-2',
    animalId: 'anim-2',
    farmId: 'farm-2',
    type: 'DEWORMING',
    performedAt: '2026-06-01T10:00:00Z',
    product: 'Eprinex Pour-On (Eprinomectin)',
    batchNumber: 'LOT-EPR882',
    dose: 35,
    doseUnit: 'mL',
    route: 'TOPICAL',
    performedByName: 'Tech Alex Ramos',
    nextDueAt: '2026-12-01T10:00:00Z',
    notes: 'Zero milk withholding formulation applied along backline.',
  },
  {
    id: 'prev-3',
    animalId: 'anim-3',
    farmId: 'farm-1',
    type: 'EXAMINATION',
    performedAt: '2026-08-15T09:00:00Z',
    product: 'Pre-Breeding Reproductive Tract Ultrasound',
    performedByName: 'Dr. Evelyn Sterling',
    nextDueAt: '2026-09-01T09:00:00Z',
    notes: 'Ovarian dynamics evaluated; 14mm dominant follicle in right ovary.',
  },
];

export const initialBreedingCycles: BreedingCycle[] = [
  {
    id: 'bc-1',
    femaleAnimalId: 'anim-1',
    cycleStart: '2026-06-01T08:00:00Z',
    season: 'Summer 2026',
    status: 'PREGNANT',
    notes: 'Second lactation breeding cycle. Synchronized with Ovsynch 56 protocol.',
  },
  {
    id: 'bc-2',
    femaleAnimalId: 'anim-3',
    cycleStart: '2026-08-10T08:00:00Z',
    season: 'Fall 2026',
    status: 'IN_BREEDING',
    notes: 'Maiden heifer cycle. Target conception weight 380 kg reached.',
  },
  {
    id: 'bc-3',
    femaleAnimalId: 'anim-2',
    cycleStart: '2025-05-10T08:00:00Z',
    cycleEnd: '2026-02-14T04:20:00Z',
    season: 'Spring 2025',
    status: 'CLOSED',
    notes: 'Concluded with successful delivery of heifer calf Apex Valedictorian 202.',
  },
];

export const initialBreedingEvents: BreedingEvent[] = [
  {
    id: 'be-1',
    breedingCycleId: 'bc-1',
    femaleAnimalId: 'anim-1',
    sireAnimalId: 'anim-5',
    sireName: 'Pine-Tree Dairy King',
    semenBatchId: 'sb-102',
    semenBatchCode: 'SEM-KING-771',
    eventType: 'ARTIFICIAL_INSEMINATION',
    eventAt: '2026-06-15T07:30:00Z',
    technicianName: 'Dr. Evelyn Sterling',
    synchronizationProtocol: 'Ovsynch 56',
    notes: 'High motility semen straw, smooth uterine horn deposition.',
  },
  {
    id: 'be-2',
    breedingCycleId: 'bc-2',
    femaleAnimalId: 'anim-3',
    sireAnimalId: 'anim-5',
    sireName: 'Pine-Tree Dairy King',
    semenBatchId: 'sb-102',
    semenBatchCode: 'SEM-KING-771',
    eventType: 'ARTIFICIAL_INSEMINATION',
    eventAt: '2026-08-25T08:00:00Z',
    technicianName: 'Tech Alex Ramos',
    synchronizationProtocol: 'Double-Ovsynch',
    notes: 'Standing estrus observed at 06:00. Inseminated 12 hours post-heat onset.',
  },
  {
    id: 'be-3',
    breedingCycleId: 'bc-3',
    femaleAnimalId: 'anim-2',
    sireAnimalId: 'anim-5',
    sireName: 'Pine-Tree Dairy King',
    semenBatchId: 'sb-102',
    semenBatchCode: 'SEM-KING-771',
    eventType: 'ARTIFICIAL_INSEMINATION',
    eventAt: '2025-05-20T08:00:00Z',
    technicianName: 'Dr. Evelyn Sterling',
    notes: 'Conception event for calving calv-1.',
  },
];

export const initialPregnancyChecks: PregnancyCheck[] = [
  {
    id: 'pc-1',
    breedingCycleId: 'bc-1',
    breedingEventId: 'be-1',
    animalId: 'anim-1',
    checkedAt: '2026-07-28T09:00:00Z',
    result: 'PREGNANT',
    gestationDaysEstimated: 43,
    fetusCount: 1,
    method: 'ULTRASOUND',
    examinerName: 'Dr. Evelyn Sterling',
    notes: 'Viable fetus with active cardiac flicker in right horn. Membrane slip verified.',
  },
  {
    id: 'pc-2',
    breedingCycleId: 'bc-2',
    breedingEventId: 'be-2',
    animalId: 'anim-3',
    checkedAt: '2026-09-02T10:00:00Z',
    result: 'RECHECK',
    gestationDaysEstimated: 28,
    fetusCount: 1,
    method: 'ULTRASOUND',
    examinerName: 'Dr. Sarah Jenkins',
    notes: 'Atypical fluid pocket detected; recheck in 10 days to verify embryonic viability.',
  },
];

export const initialPregnancies: Pregnancy[] = [
  {
    id: 'preg-1',
    damId: 'anim-1',
    damName: 'Apex Monarch Maiden 102',
    damInternalId: 'APEX-BF-001',
    breedingCycleId: 'bc-1',
    breedingEventId: 'be-1',
    sireAnimalId: 'anim-5',
    sireName: 'Pine-Tree Dairy King',
    status: 'ACTIVE',
    conceptionDate: '2026-06-15',
    expectedCalvingDate: '2027-03-24',
    confirmedAt: '2026-07-28T09:00:00Z',
    notes: 'Normal gestation progression. Expected dry-off date: Jan 24, 2027.',
  },
];

export const initialCalvingEvents: CalvingEvent[] = [
  {
    id: 'calv-1',
    damId: 'anim-2',
    pregnancyId: undefined,
    calvingAt: '2026-02-14T04:20:00Z',
    ease: 'NORMAL',
    birthType: 'SINGLE',
    presentation: 'NORMAL_ANTERIOR',
    placentaStatus: 'EXPELLED_NORMAL',
    damCondition: 'ALERT_VIGOROUS',
    offspringCount: 1,
    notes: 'Unassisted delivery in maternity pen 2. Dam licked calf clean immediately.',
  },
];

export const initialCalvingOffspring: CalvingOffspring[] = [
  {
    id: 'calv-off-1',
    calvingEventId: 'calv-1',
    animalId: 'anim-6',
    birthOrder: 1,
    birthOutcome: 'LIVE',
    birthWeightKg: 41.5,
    neonatalNotes: 'Colostrum 4L received within 2 hours of birth; navel dipped in 7% tincture of iodine.',
  },
];

export const initialProductionPeriods: ProductionPeriod[] = [
  {
    id: 'prod-per-1',
    animalId: 'anim-1',
    farmId: 'farm-1',
    herdId: 'herd-1',
    type: 'LACTATION',
    periodType: 'LACTATION',
    sequence: 2,
    cycleNumber: 2,
    startedAt: '2025-11-01T00:00:00Z',
    startDate: '2025-11-01',
    status: 'ACTIVE',
    startReason: 'Second Calving',
    notes: 'Current lactation day 308. Projected 305-day yield 12,450 kg.',
  },
  {
    id: 'prod-per-2',
    animalId: 'anim-2',
    farmId: 'farm-2',
    herdId: 'herd-2',
    type: 'LACTATION',
    periodType: 'LACTATION',
    sequence: 3,
    cycleNumber: 3,
    startedAt: '2026-02-14T00:00:00Z',
    startDate: '2026-02-14',
    status: 'ACTIVE',
    startReason: 'Third Calving',
    notes: 'Lactation day 203. Average daily yield 38.2 kg.',
  },
  {
    id: 'prod-per-3',
    animalId: 'anim-3',
    farmId: 'farm-1',
    herdId: 'herd-1',
    type: 'GROWTH_FATTENING',
    periodType: 'GROWTH_FATTENING',
    sequence: 1,
    cycleNumber: 1,
    startedAt: '2025-06-01T00:00:00Z',
    startDate: '2025-06-01',
    status: 'ACTIVE',
    startReason: 'Heifer Development Tier',
    notes: 'Targeting breeding weight of 380 kg with ADG >0.85 kg/day.',
  },
];

export const initialProductionRecords: AnimalProductionRecord[] = [
  {
    id: 'prod-rec-1',
    animalId: 'anim-1',
    productionPeriodId: 'prod-per-1',
    type: 'MILK_YIELD',
    recordType: 'MILK_TEST_DAY',
    recordedAt: '2026-09-04T06:00:00Z',
    recordDate: '2026-09-04',
    value: 19.8,
    milkYieldKg: 19.8,
    fatPercentage: 3.92,
    proteinPercentage: 3.18,
    somaticCellCount: 145,
    daysInMilk: 308,
    unit: 'kg',
    session: 'MORNING',
    source: 'SENSOR',
    qualityStatus: 'VALIDATED',
    recordedByName: 'Robotic Milking Station #1',
  },
  {
    id: 'prod-rec-2',
    animalId: 'anim-1',
    productionPeriodId: 'prod-per-1',
    type: 'MILK_YIELD',
    recordType: 'MILK_TEST_DAY',
    recordedAt: '2026-09-04T17:00:00Z',
    recordDate: '2026-09-04',
    value: 18.4,
    milkYieldKg: 18.4,
    fatPercentage: 3.95,
    proteinPercentage: 3.22,
    somaticCellCount: 152,
    daysInMilk: 308,
    unit: 'kg',
    session: 'EVENING',
    source: 'SENSOR',
    qualityStatus: 'VALIDATED',
    recordedByName: 'Robotic Milking Station #1',
  },
  {
    id: 'prod-rec-3',
    animalId: 'anim-1',
    productionPeriodId: 'prod-per-1',
    type: 'MILK_FAT_PCT',
    recordType: 'MILK_TEST_DAY',
    recordedAt: '2026-09-04T17:30:00Z',
    recordDate: '2026-09-04',
    value: 3.92,
    milkYieldKg: 38.2,
    fatPercentage: 3.92,
    proteinPercentage: 3.20,
    somaticCellCount: 148,
    daysInMilk: 308,
    unit: '%',
    session: 'DAILY_TOTAL',
    source: 'SENSOR',
    qualityStatus: 'VALIDATED',
    recordedByName: 'Robotic Milking Station #1',
  },
  {
    id: 'prod-rec-4',
    animalId: 'anim-1',
    productionPeriodId: 'prod-per-1',
    type: 'SOMATIC_CELL_COUNT',
    recordType: 'MILK_TEST_DAY',
    recordedAt: '2026-09-04T17:30:00Z',
    recordDate: '2026-09-04',
    value: 480,
    milkYieldKg: 36.5,
    somaticCellCount: 480,
    daysInMilk: 308,
    unit: 'x1000/mL',
    session: 'DAILY_TOTAL',
    source: 'SENSOR',
    qualityStatus: 'SUSPECT',
    notes: 'Cell count elevated coinciding with mastitis flare.',
    recordedByName: 'Robotic Milking Station #1',
  },
  {
    id: 'prod-rec-5',
    animalId: 'anim-3',
    productionPeriodId: 'prod-per-3',
    type: 'BODY_WEIGHT',
    recordType: 'BEEF_WEIGHT',
    recordedAt: '2026-09-01T09:00:00Z',
    recordDate: '2026-09-01',
    value: 378,
    bodyWeightKg: 378,
    dailyGainKg: 0.88,
    unit: 'kg',
    session: 'WEIGH_IN',
    source: 'MANUAL',
    qualityStatus: 'VALIDATED',
    recordedByName: 'Scale System A',
  },
  {
    id: 'prod-rec-6',
    animalId: 'anim-3',
    productionPeriodId: 'prod-per-3',
    type: 'AVERAGE_DAILY_GAIN',
    recordType: 'BEEF_WEIGHT',
    recordedAt: '2026-09-01T09:00:00Z',
    recordDate: '2026-09-01',
    value: 0.88,
    dailyGainKg: 0.88,
    bodyWeightKg: 378,
    unit: 'kg/day',
    session: 'WEIGH_IN',
    source: 'MANUAL',
    qualityStatus: 'VALIDATED',
    recordedByName: 'Scale System A',
  },
];

export const initialSensorDevices: SensorDevice[] = [
  {
    id: 'sens-dev-1',
    farmId: 'farm-1',
    serialNumber: 'RMN-BOL-99021',
    type: 'RUMEN_BOLUS',
    deviceType: 'RUMEN_BOLUS',
    manufacturer: 'smaXtec Austria',
    model: 'Classic Internal Bolus',
    firmwareVersion: 'v4.2.1',
    active: true,
    status: 'ACTIVE',
    batteryLevelPct: 88,
    installedAt: '2025-08-01',
    lastSeenAt: '2026-09-05T09:10:00Z',
    currentAnimalId: 'anim-1',
  },
  {
    id: 'sens-dev-2',
    farmId: 'farm-1',
    serialNumber: 'EAR-TAG-44102',
    type: 'EAR_TAG',
    deviceType: 'EAR_TAG',
    manufacturer: 'Allflex / Merck',
    model: 'eSense Flex Ear Tag',
    firmwareVersion: 'v2.8.0',
    active: true,
    status: 'ACTIVE',
    batteryLevelPct: 76,
    installedAt: '2025-09-15',
    lastSeenAt: '2026-09-05T09:12:00Z',
    currentAnimalId: 'anim-3',
  },
  {
    id: 'sens-dev-3',
    farmId: 'farm-2',
    serialNumber: 'NECK-COL-77881',
    type: 'COLLAR',
    deviceType: 'COLLAR',
    manufacturer: 'Nedap Livestock',
    model: 'SmartTag Neck Collar',
    firmwareVersion: 'v3.1.2',
    active: true,
    status: 'ACTIVE',
    batteryLevelPct: 94,
    installedAt: '2026-01-10',
    lastSeenAt: '2026-09-05T09:05:00Z',
    currentAnimalId: 'anim-2',
  },
  {
    id: 'sens-dev-4',
    farmId: 'farm-1',
    serialNumber: 'LEG-PED-12009',
    type: 'LEG_PEDOMETER',
    deviceType: 'LEG_PEDOMETER',
    manufacturer: 'AfiMilk',
    model: 'AfiAct II Pedometer',
    firmwareVersion: 'v1.9.4',
    active: false,
    status: 'INACTIVE',
    batteryLevelPct: 12,
    installedAt: '2024-11-20',
    lastSeenAt: '2026-09-01T14:00:00Z',
    currentAnimalId: undefined,
  },
];

export const initialDeviceAssignments: AnimalDeviceAssignment[] = [
  {
    id: 'asgn-1',
    animalId: 'anim-1',
    deviceId: 'sens-dev-1',
    assignedAt: '2025-08-01T10:00:00Z',
    placement: 'RUMEN',
    notes: 'Administered orally via standard balling gun.',
  },
  {
    id: 'asgn-2',
    animalId: 'anim-3',
    deviceId: 'sens-dev-2',
    assignedAt: '2025-09-15T11:00:00Z',
    placement: 'RIGHT_EAR',
    notes: 'Applicator tag pin sanitized.',
  },
  {
    id: 'asgn-3',
    animalId: 'anim-2',
    deviceId: 'sens-dev-3',
    assignedAt: '2026-01-10T14:00:00Z',
    placement: 'NECK_COLLAR',
    notes: 'Fitted with 2 finger clearance.',
  },
];

export const initialSensorReadings: SensorReading[] = [
  {
    id: 'sr-1',
    deviceId: 'sens-dev-1',
    animalId: 'anim-1',
    metricType: 'BODY_TEMPERATURE',
    recordedAt: '2026-09-05T08:00:00Z',
    value: 39.4,
    unit: '°C',
    quality: 'RAW',
  },
  {
    id: 'sr-2',
    deviceId: 'sens-dev-1',
    animalId: 'anim-1',
    metricType: 'BODY_TEMPERATURE',
    recordedAt: '2026-09-05T09:00:00Z',
    value: 39.6,
    unit: '°C',
    quality: 'RAW',
  },
  {
    id: 'sr-3',
    deviceId: 'sens-dev-1',
    animalId: 'anim-1',
    metricType: 'RUMINATION_MINUTES',
    recordedAt: '2026-09-05T08:00:00Z',
    value: 28,
    unit: 'min',
    quality: 'RAW',
  },
  {
    id: 'sr-4',
    deviceId: 'sens-dev-2',
    animalId: 'anim-3',
    metricType: 'ACTIVITY_INDEX',
    recordedAt: '2026-09-05T08:00:00Z',
    value: 172,
    unit: 'index',
    quality: 'RAW',
  },
];

export const initialDailySensorSummaries: DailySensorSummary[] = [
  {
    id: 'dss-1',
    animalId: 'anim-1',
    logDate: '2026-09-04',
    metricType: 'RUMINATION_MINUTES',
    sampleCount: 96,
    minValue: 15,
    maxValue: 48,
    avgValue: 34,
    sumValue: 326,
    lastValue: 38,
    unit: 'min',
    abnormal: true,
  },
  {
    id: 'dss-2',
    animalId: 'anim-1',
    logDate: '2026-09-04',
    metricType: 'BODY_TEMPERATURE',
    sampleCount: 144,
    minValue: 38.6,
    maxValue: 39.7,
    avgValue: 39.2,
    sumValue: 5644,
    lastValue: 39.5,
    unit: '°C',
    abnormal: true,
  },
  {
    id: 'dss-3',
    animalId: 'anim-3',
    logDate: '2026-09-04',
    metricType: 'ACTIVITY_INDEX',
    sampleCount: 96,
    minValue: 20,
    maxValue: 180,
    avgValue: 110,
    sumValue: 10560,
    lastValue: 165,
    unit: 'index',
    abnormal: true,
  },
  {
    id: 'dss-4',
    animalId: 'anim-2',
    logDate: '2026-09-04',
    metricType: 'RUMINATION_MINUTES',
    sampleCount: 96,
    minValue: 28,
    maxValue: 55,
    avgValue: 46,
    sumValue: 442,
    lastValue: 45,
    unit: 'min',
    abnormal: false,
  },
];

// ==========================================
// SUPPLEMENTAL WORKFLOW INITIAL MOCK DATA
// ==========================================

export const initialMaternalRecords: MaternalDevelopmentRecord[] = [
  {
    id: 'mat-1',
    animalId: 'anim-1',
    date: '2024-03-15',
    weightKg: 42.5,
    waterIntake: 'NORMAL',
    waterIntakeLpd: 12,
    feedingSchedule: 'Colostrum 4L within 2h, then whole milk 3x daily (8L/day)',
    foodPreference: 'Warm whole milk, starter calf grain nibbles',
    dietType: 'Colostrum & Whole Milk + Calf Starter Muesli',
    notes: 'Vigorous suckling reflex, dry umbilical stump, navel dipped in 7% iodine tincture.',
    technician: 'Maria Rodriguez',
  },
  {
    id: 'mat-2',
    animalId: 'anim-1',
    date: '2024-04-10',
    weightKg: 58.0,
    waterIntake: 'NORMAL',
    waterIntakeLpd: 15,
    feedingSchedule: '2x daily milk replacer (6L/day) + ad libitum calf starter',
    foodPreference: 'Calf starter pellets with flaked corn and molasses',
    dietType: 'High-protein calf starter (22% CP) + clean clover hay',
    notes: 'Active social play in nursery pen. ADG 0.62 kg/day.',
    technician: 'Maria Rodriguez',
  },
  {
    id: 'mat-3',
    animalId: 'anim-3',
    date: '2025-01-20',
    weightKg: 38.0,
    waterIntake: 'NORMAL',
    waterIntakeLpd: 10,
    feedingSchedule: 'Maternal nursing + creep feed access',
    foodPreference: 'Dam milk + sweet creep pellets',
    dietType: 'Natural maternal milk + creep starter',
    notes: 'Born unassisted on pasture. Alert and nursing within 45 minutes.',
    technician: 'David Campbell',
  },
];

export const initialWeaningRecords: WeaningDevelopmentRecord[] = [
  {
    id: 'wean-1',
    animalId: 'anim-1',
    date: '2024-06-15',
    weightKg: 185.0,
    cbc: 'Normal PCV 34%, WBC 9.2k',
    dr: 'DR-A (Post-Weaning Total Mixed Ration)',
    sp: undefined, // Female
    drSp: undefined,
    drAc: 'DR-A',
    drUs: 'DR-A',
    ac: 'Grade 1 (Superior Frame & Muscling)',
    rea: 52.4,
    sft: 3.2,
    mar: 3.5,
    waterIntake: 'High (32 L/day)',
    feedingSchedule: 'Ad libitum TMR with orchard grass hay buffer',
    foodPreference: 'Steam-flaked corn, alfalfa haylage',
    dietType: 'Weaning Grower TMR (16% CP, 0.95 Mcal/kg NEg)',
    technician: 'Dr. John Miller',
    contemporaryGroupId: 'cg-1',
    qualityStatus: 'VERIFIED',
    notes: 'Smooth two-stage fence-line weaning. Zero respiratory incidence observed.',
  },
  {
    id: 'wean-2',
    animalId: 'anim-2',
    date: '2023-10-10',
    weightKg: 245.0,
    cbc: 'Normal PCV 36%, Platelets 450k',
    dr: 'DR-BullGrow (High Energy Pasture + Protein Supplement)',
    sp: 26.5,
    drSp: 'DR-BullGrow',
    drAc: 'DR-BullGrow',
    drUs: 'DR-BullGrow',
    ac: 'Grade A+ (Elite Bone & Testicular Conformation)',
    rea: 68.2,
    sft: 4.1,
    mar: 3.8,
    waterIntake: 'Normal (40 L/day)',
    feedingSchedule: 'Twice daily bunk feeding + pasture access',
    foodPreference: 'Cracked corn & soybean meal with mineral lick',
    dietType: 'Bull Developer Ration (14.5% CP)',
    technician: 'Dr. Sarah Jenkins',
    contemporaryGroupId: 'cg-2',
    qualityStatus: 'VERIFIED',
    notes: 'Exceptional 205-day adjusted weaning weight (310 kg equiv). Strong candidate for sire evaluation.',
  },
];

export const initialYearlingRecords: YearlingDevelopmentRecord[] = [
  {
    id: 'year-1',
    animalId: 'anim-2',
    date: '2024-04-12',
    weightKg: 465.0,
    weightDate: '2024-04-12',
    weightDietaryRegime: 'DR-SireBullStation',
    sp: 36.5,
    spDate: '2024-04-12',
    spDietaryRegime: 'DR-SireBullStation',
    ac: 'Elite Herd Sire Conformation (Score 9/9)',
    acDate: '2024-04-12',
    acDietaryRegime: 'DR-SireBullStation',
    ultrasoundDate: '2024-04-14',
    ultrasoundDietaryRegime: 'DR-SireBullStation',
    rea: 88.6,
    sft: 5.4,
    mar: 4.2,
    waterIntake: 'High (55 L/day)',
    feedingSchedule: 'Precision Calan bunk electronic feeder',
    foodPreference: 'Pelleted high-density grain mix & dry Timothy hay',
    dietType: 'Bull Performance Test Finishing Ration (13% CP, 1.15 Mcal NEg)',
    technician: 'Lead Ultrasound Tech R. Stevens',
    qualityStatus: 'VERIFIED',
    notes: '365-day yearling weight certified. Ultrasound marbling ratio exceeds breed 95th percentile.',
  },
  {
    id: 'year-2',
    animalId: 'anim-1',
    date: '2025-03-20',
    weightKg: 395.0,
    weightDate: '2025-03-20',
    weightDietaryRegime: 'DR-DairyHeiferDevelopment',
    sp: undefined,
    spDate: undefined,
    spDietaryRegime: undefined,
    ac: 'Dairy Conformation Very Good (VG-86)',
    acDate: '2025-03-20',
    acDietaryRegime: 'DR-DairyHeiferDevelopment',
    ultrasoundDate: '2025-03-22',
    ultrasoundDietaryRegime: 'DR-DairyHeiferDevelopment',
    rea: 62.0,
    sft: 3.8,
    mar: 3.2,
    waterIntake: 'Normal (48 L/day)',
    feedingSchedule: 'TMR delivered once daily at 07:00',
    foodPreference: 'Corn silage and alfalfa haylage',
    dietType: 'Breeding Heifer TMR (14% CP)',
    technician: 'Chloe Bennett',
    qualityStatus: 'VERIFIED',
    notes: 'Well grown yearling heifer with good frame development, ready for first synchronization.',
  },
];

export const initialReproductiveProcesses: ReproductiveProcess[] = [
  {
    id: 'rep-proc-1',
    code: 'RP-2026-001',
    status: 'PREGNANT',
    currentStage: 'PREGNANT',
    cowId: 'anim-1',
    cowAnimalId: 'anim-1',
    cowName: 'Bella Vista Star',
    cowEarTag: 'TAG-9021',
    cowBreed: 'Holstein Friesian',
    recipientDgr: 'DGR-HOL-9021',
    branding: 'BVS-01',
    managementGroupId: 'grp-1',
    donorCowId: 'anim-2',
    donorCowAnimalId: 'anim-2',
    donorCowName: 'Cloverdale Supernova Dam 91',
    donorCowBreed: 'Holstein Friesian',
    donorWeightKg: 680,
    donorBcsDay0: 3.5,
    donorIdentifier: 'US-8840219',
    bullId: 'anim-2',
    bullAnimalId: 'anim-2',
    bullName: 'Ironwood Titan Red',
    bullDgr: 'DGR-ANG-7782',
    bullBreed: 'Red Angus',
    semenBatchId: 'sb-1',
    semenBatchCode: 'SB-HOL-2601-F',
    embryoId: 'emb-1',
    embryoCode: 'EMB-2026-001',
    embryoBreed: 'Holstein Purebred',
    embryoBatch: 'BATCH-IVF-2601',
    embryoStage: 'Blastocyst (Code 4)',
    embryoGrade: 'Grade 1 (Excellent)',
    isFreshEmbryo: false,
    syncProtocol: '7-Day Co-Synch + CIDR Protocol',
    syncDate: '2026-01-05',
    syncBatch: 'SYNC-B26-01',
    removalDate: '2026-01-12',
    treatmentsApplied: '2mL GnRH (Factrel) at CIDR insert, 5mL PGF2a (Lutalyse) at CIDR removal',
    procedureType: 'ET',
    procedureDate: '2026-01-22',
    technician: 'Dr. Sarah Jenkins',
    procedureNotes: 'Transferred single frozen-thawed Grade 1 blastocyst into ipsilateral right horn with verified CL diameter of 22mm.',
    pregnancyChecks: [
      {
        id: 'chk-1',
        checkDate: '2026-02-21',
        date: '2026-02-21',
        checkType: 'CHECK_30',
        stageLabel: 'Day 30 Ultrasound',
        result: 'PREGNANT',
        daysInGestation: 30,
        technician: 'Dr. Sarah Jenkins',
        notes: 'Viable embryonic vesicle detected with heartbeat (165 bpm).',
      },
      {
        id: 'chk-2',
        checkDate: '2026-03-24',
        date: '2026-03-24',
        checkType: 'CHECK_60',
        stageLabel: 'Day 60 Recheck',
        result: 'PREGNANT',
        daysInGestation: 61,
        technician: 'Dr. Sarah Jenkins',
        notes: 'Fetus normally positioned, cotyledons well developed.',
      },
    ],
    checks: [
      {
        id: 'chk-1',
        checkDate: '2026-02-21',
        date: '2026-02-21',
        checkType: 'CHECK_30',
        stageLabel: 'Day 30 Ultrasound',
        result: 'PREGNANT',
        daysInGestation: 30,
        technician: 'Dr. Sarah Jenkins',
        notes: 'Viable embryonic vesicle detected with heartbeat (165 bpm).',
      },
      {
        id: 'chk-2',
        checkDate: '2026-03-24',
        date: '2026-03-24',
        checkType: 'CHECK_60',
        stageLabel: 'Day 60 Recheck',
        result: 'PREGNANT',
        daysInGestation: 61,
        technician: 'Dr. Sarah Jenkins',
        notes: 'Fetus normally positioned, cotyledons well developed.',
      },
    ],
    expectedCalvingDate: '2026-10-31',
    createdAt: '2026-01-05',
  },
  {
    id: 'rep-proc-2',
    code: 'RP-2026-002',
    status: 'INSEMINATED',
    currentStage: 'INSEMINATED',
    cowId: 'anim-3',
    cowAnimalId: 'anim-3',
    cowName: 'Sunset Daisy 402',
    cowEarTag: 'TAG-9022',
    cowBreed: 'Jersey Cross',
    recipientDgr: 'DGR-JER-402',
    bullId: 'anim-2',
    bullAnimalId: 'anim-2',
    bullName: 'Ironwood Titan Red',
    bullDgr: 'DGR-ANG-7782',
    bullBreed: 'Red Angus',
    semenBatchId: 'sb-2',
    semenBatchCode: 'SB-ANG-2601-C',
    syncProtocol: 'Ovsynch 56 Protocol',
    syncDate: '2026-08-15',
    syncBatch: 'SYNC-B26-08',
    procedureType: 'AI',
    procedureDate: '2026-08-26',
    technician: 'Carlos Mendez',
    procedureNotes: 'Artificial insemination performed 16 hours post-standing heat. High cervical tone, clear mucous discharge.',
    pregnancyChecks: [
      {
        id: 'chk-3',
        checkDate: '2026-09-25',
        date: '2026-09-25',
        checkType: 'CHECK_30',
        stageLabel: 'Day 30 Upcoming Ultrasound',
        result: 'INCONCLUSIVE',
        technician: 'Pending Schedule',
        notes: 'Ultrasound scheduled for Day 30 post-AI.',
      },
    ],
    checks: [
      {
        id: 'chk-3',
        checkDate: '2026-09-25',
        date: '2026-09-25',
        checkType: 'CHECK_30',
        stageLabel: 'Day 30 Upcoming Ultrasound',
        result: 'INCONCLUSIVE',
        technician: 'Pending Schedule',
        notes: 'Ultrasound scheduled for Day 30 post-AI.',
      },
    ],
    expectedCalvingDate: '2027-06-03',
    createdAt: '2026-08-15',
  },
];

export const initialRecipientEvaluations: RecipientEvaluation[] = [
  {
    id: 'rec-eval-1',
    code: 'EVAL-REC-2026-001',
    cowId: 'anim-1',
    cowName: 'Bella Vista Star',
    cowEarTag: 'TAG-9021',
    farmId: 'farm-1',
    farmName: 'North Valley Dairy',
    breed: 'Holstein Friesian',
    managementGroupId: 'grp-1',
    managementGroupName: 'Lactating Cows Group A',
    syncDate: '2026-01-05',
    estrousCycle: 'Normal 21-Day Synchronized Cycle',
    bcs: 3.25,
    earTagVerified: true,
    pregnancyDiagnosis: 'PREGNANT',
    lastPregnancyCheckDate: '2026-03-24',
    finalObservation: 'Uterine tone excellent, viable single fetus in right uterine horn, healthy CL.',
    pregnancyOutcome: 'Confirmed Pregnant (Day 60+)',
    vaccinationHistory: 'Bovi-Shield Gold FP5 L5, ScourGuard 4KC, Vision 8 Somnus',
    tickCount: 0,
    headEvaluation: 'Feminine, alert, clear eyes and clean muzzle',
    bodyType: 'Deep-bodied dairy wedge, wide pin bones',
    coatColor: 'Black & White piebald',
    muscleDevelopment: 'Moderate dairy muscling, clean flat bone',
    umbilicalCondition: 'Clean, no herniation or thickening',
    bodyStructure: 'Sound legs, strong pasterns, wide pelvic inlet ideal for unassisted calving',
    generalConformation: 'Class 1 Commercial Dairy Cow, excellent maternal instinct candidate',
    evaluatorName: 'Dr. Sarah Jenkins',
    evaluationDate: '2026-01-04',
    status: 'APPROVED_FOR_ET',
    notes: 'Approved as prime recipient for Grade 1 IVF blastocyst transfer. History of prompt conception.',
  },
  {
    id: 'rec-eval-2',
    code: 'EVAL-REC-2026-002',
    cowId: 'anim-3',
    cowName: 'Sunset Daisy 402',
    cowEarTag: 'TAG-9022',
    farmId: 'farm-1',
    farmName: 'North Valley Dairy',
    breed: 'Jersey Cross',
    managementGroupId: 'grp-2',
    managementGroupName: 'Breeding Heifers Pen 3',
    syncDate: '2026-08-15',
    estrousCycle: 'Normal 20-Day Cycle',
    bcs: 3.0,
    earTagVerified: true,
    pregnancyDiagnosis: 'PENDING',
    lastPregnancyCheckDate: '2026-08-26',
    finalObservation: 'Pending Day 30 ultrasound check after recent insemination.',
    vaccinationHistory: 'Bovi-Shield Gold 5, 7-Way Clostridial',
    tickCount: 2,
    headEvaluation: 'Feminine Jersey head, normal dentition',
    bodyType: 'Compact, high feed conversion efficiency frame',
    coatColor: 'Fawn with black points',
    muscleDevelopment: 'Good condition, level rump',
    umbilicalCondition: 'Normal',
    bodyStructure: 'Good pelvic angle, sound mobile hooves',
    generalConformation: 'Healthy second-lactation recipient candidate',
    evaluatorName: 'Carlos Mendez',
    evaluationDate: '2026-08-12',
    status: 'ELIGIBLE',
    notes: 'Cleared for AI/ET cycle. Minor tick load treated with pour-on eprinomectin.',
  },
];

