// Bovine Government Observer Institutional Portal Initial Datasets
// Provides realistic national, regional, surveillance, compliance,
// traceability, and investigation data.

import {
  Jurisdiction,
  ReportingPeriod,
  DataFreshness,
  MetricDefinition,
  InstitutionalKPI,
  DiseaseEvent,
  QuarantineRecord,
  VaccinationSurveillanceRecord,
  MovementException,
  ComplianceAudit,
  ComplianceFinding,
  CorrectiveAction,
  InspectionSchedule,
  DataQualityIssue,
  CrossFarmQualityScore,
  InvestigationCase,
  GovernmentProgram,
  GovernmentOfficial,
  OfficialAssignment,
  StandardReport,
  InstitutionalExportJob,
  InstitutionalAlert,
  InstitutionalTask,
} from './bovine-government-types';

export const initialJurisdictions: Jurisdiction[] = [
  {
    id: 'jur-national',
    code: 'ETH-NAT',
    name: 'National Livestock Oversight Authority',
    level: 'NATIONAL',
    country: 'Ethiopia',
    totalFarms: 1108,
    reportingFarms: 1042,
    registeredAnimals: 142850,
    activeBreedingStock: 24680,
    headquarters: 'Ministry of Agriculture, Gurd Shola, Addis Ababa',
    leadOfficialName: 'Dr. Dawit Hailemariam, Chief Veterinary Officer',
    contactEmail: 'cvo@moa-livestock.gov.et',
    status: 'ACTIVE',
  },
  {
    id: 'jur-oromia',
    code: 'ETH-ORO',
    name: 'Oromia Regional Livestock Agency',
    level: 'REGION',
    parentId: 'jur-national',
    parentName: 'National Livestock Oversight Authority',
    country: 'Ethiopia',
    totalFarms: 485,
    reportingFarms: 462,
    registeredAnimals: 64210,
    activeBreedingStock: 11840,
    headquarters: 'Bole Road Regional Office, Addis Ababa',
    leadOfficialName: 'Dr. Senait Bekele, Regional Director',
    contactEmail: 's.bekele@oromia-livestock.gov.et',
    status: 'ACTIVE',
  },
  {
    id: 'jur-amhara',
    code: 'ETH-AMH',
    name: 'Amhara Livestock & Fisheries Development Bureau',
    level: 'REGION',
    parentId: 'jur-national',
    parentName: 'National Livestock Oversight Authority',
    country: 'Ethiopia',
    totalFarms: 312,
    reportingFarms: 294,
    registeredAnimals: 41800,
    activeBreedingStock: 7420,
    headquarters: 'Regional Center, Bahir Dar',
    leadOfficialName: 'Ato Getachew Tadesse, Bureau Head',
    contactEmail: 'g.tadesse@amhara-agri.gov.et',
    status: 'ACTIVE',
  },
  {
    id: 'jur-sidama',
    code: 'ETH-SID',
    name: 'Sidama Regional Veterinary Services',
    level: 'REGION',
    parentId: 'jur-national',
    parentName: 'National Livestock Oversight Authority',
    country: 'Ethiopia',
    totalFarms: 145,
    reportingFarms: 138,
    registeredAnimals: 19440,
    activeBreedingStock: 3260,
    headquarters: 'Central Veterinary Office, Hawassa',
    leadOfficialName: 'Dr. Aster Kassa, State Vet Officer',
    contactEmail: 'a.kassa@sidama-livestock.gov.et',
    status: 'ACTIVE',
  },
  {
    id: 'jur-adama-district',
    code: 'ETH-ORO-ADA',
    name: 'Adama District Veterinary Office',
    level: 'DISTRICT',
    parentId: 'jur-oromia',
    parentName: 'Oromia Regional Livestock Agency',
    country: 'Ethiopia',
    totalFarms: 98,
    reportingFarms: 94,
    registeredAnimals: 14120,
    activeBreedingStock: 2650,
    headquarters: 'Veterinary Diagnostic Post, Adama',
    leadOfficialName: 'Dr. Merga Negassa, District Lead',
    contactEmail: 'adama.vet@oromia-livestock.gov.et',
    status: 'ACTIVE',
  },
  {
    id: 'jur-bishoftu-district',
    code: 'ETH-ORO-BIS',
    name: 'Bishoftu Genetics Surveillance Sector',
    level: 'DISTRICT',
    parentId: 'jur-oromia',
    parentName: 'Oromia Regional Livestock Agency',
    country: 'Ethiopia',
    totalFarms: 124,
    reportingFarms: 120,
    registeredAnimals: 18950,
    activeBreedingStock: 3890,
    headquarters: 'National AI & Genetics Center, Bishoftu',
    leadOfficialName: 'Dr. Yonas Alemayehu, Chief Geneticist',
    contactEmail: 'bishoftu.surveillance@oromia-livestock.gov.et',
    status: 'ACTIVE',
  },
];

export const initialReportingPeriods: ReportingPeriod[] = [
  {
    key: 'TODAY',
    label: 'Today (Live)',
    fromDate: '2026-09-08',
    toDate: '2026-09-08',
    comparisonPeriodLabel: 'Yesterday',
  },
  {
    key: 'LAST_7_DAYS',
    label: 'Last 7 Days',
    fromDate: '2026-09-01',
    toDate: '2026-09-08',
    comparisonPeriodLabel: 'Prior 7 Days',
  },
  {
    key: 'LAST_30_DAYS',
    label: 'Last 30 Days',
    fromDate: '2026-08-09',
    toDate: '2026-09-08',
    comparisonPeriodLabel: 'Prior 30 Days',
  },
  {
    key: 'CURRENT_QUARTER',
    label: 'Q3 2026',
    fromDate: '2026-07-01',
    toDate: '2026-09-08',
    comparisonPeriodLabel: 'Q2 2026',
  },
  {
    key: 'YTD',
    label: 'Year to Date (2026)',
    fromDate: '2026-01-01',
    toDate: '2026-09-08',
    comparisonPeriodLabel: 'Same Period 2025',
  },
  {
    key: 'PREVIOUS_YEAR',
    label: 'Full Year 2025',
    fromDate: '2025-01-01',
    toDate: '2025-12-31',
    comparisonPeriodLabel: 'Full Year 2024',
  },
  {
    key: 'SNAPSHOT_2025',
    label: 'Historical Cutoff (31 Dec 2025)',
    fromDate: '2025-01-01',
    toDate: '2025-12-31',
    isSnapshot: true,
    snapshotDate: '2025-12-31',
    comparisonPeriodLabel: '31 Dec 2024 Snapshot',
  },
];

export const initialDataFreshness: DataFreshness = {
  lastUpdated: '08 Sep 2026 06:42 UTC',
  reportingFarms: 1042,
  totalFarms: 1108,
  coveragePct: 94.0,
  medianLagDays: 1.8,
  status: 'CURRENT',
  notes: '66 commercial feedlots and pastoral co-ops pending weekly batch telemetry sync.',
};

export const initialMetricDefinitions: Record<string, MetricDefinition> = {
  'pop-total': {
    key: 'pop-total',
    title: 'Total Active Registered Livestock',
    shortDescription: 'Total count of live bovine individuals registered under national livestock traceability systems.',
    numerator: 'Sum of live animals with active national registry ID or DGR',
    denominator: '1 (absolute headcount)',
    includedPopulation: 'All registered cattle residing in jurisdiction without confirmed death or export status',
    excludedPopulation: 'Deregistered, slaughtered, dead, or exported individuals',
    dataSources: ['National Registry Database', 'Farm Electronic Logbooks', 'Port of Entry Declarations'],
    calculationLagDays: 0.5,
    version: 'REG-2026-v1.4',
    regulatoryStandardRef: 'WOAH Terrestrial Code Chapter 4.2 / MoA Directives 2024-08',
  },
  'pop-growth': {
    key: 'pop-growth',
    title: 'Net Population Growth Rate',
    shortDescription: 'Percentage expansion of bovine census comparing opening and closing headcount.',
    numerator: '(Closing Population - Opening Population)',
    denominator: 'Opening Population',
    includedPopulation: 'All verified bovine head within the reporting window',
    excludedPopulation: 'Unverified transient market cattle (<48h transit)',
    dataSources: ['Vital Statistics Registry', 'Farm Birth/Death Records'],
    calculationLagDays: 1.0,
    version: 'STAT-POP-v2.1',
  },
  'vax-coverage': {
    key: 'vax-coverage',
    title: 'Vaccination Surveillance Coverage',
    shortDescription: 'Percentage of eligible cattle receiving mandated prophylactic biologics within scheduled schedule.',
    numerator: 'Count of animals with verified vaccine batch administration within efficacy window',
    denominator: 'Total eligible head based on age, sex, and epidemiological zone requirements',
    includedPopulation: 'All cattle residing in compulsory immunization zones for designated pathogens (FMD, LSD, CBPP)',
    excludedPopulation: 'Calves below minimum vaccine age or medically exempted animals',
    dataSources: ['Veterinary Administration Logs', 'District Cold-Chain Manifests'],
    calculationLagDays: 2.0,
    version: 'EPI-VAX-2026',
    regulatoryStandardRef: 'Veterinary Drug and Biologics Control Proclamation 728/2021',
  },
  'gen-inbreeding': {
    key: 'gen-inbreeding',
    title: 'Mean Inbreeding Coefficient (Wright’s F)',
    shortDescription: 'Population-level probability that two alleles at any locus are identical by descent.',
    numerator: 'Sum of individual inbreeding coefficients (Pedigree F and Genomic FROH)',
    denominator: 'Total evaluated animals in target breeding population',
    includedPopulation: 'Animals with >= 3 recorded ancestor generations or high-density SNP genotyping',
    excludedPopulation: 'Commercial crossbred feedlot stock without breeding enrollment',
    dataSources: ['National Pedigree Repository', 'Genotyping Laboratories BeadChip Assays'],
    calculationLagDays: 7.0,
    version: 'GEN-EVAL-v3.2',
    regulatoryStandardRef: 'FAO Animal Genetic Resources Guidelines 2023',
  },
  'repro-pregnancy': {
    key: 'repro-pregnancy',
    title: 'Confirmed Herd Pregnancy Rate',
    shortDescription: 'Proportion of eligible breeding females confirmed pregnant following AI or natural service.',
    numerator: 'Females with ultrasound or palpation positive pregnancy check',
    denominator: 'Total breeding females serviced during evaluated breeding season',
    includedPopulation: 'Breeding-age heifers and cows serviced >35 days prior to check date',
    excludedPopulation: 'Culled or sick non-breeding females',
    dataSources: ['Reproductive Diagnostics', 'Field AI Tech Logs'],
    calculationLagDays: 1.5,
    version: 'REPRO-STD-2025',
  },
  'farm-compliance': {
    key: 'farm-compliance',
    title: 'Institutional Farm Regulatory Compliance Index',
    shortDescription: 'Composite score evaluating farm adherence across identification, movement, and disease reporting.',
    numerator: 'Sum of weighted compliance dimension points (0-100 scale)',
    denominator: 'Applicable regulatory standard categories',
    includedPopulation: 'All officially licensed agricultural holdings and breeding studs',
    excludedPopulation: 'Informal household subsistence herds (<2 head)',
    dataSources: ['Official Inspector Audits', 'Automated Exception Rule Engines'],
    calculationLagDays: 1.0,
    version: 'AUDIT-COMPL-v2.0',
    regulatoryStandardRef: 'National Animal Identification & Traceability Directive 88/2023',
  },
};

export const initialInstitutionalKPIs: InstitutionalKPI[] = [
  // Population
  {
    key: 'pop-registered',
    label: 'Registered Cattle Census',
    value: 142850,
    formattedValue: '142,850',
    unit: 'Head',
    changePct: 4.8,
    previousPeriodValue: 136300,
    target: 150000,
    coveragePct: 94.0,
    severity: 'NORMAL',
    category: 'POPULATION',
    definitionKey: 'pop-total',
  },
  {
    key: 'pop-breeding-females',
    label: 'Eligible Breeding Cows & Heifers',
    value: 68420,
    formattedValue: '68,420',
    unit: 'Head',
    changePct: 3.2,
    previousPeriodValue: 66300,
    target: 70000,
    coveragePct: 95.2,
    severity: 'NORMAL',
    category: 'POPULATION',
    definitionKey: 'pop-total',
  },
  {
    key: 'pop-births-ytd',
    label: 'Live Calves Born YTD',
    value: 28410,
    formattedValue: '28,410',
    unit: 'Calves',
    changePct: 8.6,
    previousPeriodValue: 26160,
    coveragePct: 93.8,
    severity: 'NORMAL',
    category: 'POPULATION',
    definitionKey: 'pop-growth',
  },
  {
    key: 'pop-deaths-ytd',
    label: 'Reported Cattle Mortality',
    value: 4120,
    formattedValue: '4,120',
    unit: 'Head',
    changePct: -1.4,
    previousPeriodValue: 4180,
    coveragePct: 92.4,
    severity: 'WATCH',
    category: 'POPULATION',
    definitionKey: 'pop-growth',
  },

  // Farms & Reporting
  {
    key: 'farm-reporting-coverage',
    label: 'Commercial Reporting Coverage',
    value: 94.0,
    formattedValue: '94.0%',
    unit: '%',
    changePct: 2.1,
    previousPeriodValue: 92.1,
    target: 95.0,
    coveragePct: 100.0,
    severity: 'NORMAL',
    category: 'FARMS',
    definitionKey: 'farm-compliance',
  },
  {
    key: 'farm-non-reporting',
    label: 'Farms with Overdue Logs (>14d)',
    value: 66,
    formattedValue: '66',
    unit: 'Farms',
    changePct: -12.0,
    previousPeriodValue: 75,
    coveragePct: 100.0,
    severity: 'WATCH',
    category: 'FARMS',
    definitionKey: 'farm-compliance',
  },

  // Health
  {
    key: 'health-vax-coverage',
    label: 'National Compulsory Vaccination',
    value: 86.4,
    formattedValue: '86.4%',
    unit: '%',
    changePct: 5.4,
    previousPeriodValue: 82.0,
    target: 95.0,
    coveragePct: 91.2,
    severity: 'WATCH',
    category: 'HEALTH',
    definitionKey: 'vax-coverage',
  },
  {
    key: 'health-active-outbreaks',
    label: 'Active Biosecurity Disease Alerts',
    value: 4,
    formattedValue: '4',
    unit: 'Clusters',
    changePct: 33.3,
    previousPeriodValue: 3,
    coveragePct: 100.0,
    severity: 'CRITICAL',
    category: 'HEALTH',
    definitionKey: 'vax-coverage',
  },
  {
    key: 'health-quarantined',
    label: 'Cattle Under Active Quarantine',
    value: 840,
    formattedValue: '840',
    unit: 'Head',
    changePct: 28.0,
    previousPeriodValue: 656,
    coveragePct: 100.0,
    severity: 'WARNING',
    category: 'HEALTH',
    definitionKey: 'vax-coverage',
  },

  // Reproduction
  {
    key: 'repro-pregnancy-rate',
    label: 'National AI/Service Pregnancy Rate',
    value: 71.3,
    formattedValue: '71.3%',
    unit: '%',
    changePct: 2.3,
    previousPeriodValue: 69.7,
    target: 75.0,
    coveragePct: 94.6,
    severity: 'NORMAL',
    category: 'REPRODUCTION',
    definitionKey: 'repro-pregnancy',
  },
  {
    key: 'repro-calf-survival',
    label: '30-Day Neonatal Calf Survival',
    value: 93.8,
    formattedValue: '93.8%',
    unit: '%',
    changePct: 1.1,
    previousPeriodValue: 92.8,
    target: 96.0,
    coveragePct: 92.0,
    severity: 'NORMAL',
    category: 'REPRODUCTION',
    definitionKey: 'repro-pregnancy',
  },

  // Genetics
  {
    key: 'gen-coverage',
    label: 'Seedstock Genotype Coverage',
    value: 38.6,
    formattedValue: '38.6%',
    unit: '%',
    changePct: 9.2,
    previousPeriodValue: 35.3,
    target: 50.0,
    coveragePct: 98.0,
    severity: 'WATCH',
    category: 'GENETICS',
    definitionKey: 'gen-inbreeding',
  },
  {
    key: 'gen-mean-inbreeding',
    label: 'Average Pedigree Inbreeding (F)',
    value: 3.82,
    formattedValue: '3.82%',
    unit: '%',
    changePct: 0.12,
    previousPeriodValue: 3.78,
    target: 5.0, // Cap
    coveragePct: 89.0,
    severity: 'NORMAL',
    category: 'GENETICS',
    definitionKey: 'gen-inbreeding',
  },

  // Compliance
  {
    key: 'compliance-audited-pct',
    label: 'Inspected & Audited Holdings',
    value: 88.5,
    formattedValue: '88.5%',
    unit: '%',
    changePct: 6.2,
    previousPeriodValue: 83.3,
    target: 92.0,
    coveragePct: 100.0,
    severity: 'NORMAL',
    category: 'COMPLIANCE',
    definitionKey: 'farm-compliance',
  },
  {
    key: 'compliance-critical-findings',
    label: 'Unresolved Critical Non-Compliances',
    value: 12,
    formattedValue: '12',
    unit: 'Findings',
    changePct: -25.0,
    previousPeriodValue: 16,
    coveragePct: 100.0,
    severity: 'CRITICAL',
    category: 'COMPLIANCE',
    definitionKey: 'farm-compliance',
  },

  // Movement & Traceability
  {
    key: 'movement-exceptions',
    label: 'Active Movement Protocol Breaches',
    value: 18,
    formattedValue: '18',
    unit: 'Incidents',
    changePct: -10.0,
    previousPeriodValue: 20,
    coveragePct: 98.4,
    severity: 'WARNING',
    category: 'MOVEMENT',
    definitionKey: 'farm-compliance',
  },

  // Data Quality
  {
    key: 'quality-pedigree-conflicts',
    label: 'DNA/Genomic Parentage Conflicts',
    value: 9,
    formattedValue: '9',
    unit: 'Cases',
    changePct: -30.7,
    previousPeriodValue: 13,
    coveragePct: 100.0,
    severity: 'WARNING',
    category: 'DATA_QUALITY',
    definitionKey: 'gen-inbreeding',
  },
];

export const initialDiseaseEvents: DiseaseEvent[] = [
  {
    id: 'dis-001',
    code: 'DE-2026-089',
    diseaseCode: 'FMD-O',
    diseaseName: 'Foot and Mouth Disease (Serotype O)',
    confirmedStatus: 'CONFIRMED',
    farmId: 'farm-1',
    farmName: 'Rift Valley Commercial Ranch',
    regionId: 'jur-oromia',
    regionName: 'Oromia',
    districtId: 'jur-adama-district',
    districtName: 'Adama',
    animalsAffected: 42,
    deathsCount: 2,
    quarantinedCount: 280,
    reportingSource: 'District Vet Mobile Diagnostic PCR',
    reportedAt: '2026-09-02',
    status: 'INVESTIGATING',
    quarantineActive: true,
    investigationCaseId: 'inv-case-001',
    notes: 'Index case identified during feeder stock entry inspection. Movement radius locked.',
  },
  {
    id: 'dis-002',
    code: 'DE-2026-091',
    diseaseCode: 'LSD',
    diseaseName: 'Lumpy Skin Disease (Capripoxvirus)',
    confirmedStatus: 'CONFIRMED',
    farmId: 'farm-2',
    farmName: 'Awash Pastoral Syndicate Feedlot',
    regionId: 'jur-oromia',
    regionName: 'Oromia',
    districtId: 'jur-bishoftu-district',
    districtName: 'Bishoftu',
    animalsAffected: 18,
    deathsCount: 1,
    quarantinedCount: 195,
    reportingSource: 'National Veterinary Institute Lab',
    reportedAt: '2026-09-04',
    status: 'OPEN',
    quarantineActive: true,
    investigationCaseId: 'inv-case-003',
    notes: 'Vector transmission suspected after unseasonal rainfall. Ring vaccination underway.',
  },
  {
    id: 'dis-003',
    code: 'DE-2026-074',
    diseaseCode: 'CBPP',
    diseaseName: 'Contagious Bovine Pleuropneumonia',
    confirmedStatus: 'SUSPECTED',
    farmId: 'farm-3',
    farmName: 'Tana Highlands Dairy Cooperative',
    regionId: 'jur-amhara',
    regionName: 'Amhara',
    districtId: 'jur-amhara',
    districtName: 'Bahir Dar Zuria',
    animalsAffected: 14,
    deathsCount: 3,
    quarantinedCount: 140,
    reportingSource: 'Regional Sentinel Surveillance',
    reportedAt: '2026-08-28',
    status: 'CONTAINED',
    quarantineActive: true,
    notes: 'Serological test confirmation pending. Antibiotic treatment prohibited per national protocol.',
  },
  {
    id: 'dis-004',
    code: 'DE-2026-062',
    diseaseCode: 'BRUCELLA',
    diseaseName: 'Bovine Brucellosis (B. abortus)',
    confirmedStatus: 'CONFIRMED',
    farmId: 'farm-4',
    farmName: 'Hawassa Nucleus Breeding Station',
    regionId: 'jur-sidama',
    regionName: 'Sidama',
    districtId: 'jur-sidama',
    districtName: 'Hawassa',
    animalsAffected: 6,
    deathsCount: 0,
    quarantinedCount: 45,
    reportingSource: 'Routine Milk Ring Surveillance',
    reportedAt: '2026-08-14',
    status: 'CONTAINED',
    quarantineActive: true,
    notes: 'Positive reactors isolated for controlled culling and compensation protocol.',
  },
];

export const initialQuarantineRecords: QuarantineRecord[] = [
  {
    id: 'quar-001',
    farmId: 'farm-1',
    farmName: 'Rift Valley Commercial Ranch',
    regionId: 'jur-oromia',
    regionName: 'Oromia',
    reason: 'Foot and Mouth Disease outbreak containment',
    diseaseEventId: 'dis-001',
    startedAt: '2026-09-02',
    expectedEndAt: '2026-10-02',
    animalsAffected: 280,
    movementsBlocked: 8,
    status: 'ACTIVE',
    authorizedBy: 'Dr. Senait Bekele, Regional Director',
    notes: 'Strict bio-tier 3 exclusion zone. No vehicle access without wheel-wash sanitation.',
  },
  {
    id: 'quar-002',
    farmId: 'farm-2',
    farmName: 'Awash Pastoral Syndicate Feedlot',
    regionId: 'jur-oromia',
    regionName: 'Oromia',
    reason: 'Lumpy Skin Disease containment and vector control',
    diseaseEventId: 'dis-002',
    startedAt: '2026-09-04',
    expectedEndAt: '2026-10-04',
    animalsAffected: 195,
    movementsBlocked: 4,
    status: 'ACTIVE',
    authorizedBy: 'Dr. Merga Negassa, District Lead',
  },
];

export const initialVaccinationSurveillance: VaccinationSurveillanceRecord[] = [
  {
    id: 'vax-rec-01',
    regionId: 'jur-oromia',
    regionName: 'Oromia',
    districtId: 'jur-adama-district',
    districtName: 'Adama',
    vaccineCode: 'VAC-FMD-BI',
    vaccineName: 'FMD Bivalent (O & A)',
    eligibleAnimals: 11200,
    vaccinatedAnimals: 9850,
    overdueAnimals: 1350,
    coveragePct: 87.9,
    targetPct: 95.0,
    farmsBelowTargetCount: 14,
    campaignStatus: 'NEEDS_ATTENTION',
    lastCampaignDate: '2026-07-20',
  },
  {
    id: 'vax-rec-02',
    regionId: 'jur-oromia',
    regionName: 'Oromia',
    districtId: 'jur-bishoftu-district',
    districtName: 'Bishoftu',
    vaccineCode: 'VAC-LSD-NEO',
    vaccineName: 'LSD Neethling Strain Live',
    eligibleAnimals: 15400,
    vaccinatedAnimals: 14200,
    overdueAnimals: 1200,
    coveragePct: 92.2,
    targetPct: 95.0,
    farmsBelowTargetCount: 8,
    campaignStatus: 'COMPLIANT',
    lastCampaignDate: '2026-08-10',
  },
  {
    id: 'vax-rec-03',
    regionId: 'jur-amhara',
    regionName: 'Amhara',
    districtId: 'jur-amhara',
    districtName: 'Bahir Dar Zuria',
    vaccineCode: 'VAC-ANTHRAX',
    vaccineName: 'Anthrax Spore Vaccine',
    eligibleAnimals: 22000,
    vaccinatedAnimals: 16800,
    overdueAnimals: 5200,
    coveragePct: 76.4,
    targetPct: 90.0,
    farmsBelowTargetCount: 38,
    campaignStatus: 'CRITICAL_GAP',
    lastCampaignDate: '2026-05-15',
  },
  {
    id: 'vax-rec-04',
    regionId: 'jur-sidama',
    regionName: 'Sidama',
    districtId: 'jur-sidama',
    districtName: 'Hawassa Rural',
    vaccineCode: 'VAC-CBPP-T1',
    vaccineName: 'CBPP T1/44 Broth Culture',
    eligibleAnimals: 14200,
    vaccinatedAnimals: 13150,
    overdueAnimals: 1050,
    coveragePct: 92.6,
    targetPct: 95.0,
    farmsBelowTargetCount: 6,
    campaignStatus: 'COMPLIANT',
    lastCampaignDate: '2026-06-30',
  },
];

export const initialMovementExceptions: MovementException[] = [
  {
    id: 'mex-001',
    movementId: 'mov-982',
    type: 'QUARANTINE_BREACH',
    severity: 'CRITICAL',
    farmOriginId: 'farm-1',
    farmOriginName: 'Rift Valley Commercial Ranch',
    farmDestId: 'farm-2',
    farmDestName: 'Awash Pastoral Syndicate Feedlot',
    animalId: 'anim-1',
    animalName: 'Apex Queen Helena',
    animalIdentifier: 'ETH-2024-88412',
    occurredAt: '2026-09-03',
    details: 'Movement dispatched while farm-1 was under active Foot and Mouth Disease quarantine lock.',
    resolved: false,
    investigationCaseId: 'inv-case-001',
  },
  {
    id: 'mex-002',
    movementId: 'mov-985',
    type: 'UNREGISTERED_DESTINATION',
    severity: 'WARNING',
    farmOriginId: 'farm-3',
    farmOriginName: 'Tana Highlands Dairy Cooperative',
    animalId: 'anim-4',
    animalName: 'Tana Star Pioneer',
    animalIdentifier: 'ETH-2025-10294',
    occurredAt: '2026-09-05',
    details: 'Holding location code ETH-MKT-992 is not certified in national traceability directory.',
    resolved: false,
  },
  {
    id: 'mex-003',
    movementId: 'mov-974',
    type: 'IMPOSSIBLE_DATES',
    severity: 'WARNING',
    farmOriginId: 'farm-4',
    farmOriginName: 'Hawassa Nucleus Breeding Station',
    farmDestId: 'farm-1',
    farmDestName: 'Rift Valley Commercial Ranch',
    animalId: 'anim-7',
    animalName: 'Hawassa Chief 41',
    animalIdentifier: 'ETH-2024-55190',
    occurredAt: '2026-08-30',
    details: 'Arrival timestamp logged 14 hours prior to departure timestamp.',
    resolved: true,
    resolvedAt: '2026-09-02',
    resolvedBy: 'Dr. Dawit Hailemariam',
  },
];

export const initialComplianceAudits: ComplianceAudit[] = [
  {
    id: 'aud-2026-01',
    code: 'AUD-ORO-2026-042',
    farmId: 'farm-1',
    farmName: 'Rift Valley Commercial Ranch',
    regionId: 'jur-oromia',
    regionName: 'Oromia',
    type: 'DISEASE_FOLLOW_UP',
    scope: 'Epidemiological perimeter containment & animal tracking logs',
    auditorName: 'Insp. Solomon Getahun',
    auditorId: 'off-04',
    openedAt: '2026-09-03',
    status: 'IN_PROGRESS',
    scorePct: 68.0,
    openFindings: 3,
    criticalFindings: 1,
    followUpDueAt: '2026-09-17',
  },
  {
    id: 'aud-2026-02',
    code: 'AUD-AMH-2026-019',
    farmId: 'farm-3',
    farmName: 'Tana Highlands Dairy Cooperative',
    regionId: 'jur-amhara',
    regionName: 'Amhara',
    type: 'ROUTINE_ANNUAL',
    scope: 'Full regulatory certification (IDs, Vax, Welfare, Biosecurity)',
    auditorName: 'Insp. Tigist Belay',
    auditorId: 'off-05',
    openedAt: '2026-08-20',
    completedAt: '2026-08-25',
    status: 'COMPLETED',
    scorePct: 91.5,
    openFindings: 1,
    criticalFindings: 0,
    followUpDueAt: '2026-11-25',
  },
  {
    id: 'aud-2026-03',
    code: 'AUD-SID-2026-008',
    farmId: 'farm-4',
    farmName: 'Hawassa Nucleus Breeding Station',
    regionId: 'jur-sidama',
    regionName: 'Sidama',
    type: 'TRACEABILITY_AUDIT',
    scope: 'Parentage verification & RFID ear-tag reconciliation',
    auditorName: 'Insp. Solomon Getahun',
    auditorId: 'off-04',
    openedAt: '2026-08-10',
    completedAt: '2026-08-12',
    status: 'COMPLETED',
    scorePct: 96.0,
    openFindings: 0,
    criticalFindings: 0,
  },
];

export const initialComplianceFindings: ComplianceFinding[] = [
  {
    id: 'find-001',
    auditId: 'aud-2026-01',
    farmId: 'farm-1',
    farmName: 'Rift Valley Commercial Ranch',
    category: 'MOVEMENT',
    severity: 'CRITICAL',
    description: 'Animal ETH-2024-88412 was dispatched from quarantine paddock without statutory veterinary permit.',
    policyReference: 'Animal Disease Prevention Proclamation 402/2004, Section 14(a)',
    responsibleParty: 'Farm Operations Manager, Ato Berhanu Kebede',
    openedAt: '2026-09-03',
    dueAt: '2026-09-10',
    status: 'CORRECTIVE_ACTION_ISSUED',
    correctiveActionId: 'ca-001',
  },
  {
    id: 'find-002',
    auditId: 'aud-2026-01',
    farmId: 'farm-1',
    farmName: 'Rift Valley Commercial Ranch',
    category: 'IDENTITY',
    severity: 'MAJOR',
    description: '14 head of newly arrived crossbred heifers lacked secondary ear tags and had no registered RFID entry.',
    policyReference: 'National Livestock Identification System (NLIS) Mandate 02-B',
    responsibleParty: 'Livestock Registrar, W/o Almaz Mengistu',
    openedAt: '2026-09-03',
    dueAt: '2026-09-17',
    status: 'OPEN',
  },
  {
    id: 'find-003',
    auditId: 'aud-2026-02',
    farmId: 'farm-3',
    farmName: 'Tana Highlands Dairy Cooperative',
    category: 'VACCINATION',
    severity: 'MINOR',
    description: 'Vaccine batch expiry verification log missing technician signature on 3 administration dates.',
    policyReference: 'Veterinary Good Practice Standard Section 4.8',
    responsibleParty: 'Co-op Head Vet',
    openedAt: '2026-08-24',
    dueAt: '2026-09-24',
    status: 'RESPONSE_SUBMITTED',
    correctiveActionId: 'ca-002',
  },
];

export const initialCorrectiveActions: CorrectiveAction[] = [
  {
    id: 'ca-001',
    findingId: 'find-001',
    farmId: 'farm-1',
    farmName: 'Rift Valley Commercial Ranch',
    actionRequired: 'Immediately recall animal ETH-2024-88412 into isolation, submit written explanation and disciplinary log.',
    issuedBy: 'Insp. Solomon Getahun',
    issuedAt: '2026-09-03',
    responseDeadline: '2026-09-10',
    outcome: 'PENDING',
    notes: 'Farm manager acknowledged via signed letter. Transporter vehicle currently being disinfected.',
  },
  {
    id: 'ca-002',
    findingId: 'find-003',
    farmId: 'farm-3',
    farmName: 'Tana Highlands Dairy Cooperative',
    actionRequired: 'Conduct audit of all cold-chain vaccine batches and implement two-signature signoff procedure.',
    issuedBy: 'Insp. Tigist Belay',
    issuedAt: '2026-08-25',
    responseDeadline: '2026-09-24',
    farmResponse: 'Staff retraining complete on 01 Sep. Dual-signature digital template deployed to all barn tablets.',
    submittedAt: '2026-09-02',
    reviewedBy: 'Insp. Tigist Belay',
    reviewedAt: '2026-09-04',
    outcome: 'ACCEPTED',
    notes: 'Corrective action evidence verified satisfactory. Finding will close upon next routine inspection.',
  },
];

export const initialInspectionSchedules: InspectionSchedule[] = [
  {
    id: 'insp-01',
    farmId: 'farm-1',
    farmName: 'Rift Valley Commercial Ranch',
    regionName: 'Oromia',
    scheduledDate: '2026-09-14',
    inspectorName: 'Insp. Solomon Getahun',
    type: 'DISEASE_SPOT_CHECK',
    status: 'UPCOMING',
    previousScore: 68,
    checklistItemsCount: 24,
  },
  {
    id: 'insp-02',
    farmId: 'farm-2',
    farmName: 'Awash Pastoral Syndicate Feedlot',
    regionName: 'Oromia',
    scheduledDate: '2026-09-08',
    inspectorName: 'Dr. Merga Negassa',
    type: 'DISEASE_SPOT_CHECK',
    status: 'TODAY',
    previousScore: 74,
    checklistItemsCount: 18,
  },
  {
    id: 'insp-03',
    farmId: 'farm-4',
    farmName: 'Hawassa Nucleus Breeding Station',
    regionName: 'Sidama',
    scheduledDate: '2026-09-22',
    inspectorName: 'Dr. Aster Kassa',
    type: 'ANNUAL_CERTIFICATION',
    status: 'UPCOMING',
    previousScore: 96,
    checklistItemsCount: 36,
  },
];

export const initialCrossFarmQualityScores: CrossFarmQualityScore[] = [
  {
    farmId: 'farm-4',
    farmName: 'Hawassa Nucleus Breeding Station',
    regionName: 'Sidama',
    identityScore: 98,
    pedigreeScore: 97,
    healthScore: 94,
    reproductionScore: 96,
    movementScore: 99,
    geneticsScore: 98,
    overallScore: 97.0,
    reportingLagDays: 0.8,
    lastUpdated: '2026-09-08',
  },
  {
    farmId: 'farm-3',
    farmName: 'Tana Highlands Dairy Cooperative',
    regionName: 'Amhara',
    identityScore: 94,
    pedigreeScore: 91,
    healthScore: 88,
    reproductionScore: 90,
    movementScore: 92,
    geneticsScore: 89,
    overallScore: 90.7,
    reportingLagDays: 1.4,
    lastUpdated: '2026-09-07',
  },
  {
    farmId: 'farm-2',
    farmName: 'Awash Pastoral Syndicate Feedlot',
    regionName: 'Oromia',
    identityScore: 82,
    pedigreeScore: 78,
    healthScore: 74,
    reproductionScore: 80,
    movementScore: 79,
    geneticsScore: 75,
    overallScore: 78.0,
    reportingLagDays: 3.2,
    lastUpdated: '2026-09-06',
  },
  {
    farmId: 'farm-1',
    farmName: 'Rift Valley Commercial Ranch',
    regionName: 'Oromia',
    identityScore: 76,
    pedigreeScore: 82,
    healthScore: 65,
    reproductionScore: 84,
    movementScore: 68,
    geneticsScore: 86,
    overallScore: 76.8,
    reportingLagDays: 4.5,
    lastUpdated: '2026-09-05',
  },
];

export const initialDataQualityIssues: DataQualityIssue[] = [
  {
    id: 'dqi-001',
    category: 'PEDIGREE',
    title: 'DNA Marker Exclusion in Recorded Sire',
    description: 'Offspring ETH-2025-9921 excludes registered sire ETH-2020-0014 across 32 autosomal SNP loci.',
    affectedEntityType: 'PARENTAGE',
    affectedEntityId: 'par-eth-9921',
    affectedEntityLabel: 'Offspring ETH-2025-9921 x Sire Apex Dominator',
    farmId: 'farm-1',
    farmName: 'Rift Valley Commercial Ranch',
    severity: 'CRITICAL',
    detectedAt: '2026-09-01',
    status: 'IN_REVIEW',
    proposedCorrection: 'Reassign parentage to alternate artificial insemination bull ETH-2021-0082 or flag as UNVERIFIED.',
  },
  {
    id: 'dqi-002',
    category: 'IDENTITY',
    title: 'Duplicate National RFID Tag Allocated',
    description: 'RFID 840003291823901 assigned to both heifer ETH-2025-0104 and steer ETH-2024-8192.',
    affectedEntityType: 'ANIMAL',
    affectedEntityId: 'anim-12',
    affectedEntityLabel: 'RFID Tag 840003291823901',
    farmId: 'farm-2',
    farmName: 'Awash Pastoral Syndicate Feedlot',
    severity: 'CRITICAL',
    detectedAt: '2026-08-29',
    status: 'OPEN',
    proposedCorrection: 'Physical re-tagging of animal anim-12 with new certified tag series.',
  },
  {
    id: 'dqi-003',
    category: 'REPRODUCTION',
    title: 'Calving Record with Negative Gestation',
    description: 'Calving recorded on 2026-08-10 with AI service recorded on 2026-04-12 (Gestation 120 days).',
    affectedEntityType: 'PREGNANCY',
    affectedEntityId: 'preg-8821',
    affectedEntityLabel: 'Dam ETH-2022-7718',
    farmId: 'farm-3',
    farmName: 'Tana Highlands Dairy Cooperative',
    severity: 'WARNING',
    detectedAt: '2026-08-12',
    status: 'OPEN',
    proposedCorrection: 'Verify whether calving was natural pasture service prior to reported AI cycle.',
  },
];

export const initialInvestigationCases: InvestigationCase[] = [
  {
    id: 'inv-case-001',
    caseNumber: 'INV-2026-004',
    title: 'Illegal Movement Breach During FMD Quarantine Lock',
    caseType: 'MOVEMENT_IRREGULARITY',
    severity: 'CRITICAL',
    priority: 'P1',
    leadInvestigatorName: 'Insp. Solomon Getahun',
    leadInvestigatorId: 'off-04',
    jurisdictionId: 'jur-oromia',
    jurisdictionName: 'Oromia Regional Livestock Agency',
    status: 'EVIDENCE_COLLECTION',
    openedAt: '2026-09-03',
    summary: 'Investigation into unauthorized transfer of 18 cattle from quarantined feedlot Rift Valley Ranch to Awash Feedlot.',
    evidenceItems: [
      {
        id: 'evi-101',
        caseId: 'inv-case-001',
        entityType: 'FARM',
        entityId: 'farm-1',
        label: 'Rift Valley Commercial Ranch',
        description: 'Origin farm under active quarantine order dated 02 Sep 2026.',
        relation: 'CONTAMINATED_ORIGIN',
        relevanceScore: 98,
        pinned: true,
        timestamp: '2026-09-02',
      },
      {
        id: 'evi-102',
        caseId: 'inv-case-001',
        entityType: 'ANIMAL',
        entityId: 'anim-1',
        label: 'Apex Queen Helena (ETH-2024-88412)',
        description: 'Heifer transferred during quarantine window without health permit.',
        relation: 'PRIMARY_SUSPECT',
        relevanceScore: 95,
        pinned: true,
        timestamp: '2026-09-03',
      },
      {
        id: 'evi-103',
        caseId: 'inv-case-001',
        entityType: 'MOVEMENT',
        entityId: 'mov-982',
        label: 'Transfer Manifest MOV-982',
        description: 'Unsigned dispatch slip intercepted at Awash checkpost.',
        relation: 'SUPPORTING_PROOF',
        relevanceScore: 90,
        pinned: true,
        timestamp: '2026-09-03',
      },
      {
        id: 'evi-104',
        caseId: 'inv-case-001',
        entityType: 'FARM',
        entityId: 'farm-2',
        label: 'Awash Pastoral Syndicate Feedlot',
        description: 'Destination farm where animal was accepted into secondary pen.',
        relation: 'TRANSIT_SITE',
        relevanceScore: 85,
        pinned: false,
        timestamp: '2026-09-03',
      },
      {
        id: 'evi-105',
        caseId: 'inv-case-001',
        entityType: 'DISEASE_EVENT',
        entityId: 'dis-001',
        label: 'FMD Serotype O Cluster',
        description: 'Underlying viral outbreak causing the original quarantine restriction.',
        relation: 'AFFECTED_CONTACT',
        relevanceScore: 99,
        pinned: true,
        timestamp: '2026-09-02',
      },
    ],
  },
  {
    id: 'inv-case-002',
    caseNumber: 'INV-2026-003',
    title: 'Systemic Sire Parentage Misattribution Inquiry',
    caseType: 'PEDIGREE_CONFLICT',
    severity: 'HIGH',
    priority: 'P2',
    leadInvestigatorName: 'Dr. Yonas Alemayehu',
    leadInvestigatorId: 'off-03',
    jurisdictionId: 'jur-oromia',
    jurisdictionName: 'Oromia Regional Livestock Agency',
    status: 'HEARING',
    openedAt: '2026-08-25',
    summary: 'Genomic audit revealed 11 progeny attributed to elite breeding bull Apex Dominator exclude parentage upon 50K SNP chip assay.',
    evidenceItems: [
      {
        id: 'evi-201',
        caseId: 'inv-case-002',
        entityType: 'LAB_ASSAY',
        entityId: 'assay-009',
        label: 'Lab Assay Report 50K-2026-88',
        description: 'Mendelian error rate >12% across 11 registered seedstock calves.',
        relation: 'SUPPORTING_PROOF',
        relevanceScore: 96,
        pinned: true,
        timestamp: '2026-08-24',
      },
    ],
  },
];

export const initialGovernmentPrograms: GovernmentProgram[] = [
  {
    id: 'prog-001',
    code: 'NAT-AI-2028',
    name: 'National Bovine Artificial Insemination Expansion Initiative',
    description: 'Strategic program to scale AI coverage in dairy cooperatives to reach 65% pregnancy conversion rate.',
    leadAgency: 'Ministry of Agriculture & National AI Center (NAIC)',
    category: 'AI_EXPANSION',
    baselinePct: 34.0,
    currentPct: 52.8,
    targetPct: 65.0,
    totalEligible: 85000,
    completedCount: 44880,
    progressPct: 60.5,
    status: 'ON_TRACK',
    regionsCovered: ['Oromia', 'Amhara', 'Sidama'],
    startDate: '2024-01-01',
    targetCompletionDate: '2028-12-31',
    targets: [
      { metricName: 'Straw Distribution', baseline: 50000, current: 82000, target: 120000, unit: 'Doses', deadline: '2027-12-31' },
      { metricName: 'Trained AI Technicians', baseline: 180, current: 340, target: 500, unit: 'Technicians', deadline: '2026-12-31' },
    ],
  },
  {
    id: 'prog-002',
    code: 'GEN-SNP-50K',
    name: 'National Seedstock Genomic Characterization Campaign',
    description: 'Compulsory 50K SNP genotyping of all certified breeding bulls and elite donor dams.',
    leadAgency: 'National Genetics Board & Apex Cooperative Consortium',
    category: 'GENOTYPING_INITIATIVE',
    baselinePct: 18.0,
    currentPct: 38.6,
    targetPct: 50.0,
    totalEligible: 28000,
    completedCount: 10808,
    progressPct: 64.3,
    status: 'ON_TRACK',
    regionsCovered: ['National Coverage'],
    startDate: '2025-06-01',
    targetCompletionDate: '2027-06-30',
    targets: [
      { metricName: 'Genotyped Bulls', baseline: 240, current: 520, target: 800, unit: 'Bulls', deadline: '2026-12-31' },
      { metricName: 'Parentage Verification Rate', baseline: 22, current: 44, target: 70, unit: '%', deadline: '2027-06-30' },
    ],
  },
  {
    id: 'prog-003',
    code: 'INDIG-CONSERV',
    name: 'Indigenous Boran & Fogera Breed Conservation Framework',
    description: 'Protection of strategic indigenous germplasm against genetic dilution and inbreeding depression.',
    leadAgency: 'Institute of Biodiversity Conservation (IBC)',
    category: 'BREED_CONSERVATION',
    baselinePct: 45.0,
    currentPct: 54.0,
    targetPct: 75.0,
    totalEligible: 12000,
    completedCount: 6480,
    progressPct: 42.0,
    status: 'BEHIND',
    regionsCovered: ['Oromia (Boran Zone)', 'Amhara (South Gondar)'],
    startDate: '2023-09-01',
    targetCompletionDate: '2028-09-01',
    targets: [
      { metricName: 'Pedigree Inbreeding Cap', baseline: 4.8, current: 4.4, target: 4.0, unit: '% F', deadline: '2028-09-01' },
      { metricName: 'Cryo-Bank Stored Embryos', baseline: 200, current: 480, target: 1200, unit: 'Embryos', deadline: '2027-12-31' },
    ],
  },
];

export const initialGovernmentOfficials: GovernmentOfficial[] = [
  {
    id: 'off-01',
    name: 'Dr. Dawit Hailemariam',
    title: 'Chief Veterinary Officer of the Federal Republic',
    officeName: 'Federal Ministry of Agriculture',
    jurisdictionId: 'jur-national',
    jurisdictionName: 'National Livestock Oversight Authority',
    email: 'cvo@moa-livestock.gov.et',
    phone: '+251 11 646 1234',
    role: 'FEDERAL_OBSERVER',
    activeAssignmentsCount: 4,
  },
  {
    id: 'off-02',
    name: 'Dr. Senait Bekele',
    title: 'Regional Veterinary Director',
    officeName: 'Oromia Regional Bureau',
    jurisdictionId: 'jur-oromia',
    jurisdictionName: 'Oromia Regional Livestock Agency',
    email: 's.bekele@oromia-livestock.gov.et',
    phone: '+251 11 552 4431',
    role: 'REGIONAL_DIRECTOR',
    activeAssignmentsCount: 6,
  },
  {
    id: 'off-03',
    name: 'Dr. Yonas Alemayehu',
    title: 'Senior Genetic Surveillance Specialist',
    officeName: 'National AI Center, Bishoftu',
    jurisdictionId: 'jur-bishoftu-district',
    jurisdictionName: 'Bishoftu Genetics Surveillance Sector',
    email: 'y.alemayehu@naic.gov.et',
    phone: '+251 11 433 9012',
    role: 'GENETICS_ANALYST',
    activeAssignmentsCount: 3,
  },
  {
    id: 'off-04',
    name: 'Insp. Solomon Getahun',
    title: 'Principal Biosecurity & Compliance Inspector',
    officeName: 'District Enforcement Division, Adama',
    jurisdictionId: 'jur-adama-district',
    jurisdictionName: 'Adama District Veterinary Office',
    email: 's.getahun@oromia-livestock.gov.et',
    phone: '+251 22 111 8840',
    role: 'COMPLIANCE_INSPECTOR',
    activeAssignmentsCount: 5,
  },
];

export const initialOfficialAssignments: OfficialAssignment[] = [
  {
    id: 'ass-001',
    officialId: 'off-04',
    officialName: 'Insp. Solomon Getahun',
    targetType: 'INVESTIGATION',
    targetId: 'inv-case-001',
    targetName: 'Illegal Movement Breach During FMD Quarantine Lock',
    assignedRole: 'Lead Investigator',
    effectiveFrom: '2026-09-03',
    active: true,
  },
  {
    id: 'ass-002',
    officialId: 'off-04',
    officialName: 'Insp. Solomon Getahun',
    targetType: 'INSPECTION',
    targetId: 'insp-01',
    targetName: 'Rift Valley Commercial Ranch Disease Spot Check',
    assignedRole: 'Field Auditor',
    effectiveFrom: '2026-09-08',
    active: true,
  },
  {
    id: 'ass-003',
    officialId: 'off-03',
    officialName: 'Dr. Yonas Alemayehu',
    targetType: 'PROGRAM',
    targetId: 'prog-002',
    targetName: 'National Seedstock Genomic Characterization Campaign',
    assignedRole: 'Genomic QC Director',
    effectiveFrom: '2025-06-01',
    active: true,
  },
];

export const initialStandardReports: StandardReport[] = [
  {
    id: 'rep-001',
    code: 'REP-NAT-POP-2026-M8',
    title: 'National Livestock Census & Population Vital Statistics',
    category: 'POPULATION',
    description: 'Monthly aggregation of cattle population, births, mortality, and demographic pyramid breakdowns.',
    frequency: 'MONTHLY',
    generatedAt: '2026-09-01',
    dataCutoff: '2026-08-31 23:59',
    version: 'v1.0 (Final Official)',
    coveragePct: 94.2,
    fileSize: '4.8 MB',
    format: 'PDF',
    downloadUrl: '#',
  },
  {
    id: 'rep-002',
    code: 'REP-EPI-SURV-2026-W36',
    title: 'Weekly Epidemiological Surveillance & Disease Alert Bulletin',
    category: 'HEALTH',
    description: 'Notifiable transboundary animal diseases, active quarantine perimeters, and vector warnings.',
    frequency: 'WEEKLY',
    generatedAt: '2026-09-07',
    dataCutoff: '2026-09-06 23:59',
    version: 'v1.2 (Revised with NVI Data)',
    coveragePct: 96.0,
    fileSize: '2.4 MB',
    format: 'PDF',
    downloadUrl: '#',
  },
  {
    id: 'rep-003',
    code: 'REP-GEN-PROG-2026-Q2',
    title: 'Quarterly Genetic Merit & Inbreeding Surveillance Report',
    category: 'GENETICS',
    description: 'Wright’s F trends, GEBV phenotypic divergence analysis, and rare indigenous line representation.',
    frequency: 'QUARTERLY',
    generatedAt: '2026-07-05',
    dataCutoff: '2026-06-30 23:59',
    version: 'v2.0 (Official Release)',
    coveragePct: 91.5,
    fileSize: '8.1 MB',
    format: 'PDF',
    downloadUrl: '#',
  },
  {
    id: 'rep-004',
    code: 'REP-FARM-COMPL-2026-M8',
    title: 'Commercial Farm Compliance & Movement Traceability Digest',
    category: 'COMPLIANCE',
    description: 'Cross-farm audit scorecards, open critical findings, and transit permit exceptions.',
    frequency: 'MONTHLY',
    generatedAt: '2026-09-02',
    dataCutoff: '2026-08-31 23:59',
    version: 'v1.0',
    coveragePct: 94.0,
    fileSize: '3.6 MB',
    format: 'XLSX',
    downloadUrl: '#',
  },
];

export const initialExportJobs: InstitutionalExportJob[] = [
  {
    id: 'exp-job-01',
    title: 'National Registered Herd Master Registry Export',
    requesterName: 'Dr. Dawit Hailemariam',
    dataset: 'Animal Registry with DGR, RFID, DOB, Breed, Herd Location',
    scopeJurisdiction: 'National Authority (All Regions)',
    format: 'CSV',
    status: 'READY',
    rowCount: 142850,
    requestedAt: '2026-09-07 14:20',
    completedAt: '2026-09-07 14:23',
    downloadUrl: '#',
  },
  {
    id: 'exp-job-02',
    title: 'Oromia Regional Movement Event Ledger (Past 90 Days)',
    requesterName: 'Insp. Solomon Getahun',
    dataset: 'Animal Movement Permits, Checkpoint Scans, Vehicle Manifests',
    scopeJurisdiction: 'Oromia Regional Livestock Agency',
    format: 'XLSX',
    status: 'READY',
    rowCount: 14200,
    requestedAt: '2026-09-08 04:10',
    completedAt: '2026-09-08 04:11',
    downloadUrl: '#',
  },
];

export const initialInstitutionalAlerts: InstitutionalAlert[] = [
  {
    id: 'alt-001',
    title: 'Foot and Mouth Disease (FMD Serotype O) Confirmed',
    description: 'Laboratory PCR confirmed 42 active clinical cases at Rift Valley Ranch. Mandatory quarantine active.',
    severity: 'CRITICAL',
    category: 'DISEASE',
    detectedAt: '2026-09-02 11:15',
    jurisdictionName: 'Adama District / Oromia',
    affectedCount: 280,
    triggerRule: 'Confirmed WOAH Listed Pathogen',
    status: 'INVESTIGATING',
    linkRoute: '/bovine/government/health',
    investigationCaseId: 'inv-case-001',
  },
  {
    id: 'alt-002',
    title: 'Movement Quarantine Breach Intercepted',
    description: 'Animal ETH-2024-88412 moved across district line without transit permit while farm was locked.',
    severity: 'CRITICAL',
    category: 'MOVEMENT',
    detectedAt: '2026-09-03 16:40',
    jurisdictionName: 'Adama Checkpoint',
    affectedCount: 18,
    triggerRule: 'Movement during active quarantine order',
    status: 'ACTIVE',
    linkRoute: '/bovine/government/movements',
    investigationCaseId: 'inv-case-001',
  },
  {
    id: 'alt-003',
    title: 'Anthrax Vaccination Coverage Gap in Bahir Dar Zuria',
    description: 'Compulsory vaccination coverage is currently 76.4% (target 90.0%). 38 farms reporting overdue stock.',
    severity: 'WARNING',
    category: 'REPORTING',
    detectedAt: '2026-09-05 09:00',
    jurisdictionName: 'Bahir Dar Zuria / Amhara',
    affectedCount: 5200,
    triggerRule: 'Vaccination coverage <80% in high-risk soil zone',
    status: 'ACKNOWLEDGED',
    linkRoute: '/bovine/government/health',
  },
  {
    id: 'alt-004',
    title: 'Mendelian Exclusion Discrepancy in Elite Sire Line',
    description: 'Genomic 50K beadchip assay excluded registered sire for 11 registered seedstock calves.',
    severity: 'WARNING',
    category: 'GENETICS',
    detectedAt: '2026-08-25 14:10',
    jurisdictionName: 'Bishoftu Sector / Oromia',
    affectedCount: 11,
    triggerRule: 'SNP Mendelian error rate >5%',
    status: 'INVESTIGATING',
    linkRoute: '/bovine/government/genetics',
    investigationCaseId: 'inv-case-002',
  },
];

export const initialInstitutionalTasks: InstitutionalTask[] = [
  {
    id: 'task-gov-01',
    title: 'Conduct Physical Follow-Up on FMD Containment Paddock',
    type: 'INSPECTION',
    priority: 'HIGH',
    dueDate: '2026-09-14',
    farmName: 'Rift Valley Commercial Ranch',
    jurisdictionName: 'Adama District',
    assignedOfficialName: 'Insp. Solomon Getahun',
    linkRoute: '/bovine/government/compliance',
    status: 'PENDING',
  },
  {
    id: 'task-gov-02',
    title: 'Review Farm Response for Disinfection Certificate CA-001',
    type: 'FINDING_REVIEW',
    priority: 'HIGH',
    dueDate: '2026-09-10',
    farmName: 'Rift Valley Commercial Ranch',
    jurisdictionName: 'Oromia Regional Agency',
    assignedOfficialName: 'Dr. Senait Bekele',
    linkRoute: '/bovine/government/compliance',
    status: 'IN_PROGRESS',
  },
  {
    id: 'task-gov-03',
    title: 'Investigate Intercepted Unsigned Movement Manifest MOV-985',
    type: 'MOVEMENT_EXCEPTION',
    priority: 'MEDIUM',
    dueDate: '2026-09-12',
    farmName: 'Tana Highlands Dairy Cooperative',
    jurisdictionName: 'Bahir Dar Zuria',
    assignedOfficialName: 'Ato Getachew Tadesse',
    linkRoute: '/bovine/government/movements',
    status: 'PENDING',
  },
  {
    id: 'task-gov-04',
    title: 'DNA Marker Conflict Hearing for Seedstock Breeder',
    type: 'PARENTAGE_CONFLICT',
    priority: 'HIGH',
    dueDate: '2026-09-15',
    farmName: 'Rift Valley Commercial Ranch',
    jurisdictionName: 'Bishoftu Genetics Sector',
    assignedOfficialName: 'Dr. Yonas Alemayehu',
    linkRoute: '/bovine/government/genetics',
    status: 'PENDING',
  },
];
