import {
  Breed,
  TraitDefinition,
  MeasurementMethod,
  ContemporaryGroup,
  PhenotypeObservation,
  PerformanceTest,
  PerformanceTestEnrollment,
  Laboratory,
  GeneticSample,
  GenotypingAssay,
  GenotypeQcResult,
  GeneticMarker,
  AnimalMarkerResult,
  GeneticCondition,
  AnimalGeneticConditionResult,
  GeneticEvaluationRun,
  GeneticTraitEstimate,
  AnimalGeneticMetric,
} from './bovine-types';

export const initialBreeds: Breed[] = [
  {
    id: 'breed-holstein',
    code: 'HO',
    name: 'Holstein-Friesian',
    origin: 'Netherlands / Northern Germany',
    description: 'World-leading dairy breed renowned for high milk yield and responsiveness to nutritional management.',
    active: true,
    populationCount: 48,
    isDairy: true,
    isBeef: false,
    primaryColor: 'Black & White',
    registryStandardUrl: 'https://www.holsteinusa.com',
  },
  {
    id: 'breed-angus',
    code: 'AN',
    name: 'Black Angus',
    origin: 'Aberdeenshire and Angus, Scotland',
    description: 'Premier beef breed known for high marbling, calving ease, maternal instinct, and dark carcass uniformity.',
    active: true,
    populationCount: 36,
    isDairy: false,
    isBeef: true,
    primaryColor: 'Solid Black',
    registryStandardUrl: 'https://www.angus.org',
  },
  {
    id: 'breed-jersey',
    code: 'JE',
    name: 'Jersey',
    origin: 'Channel Island of Jersey, UK',
    description: 'Small-frame dairy breed characterized by superior butterfat, protein density, and exceptional feed efficiency.',
    active: true,
    populationCount: 18,
    isDairy: true,
    isBeef: false,
    primaryColor: 'Fawn / Light Brown',
    registryStandardUrl: 'https://www.usjersey.com',
  },
  {
    id: 'breed-simmental',
    code: 'SM',
    name: 'Simmental / Fleckvieh',
    origin: 'Simme Valley, Switzerland',
    description: 'Dual-purpose breed characterized by rapid muscling, heavy milk capacity in maternal lines, and structural docility.',
    active: true,
    populationCount: 14,
    isDairy: true,
    isBeef: true,
    primaryColor: 'Red & White',
    registryStandardUrl: 'https://www.simmental.org',
  },
  {
    id: 'breed-wagyu',
    code: 'KB',
    name: 'Japanese Black Wagyu',
    origin: 'Kobe / Tajima, Japan',
    description: 'Exquisite beef breed famous for extraordinary intramuscular fat dispersion (marbling score 9+) and tender texture.',
    active: true,
    populationCount: 8,
    isDairy: false,
    isBeef: true,
    primaryColor: 'Solid Black',
  },
  {
    id: 'breed-charolais',
    code: 'CH',
    name: 'Charolais',
    origin: 'Charolles, France',
    description: 'Large-framed French terminal beef breed known for heavy weaning weights, lean yield, and rapid pasture gains.',
    active: true,
    populationCount: 6,
    isDairy: false,
    isBeef: true,
    primaryColor: 'Cream White',
  },
  {
    id: 'breed-hereford',
    code: 'HH',
    name: 'Hereford',
    origin: 'Herefordshire, England',
    description: 'Hardy grazing beef breed known for foraging ability, docility, white facial blaze, and crossbreeding vigor.',
    active: true,
    populationCount: 10,
    isDairy: false,
    isBeef: true,
    primaryColor: 'Red with White Face',
  },
  {
    id: 'breed-brahman',
    code: 'BR',
    name: 'American Brahman',
    origin: 'United States (Bos indicus descent)',
    description: 'Heat, humidity, and parasite tolerant Zebu breed providing high hybrid vigor when crossed with Bos taurus.',
    active: true,
    populationCount: 4,
    isDairy: false,
    isBeef: true,
    primaryColor: 'Light Grey to Dun',
  },
];

export const initialTraitDefinitions: TraitDefinition[] = [
  {
    id: 'trait-bwt',
    code: 'BWT',
    name: 'Birth Weight',
    category: 'GROWTH',
    unit: 'kg',
    direction: 'DECREASE',
    isSexLimited: false,
    active: true,
    description: 'Weight of calf taken within 24 hours of parturition. Moderate weight preferred to minimize dystocia.',
    stages: ['BIRTH'],
    heritability: 0.42,
    minValidValue: 18.0,
    maxValidValue: 62.0,
    phenotypeCount: 78,
    geneticEstimateCount: 64,
    selectionIndexUse: ['Calving Ease Direct Index', 'Balanced Beef Index'],
  },
  {
    id: 'trait-wwt',
    code: 'WWT',
    name: 'Weaning Weight (205-day)',
    category: 'GROWTH',
    unit: 'kg',
    direction: 'INCREASE',
    isSexLimited: false,
    active: true,
    description: 'Calf body weight standardized to 205 days of age with age-of-dam maternal adjustments applied.',
    stages: ['WEANING'],
    heritability: 0.38,
    minValidValue: 120.0,
    maxValidValue: 390.0,
    phenotypeCount: 65,
    geneticEstimateCount: 64,
    selectionIndexUse: ['Terminal Sire Index', 'Maternal Weaning Index'],
  },
  {
    id: 'trait-ywt',
    code: 'YWT',
    name: 'Yearling Weight (365-day)',
    category: 'GROWTH',
    unit: 'kg',
    direction: 'INCREASE',
    isSexLimited: false,
    active: true,
    description: 'Post-weaning growth benchmark standardized to 365 days of chronological life.',
    stages: ['YEARLING'],
    heritability: 0.45,
    minValidValue: 240.0,
    maxValidValue: 650.0,
    phenotypeCount: 52,
    geneticEstimateCount: 64,
    selectionIndexUse: ['Feedlot Growth Index', 'Carcass Value Index'],
  },
  {
    id: 'trait-adg',
    code: 'ADG',
    name: 'Average Daily Gain (On-Test)',
    category: 'EFFICIENCY',
    unit: 'kg/day',
    direction: 'INCREASE',
    isSexLimited: false,
    active: true,
    description: 'Rate of daily body mass accrual measured during standardized feedlot testing window.',
    stages: ['YEARLING', '18_MONTH'],
    heritability: 0.35,
    minValidValue: 0.6,
    maxValidValue: 3.2,
    phenotypeCount: 44,
    geneticEstimateCount: 48,
    selectionIndexUse: ['Feed Efficiency Index'],
  },
  {
    id: 'trait-fcr',
    code: 'FCR',
    name: 'Feed Conversion Ratio (RFI)',
    category: 'EFFICIENCY',
    unit: 'ratio',
    direction: 'DECREASE',
    isSexLimited: false,
    active: true,
    description: 'Kilograms of dry matter intake consumed per kilogram of liveweight gained. Lower represents superior efficiency.',
    stages: ['YEARLING'],
    heritability: 0.28,
    minValidValue: 3.8,
    maxValidValue: 9.5,
    phenotypeCount: 32,
    geneticEstimateCount: 38,
    selectionIndexUse: ['Feed Efficiency Index', 'Carbon Footprint Index'],
  },
  {
    id: 'trait-milk',
    code: 'MILK',
    name: '305-Day Mature Milk Yield',
    category: 'MILK',
    unit: 'kg',
    direction: 'INCREASE',
    isSexLimited: true,
    eligibleSex: 'FEMALE',
    active: true,
    description: 'Total standardized fluid milk production across standard 305-day lactation curve.',
    stages: ['LACTATION'],
    heritability: 0.30,
    minValidValue: 4500,
    maxValidValue: 18500,
    phenotypeCount: 42,
    geneticEstimateCount: 50,
    selectionIndexUse: ['Lifetime Merit (NM$)', 'TPI Dairy Index'],
  },
  {
    id: 'trait-fat',
    code: 'FAT_PCT',
    name: 'Milk Fat Percentage',
    category: 'MILK',
    unit: '%',
    direction: 'INCREASE',
    isSexLimited: true,
    eligibleSex: 'FEMALE',
    active: true,
    description: 'Concentration of lipid fat solids within tested milk samples.',
    stages: ['LACTATION'],
    heritability: 0.50,
    minValidValue: 2.8,
    maxValidValue: 6.8,
    phenotypeCount: 38,
    geneticEstimateCount: 50,
    selectionIndexUse: ['Cheese Yield Merit (CM$)', 'Total Solids Index'],
  },
  {
    id: 'trait-prot',
    code: 'PROT_PCT',
    name: 'Milk Protein Percentage',
    category: 'MILK',
    unit: '%',
    direction: 'INCREASE',
    isSexLimited: true,
    eligibleSex: 'FEMALE',
    active: true,
    description: 'Total crude protein fraction within bulk and individual test milkings.',
    stages: ['LACTATION'],
    heritability: 0.52,
    minValidValue: 2.4,
    maxValidValue: 4.6,
    phenotypeCount: 38,
    geneticEstimateCount: 50,
    selectionIndexUse: ['Cheese Yield Merit (CM$)', 'TPI Dairy Index'],
  },
  {
    id: 'trait-marb',
    code: 'MARB',
    name: 'Intramuscular Fat / Marbling Score',
    category: 'CARCASS',
    unit: 'score',
    direction: 'INCREASE',
    isSexLimited: false,
    active: true,
    description: 'Ultrasound or carcass ribeye cross-section intramuscular flecking score (USDA scale 1-10).',
    stages: ['YEARLING', 'HARVEST'],
    heritability: 0.48,
    minValidValue: 1.0,
    maxValidValue: 10.0,
    phenotypeCount: 36,
    geneticEstimateCount: 56,
    selectionIndexUse: ['Beef Value ($B)', 'Quality Grade Premium'],
  },
  {
    id: 'trait-rea',
    code: 'REA',
    name: 'Ribeye Muscle Area',
    category: 'CARCASS',
    unit: 'sq.cm',
    direction: 'INCREASE',
    isSexLimited: false,
    active: true,
    description: 'Cross-sectional area of Longissimus dorsi muscle between 12th and 13th ribs.',
    stages: ['YEARLING', 'HARVEST'],
    heritability: 0.40,
    minValidValue: 45.0,
    maxValidValue: 135.0,
    phenotypeCount: 36,
    geneticEstimateCount: 56,
    selectionIndexUse: ['Grid Value ($G)', 'Yield Grade Index'],
  },
  {
    id: 'trait-doc',
    code: 'DOC',
    name: 'Chute Docility Score',
    category: 'TEMPERAMENT',
    unit: 'score',
    direction: 'DECREASE',
    isSexLimited: false,
    active: true,
    description: 'Behavioral response during restraint in squeeze chute. 1=Docile, 2=Restless, 3=Nervous, 4=Flighty, 5=Aggressive.',
    stages: ['WEANING', 'YEARLING'],
    heritability: 0.37,
    minValidValue: 1.0,
    maxValidValue: 5.0,
    phenotypeCount: 58,
    geneticEstimateCount: 46,
    selectionIndexUse: ['Handling Safety Score', 'Maternal Temperament'],
  },
  {
    id: 'trait-dpr',
    code: 'DPR',
    name: 'Daughter Pregnancy Rate',
    category: 'REPRODUCTION',
    unit: '%',
    direction: 'INCREASE',
    isSexLimited: true,
    eligibleSex: 'FEMALE',
    active: true,
    description: 'Percentage of non-pregnant cows that become pregnant during each 21-day breeding opportunity cycle.',
    stages: ['MATURE'],
    heritability: 0.04,
    minValidValue: -5.0,
    maxValidValue: 8.0,
    phenotypeCount: 28,
    geneticEstimateCount: 42,
    selectionIndexUse: ['Fertility Index', 'Net Merit (NM$)'],
  },
  {
    id: 'trait-scs',
    code: 'SCS',
    name: 'Somatic Cell Score',
    category: 'HEALTH',
    unit: 'score',
    direction: 'DECREASE',
    isSexLimited: true,
    eligibleSex: 'FEMALE',
    active: true,
    description: 'Log base 2 transformed measure of somatic cell count in milk. Key indicator of mastitis resistance.',
    stages: ['LACTATION'],
    heritability: 0.12,
    minValidValue: 1.5,
    maxValidValue: 6.5,
    phenotypeCount: 34,
    geneticEstimateCount: 42,
    selectionIndexUse: ['Udder Health Index', 'Lifetime Merit'],
  },
];

export const initialMeasurementMethods: MeasurementMethod[] = [
  {
    id: 'method-dig-scale',
    code: 'DIG_SCALE_CAL',
    name: 'Calibrated Electronic Platform Scale',
    protocolVersion: 'v2.4 (ICAR-2024)',
    description: 'Digital 4-load cell livestock scale with dampening filter for motion artifacts. Calibrated monthly with certified 250kg test weights.',
    active: true,
    equipment: 'Tru-Test MP600 & XR5000 indicator',
    unit: 'kg',
    standardOperatingProcedure: 'SOP-WT-01: Zero scale before entry. Animal must be fully supported with four feet on plate. Record stabilized reading within 3 seconds.',
    observationCount: 142,
    metadataFields: {
      Precision: '±0.5 kg',
      Certification: 'Weights & Measures Class III',
      FilterMode: 'Live Animal Dynamic Filter 3',
    },
  },
  {
    id: 'method-us-carcass',
    code: 'US_CARCASS_SCAN',
    name: 'Real-Time Ultrasound Carcass Imaging',
    protocolVersion: 'v3.1 (UGC-Certified)',
    description: 'B-mode real-time linear array ultrasound probe positioned between 12th and 13th ribs with acoustic coupling vegetable oil.',
    active: true,
    equipment: 'Aloka 500V with 3.5 MHz 17cm linear probe',
    unit: 'sq.cm / %',
    standardOperatingProcedure: 'SOP-US-04: Apply mineral oil generous wipe. Place probe perpendicular to spine. Capture 4 freeze-frame clips; average computer-assisted tracing.',
    observationCount: 72,
    metadataFields: {
      TechnicianCertification: 'UGC Field & Lab Certified #2041',
      SoftwareImageAnalysis: 'BIA Carcass Analysis Suite v4.2',
    },
  },
  {
    id: 'method-dhi-meter',
    code: 'DHI_ELECTRONIC_FLOW',
    name: 'DHI Approved Electronic Free-Flow Milk Meter',
    protocolVersion: 'v1.8 (ICAR Certified)',
    description: 'In-line optical flow meter sampling individual quarter yields and composite aliquot for laboratory mid-infrared spectroscopy.',
    active: true,
    equipment: 'DeLaval MM27 VMS Flow Sensor',
    unit: 'kg / %',
    standardOperatingProcedure: 'SOP-MK-02: Auto-tare on teat cup attachment. Agitate composite vial for 10 seconds before preservative pill addition.',
    observationCount: 68,
    metadataFields: {
      AnalyticalLaboratory: 'Heartland DHI Central Testing',
      AnalyzerPlatform: 'Foss MilkoScan FT6000',
    },
  },
  {
    id: 'method-chute-doc',
    code: 'BIF_CHUTE_SCORE',
    name: 'BIF Standard Chute Behavior Scoring',
    protocolVersion: 'v4.0 (BIF Guidelines)',
    description: 'Visual behavioral observation during 10 seconds of unforced restraint in squeeze chute without headgate pinning.',
    active: true,
    unit: 'score 1-5',
    standardOperatingProcedure: 'SOP-DOC-01: Assessor stands 2m directly in front of headgate. Score 1=mild/calm to 5=violent shaking and vocalization.',
    observationCount: 58,
    metadataFields: {
      InterObserverConcordance: 'Kappa = 0.89',
      RestraintProtocol: 'Hydraulic squeeze 40psi gentle hold',
    },
  },
  {
    id: 'method-genomic-impute',
    code: 'GBLUP_IMPUTE',
    name: 'Single-Step Genomic Back-Prediction',
    protocolVersion: 'v5.2 (FImpute3 / BLUPF90)',
    description: 'High-density chip imputation combined with pedigree inverse relationship matrix A-1 to synthesize missing ancestral marker loci.',
    active: true,
    observationCount: 46,
    metadataFields: {
      ImputationAccuracy: 'r² > 0.985',
      ReferenceGenome: 'ARS-UCD1.2',
    },
  },
];

export const initialContemporaryGroups: ContemporaryGroup[] = [
  {
    id: 'cg-1',
    code: 'CG-2025-F1-SPRING-HEIFER',
    name: 'Spring 2025 Valley View Replacement Heifers',
    farmId: 'farm-1',
    farmName: 'Valley View Genetics Farm',
    herdId: 'herd-3',
    herdName: 'Young Stock Heifers',
    managementGroupId: 'group-1',
    sexGroup: 'FEMALE',
    birthSeason: 'Spring 2025 (Feb-Apr)',
    feedingGroup: 'Total Mixed Ration - Heifer High Forage 62% DM',
    managementSystem: 'Confinement Freestall with Compost Pack',
    startDate: '2025-02-01',
    endDate: '2025-08-30',
    status: 'CLOSED',
    animalCount: 14,
    phenotypeCount: 42,
    notes: 'Homogeneous nutritional plane. All animals vaccinated on standardized protocol.',
  },
  {
    id: 'cg-2',
    code: 'CG-2025-F2-FALL-BULLS',
    name: 'Fall 2025 High Desert Feedlot Bull Test Group',
    farmId: 'farm-2',
    farmName: 'High Desert Bull Station',
    herdId: 'herd-4',
    herdName: 'Bull Stud Sires',
    managementGroupId: 'group-4',
    sexGroup: 'MALE',
    birthSeason: 'Fall 2024 (Sep-Nov)',
    feedingGroup: 'Ad libitum 85% Concentrate Grow Ration',
    managementSystem: 'Drylot Feedlot with Calan Gate Intake Recording',
    startDate: '2025-09-01',
    endDate: '2026-01-15',
    status: 'CLOSED',
    animalCount: 12,
    phenotypeCount: 36,
    notes: 'Eligible for national BIF performance test index ranking.',
  },
  {
    id: 'cg-3',
    code: 'CG-2026-F1-MILK-L1',
    name: '2026 First Lactation High Merit Holstein Milkers',
    farmId: 'farm-1',
    farmName: 'Valley View Genetics Farm',
    herdId: 'herd-2',
    herdName: 'Production Milking Herd A',
    managementGroupId: 'group-2',
    sexGroup: 'FEMALE',
    birthSeason: 'Spring 2024',
    feedingGroup: 'High Production Dairy TMR (17.5% CP, 1.72 Mcal NEL/kg)',
    managementSystem: 'Free-stall with Rubber Mattresses & DeLaval Robotic VMS',
    startDate: '2026-01-01',
    status: 'ACTIVE',
    animalCount: 18,
    phenotypeCount: 54,
    notes: 'Active contemporary group receiving monthly DHI tester visits.',
  },
  {
    id: 'cg-4',
    code: 'CG-2026-F3-EMBRYO-CALVES',
    name: '2026 Pine Ridge Progeny Test Weanlings',
    farmId: 'farm-3',
    farmName: 'Pine Ridge Embryo Facility',
    herdId: 'herd-7',
    herdName: 'Progeny Test Calves',
    sexGroup: 'MIXED',
    birthSeason: 'Spring 2026 (Jan-Mar)',
    feedingGroup: 'Pasture Creep Feeder with Pelleted Starter (18% CP)',
    managementSystem: 'Rotational Grazing on Fescue/Clover Mixed Sward',
    startDate: '2026-01-15',
    status: 'ACTIVE',
    animalCount: 6,
    phenotypeCount: 12,
    warnings: ['Contemporary group has fewer than 10 animals (recommended minimum for genetic evaluation is 10).', 'Mixed sex group without separate sub-classification may require statistical sex-adjustment.'],
    notes: 'Recipient-born IVF calves undergoing maternal effect weaning evaluation.',
  },
];

export const initialPhenotypeObservations: PhenotypeObservation[] = [
  {
    id: 'pheno-1',
    animalId: 'anim-1',
    animalName: 'Altair Supernova ET',
    animalIdentifier: 'US-9941203',
    traitId: 'trait-bwt',
    traitCode: 'BWT',
    traitName: 'Birth Weight',
    unit: 'kg',
    observationDate: '2024-03-14',
    stage: 'BIRTH',
    rawValue: 39.5,
    adjustedValue: 39.5,
    adjustmentReason: 'First-calf heifer adjustment (+0.0 kg baseline recorded)',
    animalAgeDays: 0,
    measurementMethodId: 'method-dig-scale',
    measurementMethodCode: 'DIG_SCALE_CAL',
    contemporaryGroupId: 'cg-1',
    contemporaryGroupCode: 'CG-2025-F1-SPRING-HEIFER',
    farmId: 'farm-1',
    farmName: 'Valley View Genetics Farm',
    recordedBy: 'Dr. John Miller',
    qualityStatus: 'VALIDATED',
    qualityFlags: ['STANDARD_PROTOCOL', 'WITHIN_3_SD'],
    notes: 'Unassisted birth, vigorous calf standing within 35 minutes.',
  },
  {
    id: 'pheno-2',
    animalId: 'anim-1',
    animalName: 'Altair Supernova ET',
    animalIdentifier: 'US-9941203',
    traitId: 'trait-wwt',
    traitCode: 'WWT',
    traitName: 'Weaning Weight (205-day)',
    unit: 'kg',
    observationDate: '2024-10-05',
    stage: 'WEANING',
    rawValue: 238.0,
    adjustedValue: 246.5,
    adjustmentReason: 'Standardized to exactly 205 days from day 205 actual (Age-of-dam +8.5 kg)',
    animalAgeDays: 205,
    measurementMethodId: 'method-dig-scale',
    measurementMethodCode: 'DIG_SCALE_CAL',
    contemporaryGroupId: 'cg-1',
    contemporaryGroupCode: 'CG-2025-F1-SPRING-HEIFER',
    farmId: 'farm-1',
    farmName: 'Valley View Genetics Farm',
    recordedBy: 'Sarah Jenkins',
    qualityStatus: 'VALIDATED',
    qualityFlags: ['ADJUSTED_205_DAY', 'CG_VALIDATED'],
  },
  {
    id: 'pheno-3',
    animalId: 'anim-1',
    animalName: 'Altair Supernova ET',
    animalIdentifier: 'US-9941203',
    traitId: 'trait-ywt',
    traitCode: 'YWT',
    traitName: 'Yearling Weight (365-day)',
    unit: 'kg',
    observationDate: '2025-03-14',
    stage: 'YEARLING',
    rawValue: 422.0,
    adjustedValue: 422.0,
    adjustmentReason: 'Taken exactly on day 365',
    animalAgeDays: 365,
    measurementMethodId: 'method-dig-scale',
    measurementMethodCode: 'DIG_SCALE_CAL',
    contemporaryGroupId: 'cg-1',
    contemporaryGroupCode: 'CG-2025-F1-SPRING-HEIFER',
    farmId: 'farm-1',
    farmName: 'Valley View Genetics Farm',
    recordedBy: 'Dr. John Miller',
    qualityStatus: 'VALIDATED',
    qualityFlags: ['CERTIFIED_SCALE', 'OFFICIAL_AUDIT'],
  },
  {
    id: 'pheno-4',
    animalId: 'anim-1',
    animalName: 'Altair Supernova ET',
    animalIdentifier: 'US-9941203',
    traitId: 'trait-milk',
    traitCode: 'MILK',
    traitName: '305-Day Mature Milk Yield',
    unit: 'kg',
    observationDate: '2026-08-15',
    stage: 'LACTATION',
    rawValue: 12450.0,
    adjustedValue: 13120.0,
    adjustmentReason: 'Mature Equivalent (ME) 2-year-old adjustment factor 1.054',
    animalAgeDays: 885,
    measurementMethodId: 'method-dhi-meter',
    measurementMethodCode: 'DHI_ELECTRONIC_FLOW',
    contemporaryGroupId: 'cg-3',
    contemporaryGroupCode: 'CG-2026-F1-MILK-L1',
    farmId: 'farm-1',
    farmName: 'Valley View Genetics Farm',
    recordedBy: 'DHI Tester Mark Vance',
    qualityStatus: 'VALIDATED',
    qualityFlags: ['DHI_CERTIFIED', 'OFFICIAL_TEST'],
  },
  {
    id: 'pheno-5',
    animalId: 'anim-2',
    animalName: 'Ironwood Titan Red',
    animalIdentifier: 'US-7782341',
    traitId: 'trait-bwt',
    traitCode: 'BWT',
    traitName: 'Birth Weight',
    unit: 'kg',
    observationDate: '2023-08-22',
    stage: 'BIRTH',
    rawValue: 34.0,
    adjustedValue: 34.0,
    adjustmentReason: 'Direct scale weight recorded at 4 hours',
    animalAgeDays: 0,
    measurementMethodId: 'method-dig-scale',
    measurementMethodCode: 'DIG_SCALE_CAL',
    contemporaryGroupId: 'cg-2',
    contemporaryGroupCode: 'CG-2025-F2-FALL-BULLS',
    farmId: 'farm-2',
    farmName: 'High Desert Bull Station',
    recordedBy: 'Carlos Mendez',
    qualityStatus: 'VALIDATED',
    qualityFlags: ['CALVING_EASE_VERIFIED'],
  },
  {
    id: 'pheno-6',
    animalId: 'anim-2',
    animalName: 'Ironwood Titan Red',
    animalIdentifier: 'US-7782341',
    traitId: 'trait-ywt',
    traitCode: 'YWT',
    traitName: 'Yearling Weight (365-day)',
    unit: 'kg',
    observationDate: '2024-08-21',
    stage: 'YEARLING',
    rawValue: 568.0,
    adjustedValue: 568.0,
    animalAgeDays: 365,
    measurementMethodId: 'method-dig-scale',
    measurementMethodCode: 'DIG_SCALE_CAL',
    contemporaryGroupId: 'cg-2',
    contemporaryGroupCode: 'CG-2025-F2-FALL-BULLS',
    farmId: 'farm-2',
    farmName: 'High Desert Bull Station',
    recordedBy: 'Carlos Mendez',
    qualityStatus: 'VALIDATED',
    qualityFlags: ['TOP_5_PERCENTILE'],
  },
  {
    id: 'pheno-7',
    animalId: 'anim-2',
    animalName: 'Ironwood Titan Red',
    animalIdentifier: 'US-7782341',
    traitId: 'trait-adg',
    traitCode: 'ADG',
    traitName: 'Average Daily Gain (On-Test)',
    unit: 'kg/day',
    observationDate: '2024-11-15',
    stage: 'YEARLING',
    rawValue: 2.14,
    adjustedValue: 2.14,
    animalAgeDays: 450,
    measurementMethodId: 'method-dig-scale',
    measurementMethodCode: 'DIG_SCALE_CAL',
    contemporaryGroupId: 'cg-2',
    contemporaryGroupCode: 'CG-2025-F2-FALL-BULLS',
    farmId: 'farm-2',
    farmName: 'High Desert Bull Station',
    recordedBy: 'Carlos Mendez',
    qualityStatus: 'VALIDATED',
    qualityFlags: ['ON_TEST_112_DAY'],
  },
  {
    id: 'pheno-8',
    animalId: 'anim-2',
    animalName: 'Ironwood Titan Red',
    animalIdentifier: 'US-7782341',
    traitId: 'trait-marb',
    traitCode: 'MARB',
    traitName: 'Intramuscular Fat / Marbling Score',
    unit: 'score',
    observationDate: '2024-08-25',
    stage: 'YEARLING',
    rawValue: 7.8,
    adjustedValue: 7.9,
    adjustmentReason: 'Age-standardized to 365 days',
    animalAgeDays: 369,
    measurementMethodId: 'method-us-carcass',
    measurementMethodCode: 'US_CARCASS_SCAN',
    contemporaryGroupId: 'cg-2',
    contemporaryGroupCode: 'CG-2025-F2-FALL-BULLS',
    farmId: 'farm-2',
    farmName: 'High Desert Bull Station',
    recordedBy: 'Dr. John Miller',
    qualityStatus: 'VALIDATED',
    qualityFlags: ['UGC_CERTIFIED_SCAN'],
  },
  {
    id: 'pheno-9',
    animalId: 'anim-3',
    animalName: 'Meadow Jewel 420',
    animalIdentifier: 'US-6619022',
    traitId: 'trait-fat',
    traitCode: 'FAT_PCT',
    traitName: 'Milk Fat Percentage',
    unit: '%',
    observationDate: '2026-06-12',
    stage: 'LACTATION',
    rawValue: 5.42,
    adjustedValue: 5.42,
    animalAgeDays: 755,
    measurementMethodId: 'method-dhi-meter',
    measurementMethodCode: 'DHI_ELECTRONIC_FLOW',
    farmId: 'farm-1',
    farmName: 'Valley View Genetics Farm',
    recordedBy: 'DHI Tester Mark Vance',
    qualityStatus: 'VALIDATED',
    qualityFlags: ['HIGH_BUTTERFAT'],
  },
  {
    id: 'pheno-10',
    animalId: 'anim-4',
    animalName: 'Onyx Black Diamond',
    animalIdentifier: 'US-8821940',
    traitId: 'trait-doc',
    traitCode: 'DOC',
    traitName: 'Chute Docility Score',
    unit: 'score',
    observationDate: '2026-01-20',
    stage: 'WEANING',
    rawValue: 1.0,
    animalAgeDays: 210,
    measurementMethodId: 'method-chute-doc',
    measurementMethodCode: 'BIF_CHUTE_SCORE',
    farmId: 'farm-2',
    farmName: 'High Desert Bull Station',
    recordedBy: 'Carlos Mendez',
    qualityStatus: 'VALIDATED',
    qualityFlags: ['DOCILE_SCORE_1'],
  },
  {
    id: 'pheno-11',
    animalId: 'anim-5',
    animalName: 'Cloverhill Princess 108',
    animalIdentifier: 'US-5541098',
    traitId: 'trait-bwt',
    traitCode: 'BWT',
    traitName: 'Birth Weight',
    unit: 'kg',
    observationDate: '2024-02-10',
    stage: 'BIRTH',
    rawValue: 58.2,
    adjustedValue: 58.2,
    animalAgeDays: 0,
    measurementMethodId: 'method-dig-scale',
    measurementMethodCode: 'DIG_SCALE_CAL',
    farmId: 'farm-3',
    farmName: 'Pine Ridge Embryo Facility',
    recordedBy: 'Sarah Jenkins',
    qualityStatus: 'SUSPECT',
    qualityFlags: ['STATISTICAL_OUTLIER_HIGH', 'POSSIBLE_SCALE_TARE_ERROR'],
    notes: 'Recorded birth weight is +3.8 SD above contemporary mean. Recommended re-inspection against tape metric.',
  },
];

export const initialPerformanceTests: PerformanceTest[] = [
  {
    id: 'pt-1',
    code: 'BIF-TEST-2025-FALL',
    name: 'National 112-Day Beef Sire Intake & Efficiency Test',
    testStation: 'High Desert Test Station Barn 4',
    location: 'Boise Foothills, ID',
    startDate: '2025-09-01',
    endDate: '2026-01-15',
    status: 'COMPLETED',
    contemporaryGroupId: 'cg-2',
    contemporaryGroupCode: 'CG-2025-F2-FALL-BULLS',
    enrolledCount: 12,
    completedCount: 12,
    protocolSections: [
      {
        title: 'Acclimatization Period',
        content: '21-day warm-up on step-up concentrate ration to stabilize rumen microbiota before official day-0 weight.',
      },
      {
        title: 'Weighing Schedule',
        content: 'Weights taken on two consecutive days at start (days -1 and 0), midpoint day 56, and closeout days 111 and 112.',
      },
      {
        title: 'Feed Intake Measurement',
        content: 'Individual RFID Calan Broadbent electronic feeding gates measuring daily intake to the nearest 10 grams.',
      },
      {
        title: 'Ultrasound Carcass Closeout',
        content: 'Scan for ribeye area, 12th rib fat thickness, and intramuscular fat by certified UGC technician.',
      },
    ],
  },
  {
    id: 'pt-2',
    code: 'HEIFER-DEV-2026-A',
    name: 'Apex Spring Replacement Heifer RFI Cohort',
    testStation: 'Valley View Research Barn 2',
    location: 'Vergennes, VT',
    startDate: '2026-03-01',
    endDate: '2026-07-15',
    status: 'IN_PROGRESS',
    contemporaryGroupId: 'cg-1',
    contemporaryGroupCode: 'CG-2025-F1-SPRING-HEIFER',
    enrolledCount: 14,
    completedCount: 0,
    protocolSections: [
      {
        title: 'Growth Target',
        content: 'Average daily gain managed between 0.75 - 0.85 kg/day to avoid mammary adipose deposition.',
      },
      {
        title: 'Breeding Soundness Protocol',
        content: 'Reproductive tract scoring (RTS) and pelvic area measurements taken at 13 months of chronological age.',
      },
    ],
  },
];

export const initialPerformanceTestEnrollments: PerformanceTestEnrollment[] = [
  {
    id: 'pte-1',
    performanceTestId: 'pt-1',
    testName: 'National 112-Day Beef Sire Intake & Efficiency Test',
    animalId: 'anim-2',
    animalName: 'Ironwood Titan Red',
    animalIdentifier: 'US-7782341',
    entryDate: '2025-09-01',
    exitDate: '2026-01-15',
    entryWeightKg: 420.0,
    exitWeightKg: 660.0,
    averageDailyGainKg: 2.14,
    feedConversionRatio: 5.12,
    rank: 1,
    status: 'COMPLETED',
    contemporaryGroupId: 'cg-2',
    notes: 'Class Champion for on-test Average Daily Gain and superior residual feed intake.',
  },
  {
    id: 'pte-2',
    performanceTestId: 'pt-1',
    testName: 'National 112-Day Beef Sire Intake & Efficiency Test',
    animalId: 'anim-4',
    animalName: 'Onyx Black Diamond',
    animalIdentifier: 'US-8821940',
    entryDate: '2025-09-01',
    exitDate: '2026-01-15',
    entryWeightKg: 395.0,
    exitWeightKg: 618.0,
    averageDailyGainKg: 1.99,
    feedConversionRatio: 5.48,
    rank: 3,
    status: 'COMPLETED',
    contemporaryGroupId: 'cg-2',
    notes: 'Ranked 3rd of 12 test sires with outstanding ribeye scan (98.4 sq.cm).',
  },
  {
    id: 'pte-3',
    performanceTestId: 'pt-2',
    testName: 'Apex Spring Replacement Heifer RFI Cohort',
    animalId: 'anim-1',
    animalName: 'Altair Supernova ET',
    animalIdentifier: 'US-9941203',
    entryDate: '2026-03-01',
    entryWeightKg: 418.0,
    status: 'ACTIVE',
    contemporaryGroupId: 'cg-1',
    notes: 'Midpoint weigh-in scheduled for April 25.',
  },
];

export const initialLaboratories: Laboratory[] = [
  {
    id: 'lab-neogen',
    code: 'NEO-GENESEEK',
    name: 'Neogen GeneSeek Genomics Center',
    country: 'United States',
    address: '4131 N 48th St, Lincoln, NE 68504',
    accreditation: 'ICAR Accredited Genotyping Laboratory / ISO 17025',
    email: 'geneseekinfo@neogen.com',
    phone: '+1 (402) 435-0665',
    active: true,
    sampleVolume: 840,
    assayVolume: 812,
    averageTurnaroundDays: 8.5,
    organizationName: 'Neogen Corporation',
  },
  {
    id: 'lab-zoetis',
    code: 'ZOETIS-CLARIFIDE',
    name: 'Zoetis Genetics Central Facility',
    country: 'United States',
    address: '333 Portage St, Kalamazoo, MI 49007',
    accreditation: 'USDA-AIPL Approved / ISO 9001:2015',
    email: 'clarifide.support@zoetis.com',
    phone: '+1 (888) 963-8471',
    active: true,
    sampleVolume: 520,
    assayVolume: 498,
    averageTurnaroundDays: 9.2,
    organizationName: 'Zoetis Inc.',
  },
  {
    id: 'lab-weatherbys',
    code: 'WEATHERBYS-DNA',
    name: 'Weatherbys Scientific Laboratory',
    country: 'Ireland',
    address: 'Johnstown, Naas, Co. Kildare, Ireland',
    accreditation: 'ISAG Institutional Member / ICAR Gold Standard',
    email: 'dna@weatherbys.ie',
    phone: '+353 45 879979',
    active: true,
    sampleVolume: 310,
    assayVolume: 304,
    averageTurnaroundDays: 11.0,
    organizationName: 'Weatherbys Ltd',
  },
  {
    id: 'lab-internal',
    code: 'APEX-BIO-LAB',
    name: 'Apex Bovine Molecular Diagnostics Lab',
    country: 'United States',
    address: 'Valley View Campus Building C, Vergennes, VT',
    accreditation: 'In-House Quality Standard ISO 15189 Tier 2',
    email: 'genetics@apexbovine.com',
    phone: '+1 (802) 555-0199',
    active: true,
    sampleVolume: 160,
    assayVolume: 154,
    averageTurnaroundDays: 3.5,
    organizationName: 'Apex Bovine Holdings',
  },
];

export const initialGeneticSamples: GeneticSample[] = [
  {
    id: 'sample-1',
    sampleCode: 'SMP-2024-9941',
    animalId: 'anim-1',
    animalName: 'Altair Supernova ET',
    animalIdentifier: 'US-9941203',
    sampleType: 'TISSUE_TSU',
    collectedDate: '2024-03-16',
    collectedBy: 'Dr. John Miller',
    destinationLabId: 'lab-neogen',
    destinationLabName: 'Neogen GeneSeek Genomics Center',
    receivedDate: '2024-03-20',
    status: 'COMPLETED',
    barcode: 'TSU8492019482',
    assayCount: 1,
    chainOfCustody: [
      {
        timestamp: '2024-03-16 09:30',
        location: 'Valley View Genetics - Maternity Pen 1',
        handledBy: 'Dr. John Miller',
        action: 'Collected Allflex TSU ear notch during initial tagging',
        notes: 'Buffer fluid clear, green pin indicator seated.',
      },
      {
        timestamp: '2024-03-18 14:00',
        location: 'Valley View Office Dispatch',
        handledBy: 'Sarah Jenkins',
        action: 'Shipped via FedEx Priority Overnight tracking #79428194012',
        notes: 'Insulated cooler pouch with cold gel pack.',
      },
      {
        timestamp: '2024-03-20 10:15',
        location: 'Neogen GeneSeek Sample Intake Lincoln, NE',
        handledBy: 'Intake Specialist Tyler B.',
        action: 'Received intact, 2D barcode scanned into LIMS',
        notes: 'Sample integrity confirmed satisfactory.',
      },
      {
        timestamp: '2024-03-22 08:30',
        location: 'Genotyping Automation Suite',
        handledBy: 'Lab Analyst M. Zhao',
        action: 'DNA extraction (magnetic bead) & quantification A260/280=1.88',
      },
      {
        timestamp: '2024-03-26 16:00',
        location: 'Informatics Analysis Core',
        handledBy: 'Bioinformatics Lead Dr. S. Patel',
        action: 'Assay processing completed, QC passed, data published',
      },
    ],
  },
  {
    id: 'sample-2',
    sampleCode: 'SMP-2023-7782',
    animalId: 'anim-2',
    animalName: 'Ironwood Titan Red',
    animalIdentifier: 'US-7782341',
    sampleType: 'SEMEN',
    collectedDate: '2024-02-10',
    collectedBy: 'Carlos Mendez',
    destinationLabId: 'lab-zoetis',
    destinationLabName: 'Zoetis Genetics Central Facility',
    receivedDate: '2024-02-14',
    status: 'COMPLETED',
    barcode: 'SMN9941029481',
    assayCount: 1,
    chainOfCustody: [
      {
        timestamp: '2024-02-10 08:00',
        location: 'High Desert AI Collection Chute',
        handledBy: 'Carlos Mendez',
        action: 'Collected 0.5ml semen straw from scheduled sire collection batch',
      },
      {
        timestamp: '2024-02-12 11:30',
        location: 'Boise FedEx Regional Depot',
        handledBy: 'Carlos Mendez',
        action: 'Shipped in liquid nitrogen dry shipper vessel',
      },
      {
        timestamp: '2024-02-14 09:00',
        location: 'Zoetis Genetics Kalamazoo MI',
        handledBy: 'Lab Scientist Dave R.',
        action: 'Received sample in frozen state, logged in LIMS',
      },
      {
        timestamp: '2024-02-19 14:00',
        location: 'Illumina HiScan Array Lab',
        handledBy: 'Senior Technologist Alice G.',
        action: 'Genotyping assay BovineSNP50 completed successfully',
      },
    ],
  },
  {
    id: 'sample-3',
    sampleCode: 'SMP-2026-6619',
    animalId: 'anim-3',
    animalName: 'Meadow Jewel 420',
    animalIdentifier: 'US-6619022',
    sampleType: 'BLOOD_EDTA',
    collectedDate: '2026-08-20',
    collectedBy: 'Dr. John Miller',
    destinationLabId: 'lab-neogen',
    destinationLabName: 'Neogen GeneSeek Genomics Center',
    receivedDate: '2026-08-24',
    status: 'PROCESSING',
    barcode: 'BLD4421098231',
    assayCount: 0,
    chainOfCustody: [
      {
        timestamp: '2026-08-20 10:45',
        location: 'Valley View Veterinary Chute',
        handledBy: 'Dr. John Miller',
        action: 'Venipuncture coccygeal vein into 10mL purple-top K2-EDTA tube',
      },
      {
        timestamp: '2026-08-21 16:00',
        location: 'Valley View Farm Office',
        handledBy: 'Sarah Jenkins',
        action: 'Dispatched via UPS Express Next Day',
      },
      {
        timestamp: '2026-08-24 11:00',
        location: 'Neogen GeneSeek Receiving Dock',
        handledBy: 'Clerk Jennifer S.',
        action: 'Package received, barcode verified, queued for lysis',
      },
    ],
  },
  {
    id: 'sample-4',
    sampleCode: 'SMP-2026-8821',
    animalId: 'anim-4',
    animalName: 'Onyx Black Diamond',
    animalIdentifier: 'US-8821940',
    sampleType: 'HAIR_FOLLICLE',
    collectedDate: '2026-08-30',
    collectedBy: 'Carlos Mendez',
    destinationLabId: 'lab-weatherbys',
    destinationLabName: 'Weatherbys Scientific Laboratory',
    status: 'SHIPPED',
    barcode: 'HAR1094827104',
    assayCount: 0,
    chainOfCustody: [
      {
        timestamp: '2026-08-30 14:15',
        location: 'High Desert Pasture 2 Handling Chute',
        handledBy: 'Carlos Mendez',
        action: 'Pulled 40 tail-switch hairs with intact visible follicles into collection card',
      },
      {
        timestamp: '2026-09-02 09:30',
        location: 'DHL International Dispatch',
        handledBy: 'Carlos Mendez',
        action: 'Shipped international air freight to Ireland with export customs manifest',
      },
    ],
  },
  {
    id: 'sample-5',
    sampleCode: 'SMP-2026-0012',
    animalId: 'anim-5',
    animalName: 'Cloverhill Princess 108',
    animalIdentifier: 'US-5541098',
    sampleType: 'TISSUE_TSU',
    collectedDate: '2026-07-10',
    collectedBy: 'Sarah Jenkins',
    destinationLabId: 'lab-neogen',
    destinationLabName: 'Neogen GeneSeek Genomics Center',
    receivedDate: '2026-07-14',
    status: 'REJECTED',
    barcode: 'TSU3391048201',
    notes: 'Insufficient tissue biopsy volume. Tube had missing buffer fluid upon arrival.',
    assayCount: 0,
    chainOfCustody: [
      {
        timestamp: '2026-07-10 11:00',
        location: 'Pine Ridge Nursery',
        handledBy: 'Sarah Jenkins',
        action: 'Ear notch collected with damaged applicator punch',
      },
      {
        timestamp: '2026-07-14 13:00',
        location: 'Neogen GeneSeek Receiving',
        handledBy: 'Lab QA Inspector David K.',
        action: 'Sample rejected at intake: dry punch, DNA yield estimated < 15ng. Request re-sample.',
      },
    ],
  },
];

export const initialGenotypingAssays: GenotypingAssay[] = [
  {
    id: 'assay-1',
    code: 'GGP-100K-9941',
    name: 'GGP Bovine 100K Genomic Profiler',
    laboratoryId: 'lab-neogen',
    laboratoryName: 'Neogen GeneSeek Genomics Center',
    density: '100K',
    markerCount: 104250,
    callRate: 99.74,
    heterozygosityRate: 34.2,
    sexConcordance: 'PASS',
    mendelianConflicts: 0,
    assemblyVersion: 'ARS-UCD1.2 (Bos taurus)',
    sampleId: 'sample-1',
    sampleCode: 'SMP-2024-9941',
    animalId: 'anim-1',
    animalName: 'Altair Supernova ET',
    animalIdentifier: 'US-9941203',
    assayName: 'GGP Bovine 100K Genomic Profiler',
    labId: 'lab-neogen',
    labName: 'Neogen GeneSeek Genomics Center',
    platform: 'ILLUMINA_BEADCHIP',
    chipName: 'GGP Bovine 100K v3.0',
    chipVersion: 'v3.0',
    genomeAssembly: 'ARS-UCD1.2',
    totalMarkers: 104250,
    calledMarkers: 103980,
    callRatePct: 99.74,
    heterozygosityPct: 34.2,
    performedDate: '2024-03-25',
    qcStatus: 'PASSED',
    softwareVersion: 'GenomeStudio v2.0.5 / GenCall 0.15',
    rawDataAssetUrl: '/assets/genomics/SMP-2024-9941_idat.zip',
    processedDataAssetUrl: '/assets/genomics/SMP-2024-9941_finalreport.txt',
    qcNotes: 'Exceptional signal-to-noise ratio. Zero mendelian violations with verified sire Altair Benchmark.',
    parentageSupported: true,
  },
  {
    id: 'assay-2',
    code: 'HD-777K-7782',
    name: 'Clarifide Plus BovineHD 770K High-Density',
    laboratoryId: 'lab-zoetis',
    laboratoryName: 'Zoetis Genetics Central Facility',
    density: '777K',
    markerCount: 777962,
    callRate: 99.60,
    heterozygosityRate: 32.8,
    sexConcordance: 'PASS',
    mendelianConflicts: 0,
    assemblyVersion: 'ARS-UCD1.2 (Bos taurus)',
    sampleId: 'sample-2',
    sampleCode: 'SMP-2023-7782',
    animalId: 'anim-2',
    animalName: 'Ironwood Titan Red',
    animalIdentifier: 'US-7782341',
    assayName: 'Clarifide Plus BovineHD 770K High-Density',
    labId: 'lab-zoetis',
    labName: 'Zoetis Genetics Central Facility',
    platform: 'ILLUMINA_BEADCHIP',
    chipName: 'Illumina BovineHD 777K',
    chipVersion: 'v2.1',
    genomeAssembly: 'ARS-UCD1.2',
    totalMarkers: 777962,
    calledMarkers: 774850,
    callRatePct: 99.60,
    heterozygosityPct: 32.8,
    performedDate: '2024-02-18',
    qcStatus: 'PASSED',
    softwareVersion: 'Clarifide Pipeline v4.4',
    rawDataAssetUrl: '/assets/genomics/SMP-2023-7782_idat.zip',
    processedDataAssetUrl: '/assets/genomics/SMP-2023-7782_calls.vcf.gz',
    qcNotes: 'High density research grade scan for foundational AI sire.',
    parentageSupported: true,
  },
  {
    id: 'assay-3',
    code: 'GGP-50K-1082',
    name: 'GGP Bovine 50K BeadChip',
    laboratoryId: 'lab-neogen',
    laboratoryName: 'Neogen GeneSeek Genomics Center',
    density: '50K',
    markerCount: 54609,
    callRate: 97.27,
    heterozygosityRate: 41.5,
    sexConcordance: 'PASS',
    mendelianConflicts: 2,
    assemblyVersion: 'ARS-UCD1.2 (Bos taurus)',
    sampleId: 'sample-6-prev',
    sampleCode: 'SMP-2024-1082',
    animalId: 'anim-6',
    animalName: 'Apex Thunderstruck ET',
    animalIdentifier: 'US-3301984',
    assayName: 'GGP Bovine 50K BeadChip',
    labId: 'lab-neogen',
    labName: 'Neogen GeneSeek Genomics Center',
    platform: 'ILLUMINA_BEADCHIP',
    chipName: 'GGP Bovine 50K v2',
    chipVersion: 'v2.0',
    genomeAssembly: 'ARS-UCD1.2',
    totalMarkers: 54609,
    calledMarkers: 53120,
    callRatePct: 97.27,
    heterozygosityPct: 41.5,
    performedDate: '2024-05-12',
    qcStatus: 'WARNING',
    softwareVersion: 'GenomeStudio v2.0.5',
    qcNotes: 'Call rate 97.27% is below standard 98.5% threshold. Elevated heterozygosity (41.5%) suggests minor DNA cross-contamination during lysis.',
    parentageSupported: false,
  },
  {
    id: 'assay-4',
    code: 'AXIOM-64K-4401',
    name: 'Affymetrix Axiom Bovine Genotyping v1',
    laboratoryId: 'lab-internal',
    laboratoryName: 'Apex Bovine Molecular Diagnostics Lab',
    density: '64K',
    markerCount: 64120,
    callRate: 84.37,
    heterozygosityRate: 22.1,
    sexConcordance: 'FAIL',
    mendelianConflicts: 8,
    assemblyVersion: 'ARS-UCD1.2 (Bos taurus)',
    sampleId: 'sample-7-fail',
    sampleCode: 'SMP-2025-4401',
    animalId: 'anim-7',
    animalName: 'Morning Mist Belle',
    animalIdentifier: 'US-2201948',
    assayName: 'Affymetrix Axiom Bovine Genotyping v1',
    labId: 'lab-internal',
    labName: 'Apex Bovine Molecular Diagnostics Lab',
    platform: 'AFFYMETRIX_AXIOM',
    chipName: 'Axiom Bovine 64K',
    chipVersion: 'v1.0',
    genomeAssembly: 'ARS-UCD1.2',
    totalMarkers: 64120,
    calledMarkers: 54100,
    callRatePct: 84.37,
    heterozygosityPct: 22.1,
    performedDate: '2025-11-04',
    qcStatus: 'FAILED',
    softwareVersion: 'Axiom Analysis Suite v5.1',
    qcNotes: 'Major hybridization failure on BeadArray lane 4. Dish dish quality metric < 0.82. Sample flagged for re-extraction.',
    parentageSupported: false,
  },
];

export const initialGenotypeQcResults: GenotypeQcResult[] = [
  {
    id: 'qc-1',
    assayId: 'assay-1',
    checkCode: 'CALL_RATE',
    checkName: 'Sample SNP Call Rate Percentage',
    actualValue: '99.74%',
    threshold: '>= 98.50%',
    status: 'PASSED',
    message: 'Exceeds gold-standard minimum call rate threshold.',
  },
  {
    id: 'qc-2',
    assayId: 'assay-1',
    checkCode: 'HETEROZYGOSITY',
    checkName: 'Autosomal Heterozygosity Rate',
    actualValue: '34.2%',
    threshold: '28.0% - 38.0%',
    status: 'PASSED',
    message: 'Heterozygosity within expected population bounds for purebred Holstein.',
  },
  {
    id: 'qc-3',
    assayId: 'assay-1',
    checkCode: 'SEX_CONCORDANCE',
    checkName: 'Genotypic Sex Concordance vs Recorded Sex',
    actualValue: 'XX (Female)',
    threshold: 'Matches Recorded FEMALE',
    status: 'PASSED',
    message: 'X-chromosome heterozygosity confirmed 2 copies, no Y-specific markers called.',
  },
  {
    id: 'qc-4',
    assayId: 'assay-1',
    checkCode: 'PARENTAGE_CONCORDANCE',
    checkName: 'Pedigree Parentage Mendelian Exclusion',
    actualValue: '0 opposing homozygous loci',
    threshold: '<= 1% of parentage SNPs',
    status: 'PASSED',
    message: 'Pedigree verified with 100% concordance against reported sire & dam.',
  },
  {
    id: 'qc-5',
    assayId: 'assay-3',
    checkCode: 'CALL_RATE',
    checkName: 'Sample SNP Call Rate Percentage',
    actualValue: '97.27%',
    threshold: '>= 98.50%',
    status: 'WARNING',
    message: 'Below 98.5% minimum bar. Acceptable for low-pass screening only, invalid for official registration certificate.',
  },
  {
    id: 'qc-6',
    assayId: 'assay-3',
    checkCode: 'HETEROZYGOSITY',
    checkName: 'Autosomal Heterozygosity Rate',
    actualValue: '41.5%',
    threshold: '28.0% - 38.0%',
    status: 'WARNING',
    message: 'Elevated heterozygosity flag. Possible cross-contamination or mixed DNA.',
  },
  {
    id: 'qc-7',
    assayId: 'assay-4',
    checkCode: 'CALL_RATE',
    checkName: 'Sample SNP Call Rate Percentage',
    actualValue: '84.37%',
    threshold: '>= 98.50%',
    status: 'FAILED',
    message: 'Fatal call rate failure. 15.6% missing loci invalidates evaluation imputation.',
  },
];

export const initialGeneticMarkers: GeneticMarker[] = [
  {
    id: 'marker-dgat1',
    code: 'BTA14_DGAT1_K232A',
    name: 'Diacylglycerol O-Acyltransferase 1 K232A',
    chromosome: '14',
    positionBp: 1802266,
    refAllele: 'A',
    altAllele: 'K',
    genomeAssembly: 'ARS-UCD1.2',
    geneSymbol: 'DGAT1',
    effectDescription: 'K allele strongly increases milk fat percentage and fat yield while reducing total fluid volume.',
    resultCount: 84,
    active: true,
  },
  {
    id: 'marker-abcg2',
    code: 'BTA06_ABCG2_Y581S',
    name: 'ATP-Binding Cassette Transporter G2 Y581S',
    chromosome: '6',
    positionBp: 38027010,
    refAllele: 'A',
    altAllele: 'C',
    genomeAssembly: 'ARS-UCD1.2',
    geneSymbol: 'ABCG2',
    effectDescription: 'Significant quantitative trait nucleotide for milk protein concentration and somatic cell count.',
    resultCount: 76,
    active: true,
  },
  {
    id: 'marker-tg',
    code: 'BTA14_TG_5UTR',
    name: 'Thyroglobulin 5-prime UTR C>T Polymorphism',
    chromosome: '14',
    positionBp: 9294200,
    refAllele: 'C',
    altAllele: 'T',
    genomeAssembly: 'ARS-UCD1.2',
    geneSymbol: 'TG',
    effectDescription: 'TT genotype associated with significantly elevated intramuscular fat (marbling score) in beef cattle.',
    resultCount: 92,
    active: true,
  },
  {
    id: 'marker-myf5',
    code: 'BTA05_MYF5_EX1',
    name: 'Myogenic Factor 5 Exon 1 Insertion',
    chromosome: '5',
    positionBp: 111840220,
    refAllele: 'G',
    altAllele: 'A',
    genomeAssembly: 'ARS-UCD1.2',
    geneSymbol: 'MYF5',
    effectDescription: 'Regulates skeletal myogenesis, ribeye area dimensions, and carcass muscularity.',
    resultCount: 68,
    active: true,
  },
  {
    id: 'marker-mc1r',
    code: 'BTA18_MC1R_E_LOCUS',
    name: 'Melanocortin 1 Receptor Extension Locus (Red/Black)',
    chromosome: '18',
    positionBp: 14757904,
    refAllele: 'ED',
    altAllele: 'e',
    genomeAssembly: 'ARS-UCD1.2',
    geneSymbol: 'MC1R',
    effectDescription: 'Determines dominant black (ED), black/red wild-type (E+), and recessive red (e) coat pigmentation.',
    resultCount: 98,
    active: true,
  },
  {
    id: 'marker-polled',
    code: 'BTA01_POLLED_CELTIC',
    name: 'Celtic Polled Duplication Insertion (Pc)',
    chromosome: '1',
    positionBp: 2429402,
    refAllele: 'p',
    altAllele: 'P',
    genomeAssembly: 'ARS-UCD1.2',
    geneSymbol: 'POLLED',
    effectDescription: 'Dominant allele conferring true polledness (absence of horns) without dehorning surgery.',
    resultCount: 94,
    active: true,
  },
];

export const initialAnimalMarkerResults: AnimalMarkerResult[] = [
  {
    id: 'amr-1',
    markerId: 'marker-dgat1',
    markerCode: 'BTA14_DGAT1_K232A',
    animalId: 'anim-1',
    animalName: 'Altair Supernova ET',
    animalIdentifier: 'US-9941203',
    genotype: 'K/A',
    assayId: 'assay-1',
    qualityScore: 99.8,
    recordedDate: '2024-03-25',
  },
  {
    id: 'amr-2',
    markerId: 'marker-mc1r',
    markerCode: 'BTA18_MC1R_E_LOCUS',
    animalId: 'anim-1',
    animalName: 'Altair Supernova ET',
    animalIdentifier: 'US-9941203',
    genotype: 'ED/e',
    assayId: 'assay-1',
    qualityScore: 99.9,
    recordedDate: '2024-03-25',
  },
  {
    id: 'amr-3',
    markerId: 'marker-polled',
    markerCode: 'BTA01_POLLED_CELTIC',
    animalId: 'anim-1',
    animalName: 'Altair Supernova ET',
    animalIdentifier: 'US-9941203',
    genotype: 'P/p',
    assayId: 'assay-1',
    qualityScore: 99.5,
    recordedDate: '2024-03-25',
  },
  {
    id: 'amr-4',
    markerId: 'marker-tg',
    markerCode: 'BTA14_TG_5UTR',
    animalId: 'anim-2',
    animalName: 'Ironwood Titan Red',
    animalIdentifier: 'US-7782341',
    genotype: 'T/T',
    assayId: 'assay-2',
    qualityScore: 99.9,
    recordedDate: '2024-02-18',
  },
  {
    id: 'amr-5',
    markerId: 'marker-mc1r',
    markerCode: 'BTA18_MC1R_E_LOCUS',
    animalId: 'anim-2',
    animalName: 'Ironwood Titan Red',
    animalIdentifier: 'US-7782341',
    genotype: 'e/e',
    assayId: 'assay-2',
    qualityScore: 99.9,
    recordedDate: '2024-02-18',
  },
  {
    id: 'amr-6',
    markerId: 'marker-polled',
    markerCode: 'BTA01_POLLED_CELTIC',
    animalId: 'anim-2',
    animalName: 'Ironwood Titan Red',
    animalIdentifier: 'US-7782341',
    genotype: 'P/P',
    assayId: 'assay-2',
    qualityScore: 99.9,
    recordedDate: '2024-02-18',
  },
];

export const initialGeneticConditions: GeneticCondition[] = [
  {
    id: 'cond-blad',
    code: 'BLAD',
    name: 'Bovine Leukocyte Adhesion Deficiency',
    category: 'GENETIC_DEFECT',
    inheritance: 'AUTOSOMAL_RECESSIVE',
    description: 'Deficiency in CD18 surface glycoprotein causing recurrent bacterial infections, uncurable pneumonia, and early calf mortality.',
    affectedBreeds: ['Holstein-Friesian'],
    testMethod: 'Direct PCR-RFLP / Illumina BeadChip SNP',
  },
  {
    id: 'cond-cvm',
    code: 'CVM',
    name: 'Complex Vertebral Malformation',
    category: 'GENETIC_DEFECT',
    inheritance: 'AUTOSOMAL_RECESSIVE',
    description: 'Lethal autosomal recessive disorder causing spinal deformities, hemivertebrae, shortened necks, and severe late abortions.',
    affectedBreeds: ['Holstein-Friesian'],
    testMethod: 'Direct TaqMan Allelic Discrimination Assay',
  },
  {
    id: 'cond-brachy',
    code: 'BY',
    name: 'Brachyspina Syndrome',
    category: 'GENETIC_DEFECT',
    inheritance: 'AUTOSOMAL_RECESSIVE',
    description: 'Extremely shortened vertebral column, craniofacial dysplasia, and early embryonic fetal resorption caused by a 3.3kb deletion in FANCI.',
    affectedBreeds: ['Holstein-Friesian'],
    testMethod: 'Genomic Chip Probes / PCR Deletion Assay',
  },
  {
    id: 'cond-hcd',
    code: 'HCD',
    name: 'Haplotype for Cholesterol Deficiency',
    category: 'GENETIC_DEFECT',
    inheritance: 'AUTOSOMAL_RECESSIVE',
    description: 'Defect in APOB gene leading to hypocholesterolemia, failure to thrive, severe steatorrhea, and calf death within months.',
    affectedBreeds: ['Holstein-Friesian'],
    testMethod: 'Haplotype Imputation / Direct Sequencing',
  },
  {
    id: 'cond-am',
    code: 'AM',
    name: 'Arthrogryposis Multiplex (Curly Calf)',
    category: 'GENETIC_DEFECT',
    inheritance: 'AUTOSOMAL_RECESSIVE',
    description: 'Stillborn calves with bent and twisted spine, rigid joints, and contracted flexor tendons linked to purebred Angus lines.',
    affectedBreeds: ['Black Angus', 'Red Angus'],
    testMethod: 'ISAG / Angus Association Certified DNA Assay',
  },
  {
    id: 'cond-nh',
    code: 'NH',
    name: 'Neuropathic Hydrocephalus (Water Head)',
    category: 'GENETIC_DEFECT',
    inheritance: 'AUTOSOMAL_RECESSIVE',
    description: 'Extreme fluid buildup inside cranial vault, missing cerebral cortex, and severe dystocia in beef lines.',
    affectedBreeds: ['Black Angus', 'Charolais'],
    testMethod: 'Direct DNA Marker Genotyping',
  },
  {
    id: 'cond-polled',
    code: 'POLLED_TRAIT',
    name: 'Polled Condition (Natural Hornlessness)',
    category: 'HORNED_POLLED',
    inheritance: 'AUTOSOMAL_DOMINANT',
    description: 'Celtic or Friesian allele variants conferring hornless skull phenotype with major animal welfare benefits.',
    affectedBreeds: ['Holstein-Friesian', 'Black Angus', 'Hereford', 'Simmental'],
    testMethod: 'High-Density PCR Sequencing',
  },
  {
    id: 'cond-red-coat',
    code: 'RED_FACTOR',
    name: 'Red Factor (Recessive Red Coat)',
    category: 'COLOR_COAT',
    inheritance: 'AUTOSOMAL_RECESSIVE',
    description: 'Loss-of-function allele e in MC1R gene producing red and white hair coat when present in homozygous state.',
    affectedBreeds: ['Holstein-Friesian'],
    testMethod: 'Direct TaqMan / Illumina 100K BeadChip',
  },
];

export const initialAnimalGeneticConditionResults: AnimalGeneticConditionResult[] = [
  {
    id: 'agcr-1',
    conditionId: 'cond-blad',
    conditionCode: 'BLAD',
    conditionName: 'Bovine Leukocyte Adhesion Deficiency',
    animalId: 'anim-1',
    animalName: 'Altair Supernova ET',
    animalIdentifier: 'US-9941203',
    status: 'FREE',
    testedDate: '2024-03-25',
    assayId: 'assay-1',
    labName: 'Neogen GeneSeek Genomics Center',
    certificateNumber: 'NEO-2024-QC-88410',
    source: 'LAB_TEST',
    confidence: 'HIGH',
    notes: 'Tested non-carrier (homozygous normal wild type). Certified Tested Free.',
  },
  {
    id: 'agcr-2',
    conditionId: 'cond-cvm',
    conditionCode: 'CVM',
    conditionName: 'Complex Vertebral Malformation',
    animalId: 'anim-1',
    animalName: 'Altair Supernova ET',
    animalIdentifier: 'US-9941203',
    status: 'FREE',
    testedDate: '2024-03-25',
    assayId: 'assay-1',
    labName: 'Neogen GeneSeek Genomics Center',
    certificateNumber: 'NEO-2024-QC-88411',
    source: 'LAB_TEST',
    confidence: 'HIGH',
  },
  {
    id: 'agcr-3',
    conditionId: 'cond-red-coat',
    conditionCode: 'RED_FACTOR',
    conditionName: 'Red Factor (Recessive Red Coat)',
    animalId: 'anim-1',
    animalName: 'Altair Supernova ET',
    animalIdentifier: 'US-9941203',
    status: 'CARRIER',
    testedDate: '2024-03-25',
    assayId: 'assay-1',
    labName: 'Neogen GeneSeek Genomics Center',
    certificateNumber: 'NEO-2024-QC-88414',
    source: 'LAB_TEST',
    confidence: 'HIGH',
    notes: 'Heterozygous ED/e carrier. Phenotypically black; capable of transmitting red factor to 50% of progeny.',
  },
  {
    id: 'agcr-4',
    conditionId: 'cond-polled',
    conditionCode: 'POLLED_TRAIT',
    conditionName: 'Polled Condition (Natural Hornlessness)',
    animalId: 'anim-1',
    animalName: 'Altair Supernova ET',
    animalIdentifier: 'US-9941203',
    status: 'CARRIER',
    testedDate: '2024-03-25',
    assayId: 'assay-1',
    labName: 'Neogen GeneSeek Genomics Center',
    certificateNumber: 'NEO-2024-QC-88415',
    source: 'LAB_TEST',
    confidence: 'HIGH',
    notes: 'Heterozygous Polled (P/p). All calves have 50% chance of natural hornlessness.',
  },
  {
    id: 'agcr-5',
    conditionId: 'cond-am',
    conditionCode: 'AM',
    conditionName: 'Arthrogryposis Multiplex (Curly Calf)',
    animalId: 'anim-2',
    animalName: 'Ironwood Titan Red',
    animalIdentifier: 'US-7782341',
    status: 'FREE',
    testedDate: '2024-02-18',
    assayId: 'assay-2',
    labName: 'Zoetis Genetics Central Facility',
    certificateNumber: 'ZTS-AM-992014',
    source: 'LAB_TEST',
    confidence: 'HIGH',
    notes: 'Officially certified AM Free by American Angus Association standard testing.',
  },
  {
    id: 'agcr-6',
    conditionId: 'cond-nh',
    conditionCode: 'NH',
    conditionName: 'Neuropathic Hydrocephalus (Water Head)',
    animalId: 'anim-2',
    animalName: 'Ironwood Titan Red',
    animalIdentifier: 'US-7782341',
    status: 'FREE',
    testedDate: '2024-02-18',
    assayId: 'assay-2',
    labName: 'Zoetis Genetics Central Facility',
    certificateNumber: 'ZTS-NH-992015',
    source: 'LAB_TEST',
    confidence: 'HIGH',
  },
  {
    id: 'agcr-7',
    conditionId: 'cond-polled',
    conditionCode: 'POLLED_TRAIT',
    conditionName: 'Polled Condition (Natural Hornlessness)',
    animalId: 'anim-2',
    animalName: 'Ironwood Titan Red',
    animalIdentifier: 'US-7782341',
    status: 'FREE',
    testedDate: '2024-02-18',
    assayId: 'assay-2',
    labName: 'Zoetis Genetics Central Facility',
    certificateNumber: 'ZTS-POL-992016',
    source: 'LAB_TEST',
    confidence: 'HIGH',
    notes: 'Homozygous Polled (P/P). 100% of progeny will be born naturally hornless regardless of dam horn status.',
  },
  {
    id: 'agcr-8',
    conditionId: 'cond-hcd',
    conditionCode: 'HCD',
    conditionName: 'Haplotype for Cholesterol Deficiency',
    animalId: 'anim-6',
    animalName: 'Apex Thunderstruck ET',
    animalIdentifier: 'US-3301984',
    status: 'CARRIER',
    testedDate: '2024-05-12',
    assayId: 'assay-3',
    labName: 'Neogen GeneSeek Genomics Center',
    certificateNumber: 'NEO-HCD-20419',
    source: 'LAB_TEST',
    confidence: 'MEDIUM',
    notes: 'Carrier status confirmed via haplotype inheritance from maternal grandsire. Caution in mating plan: do not cross with HCD carriers.',
  },
  {
    id: 'agcr-9',
    conditionId: 'cond-blad',
    conditionCode: 'BLAD',
    conditionName: 'Bovine Leukocyte Adhesion Deficiency',
    animalId: 'anim-3',
    animalName: 'Meadow Jewel 420',
    animalIdentifier: 'US-6619022',
    status: 'FREE',
    testedDate: '2024-06-01',
    source: 'PEDIGREE_INFERRED',
    confidence: 'HIGH',
    notes: 'Inferred Free based on two generations of certified free ancestors on maternal and paternal branches.',
  },
];

export const initialGeneticEvaluationRuns: GeneticEvaluationRun[] = [
  {
    id: 'run-2026-08',
    runCode: 'EVAL-2026.2-NATIONAL',
    name: 'August 2026 National Single-Step Genomic Evaluation',
    runDate: '2026-08-15',
    breedScope: 'All Breeds (Multi-Breed BLUP)',
    methodology: 'SSGBLUP_SINGLE_STEP',
    softwareName: 'BLUPF90 Suite / preGSf90',
    softwareVersion: 'v2025.4.1',
    geneticBase: 'USA Base 2020 (5-Year Rolling Base)',
    baseYear: 2020,
    country: 'United States',
    status: 'PUBLISHED',
    animalCount: 48,
    traitCount: 13,
    publishedDate: '2026-08-18',
    notes: 'Official active national run incorporating 104K chip genomics and 205-day weaning adjustments.',
  },
  {
    id: 'run-2026-04',
    runCode: 'EVAL-2026.1-SPRING',
    name: 'April 2026 Spring Multi-Trait Genomic Evaluation',
    runDate: '2026-04-10',
    breedScope: 'Holstein & Angus Specialized Populations',
    methodology: 'SSGBLUP_SINGLE_STEP',
    softwareName: 'BLUPF90 Suite / preGSf90',
    softwareVersion: 'v2025.2.0',
    geneticBase: 'USA Base 2020 (5-Year Rolling Base)',
    baseYear: 2020,
    country: 'United States',
    status: 'COMPLETED',
    animalCount: 44,
    traitCount: 13,
    publishedDate: '2026-04-14',
    notes: 'Prior official publication. Maintained for longitudinal genetic trend tracking.',
  },
  {
    id: 'run-2025-12',
    runCode: 'EVAL-2025.3-INTERBULL',
    name: 'December 2025 Interbull MACE Trans-Atlantic Run',
    runDate: '2025-12-05',
    breedScope: 'Holstein-Friesian International Sires',
    methodology: 'BLUP_ANIMAL_MODEL',
    softwareName: 'Interbull MACE Suite',
    softwareVersion: 'v3.8',
    geneticBase: 'Interbull International Base 2015',
    baseYear: 2015,
    country: 'Sweden (Interbull Centre)',
    status: 'COMPLETED',
    animalCount: 32,
    traitCount: 9,
    publishedDate: '2025-12-10',
    notes: 'International conversion run. Caution: Genetic base 2015 is distinct from USA 2020 base.',
  },
  {
    id: 'run-draft-2026-12',
    runCode: 'EVAL-2026.3-DRAFT-FALL',
    name: 'December 2026 Prototype GBLUP Model Candidate',
    runDate: '2026-09-01',
    breedScope: 'All Breeds',
    methodology: 'BAYESIAN_RIDGE_REGRESSION',
    softwareName: 'BGLR R-Package / Custom Julia Pipeline',
    softwareVersion: 'v1.1.2',
    geneticBase: 'USA Base 2025 Target',
    baseYear: 2025,
    country: 'United States',
    status: 'DRAFT',
    animalCount: 0,
    traitCount: 13,
    notes: 'Draft research run exploring feed efficiency Bayesian mixture models. Not published.',
  },
];

export const initialGeneticTraitEstimates: GeneticTraitEstimate[] = [
  // Altair Supernova ET in run-2026-08
  {
    id: 'est-1',
    evaluationRunId: 'run-2026-08',
    evaluationRunCode: 'EVAL-2026.2-NATIONAL',
    animalId: 'anim-1',
    animalName: 'Altair Supernova ET',
    animalIdentifier: 'US-9941203',
    traitId: 'trait-bwt',
    traitCode: 'BWT',
    traitName: 'Birth Weight',
    estimateType: 'GEBV',
    value: -1.2,
    unit: 'kg',
    accuracy: 0.88,
    reliabilityPct: 77,
    percentile: 84,
    rank: 6,
    totalRanked: 48,
    decile: 2,
  },
  {
    id: 'est-2',
    evaluationRunId: 'run-2026-08',
    evaluationRunCode: 'EVAL-2026.2-NATIONAL',
    animalId: 'anim-1',
    animalName: 'Altair Supernova ET',
    animalIdentifier: 'US-9941203',
    traitId: 'trait-wwt',
    traitCode: 'WWT',
    traitName: 'Weaning Weight (205-day)',
    estimateType: 'GEBV',
    value: 28.5,
    unit: 'kg',
    accuracy: 0.84,
    reliabilityPct: 71,
    percentile: 91,
    rank: 4,
    totalRanked: 48,
    decile: 1,
  },
  {
    id: 'est-3',
    evaluationRunId: 'run-2026-08',
    evaluationRunCode: 'EVAL-2026.2-NATIONAL',
    animalId: 'anim-1',
    animalName: 'Altair Supernova ET',
    animalIdentifier: 'US-9941203',
    traitId: 'trait-ywt',
    traitCode: 'YWT',
    traitName: 'Yearling Weight (365-day)',
    estimateType: 'GEBV',
    value: 58.2,
    unit: 'kg',
    accuracy: 0.82,
    reliabilityPct: 67,
    percentile: 88,
    rank: 5,
    totalRanked: 48,
    decile: 2,
  },
  {
    id: 'est-4',
    evaluationRunId: 'run-2026-08',
    evaluationRunCode: 'EVAL-2026.2-NATIONAL',
    animalId: 'anim-1',
    animalName: 'Altair Supernova ET',
    animalIdentifier: 'US-9941203',
    traitId: 'trait-milk',
    traitCode: 'MILK',
    traitName: '305-Day Mature Milk Yield',
    estimateType: 'GEBV',
    value: 1140.0,
    unit: 'kg',
    accuracy: 0.86,
    reliabilityPct: 74,
    percentile: 96,
    rank: 2,
    totalRanked: 48,
    decile: 1,
  },
  {
    id: 'est-5',
    evaluationRunId: 'run-2026-08',
    evaluationRunCode: 'EVAL-2026.2-NATIONAL',
    animalId: 'anim-1',
    animalName: 'Altair Supernova ET',
    animalIdentifier: 'US-9941203',
    traitId: 'trait-fat',
    traitCode: 'FAT_PCT',
    traitName: 'Milk Fat Percentage',
    estimateType: 'GEBV',
    value: 0.18,
    unit: '%',
    accuracy: 0.85,
    reliabilityPct: 72,
    percentile: 82,
    rank: 8,
    totalRanked: 48,
    decile: 2,
  },
  {
    id: 'est-6',
    evaluationRunId: 'run-2026-08',
    evaluationRunCode: 'EVAL-2026.2-NATIONAL',
    animalId: 'anim-1',
    animalName: 'Altair Supernova ET',
    animalIdentifier: 'US-9941203',
    traitId: 'trait-prot',
    traitCode: 'PROT_PCT',
    traitName: 'Milk Protein Percentage',
    estimateType: 'GEBV',
    value: 0.09,
    unit: '%',
    accuracy: 0.85,
    reliabilityPct: 72,
    percentile: 86,
    rank: 6,
    totalRanked: 48,
    decile: 2,
  },
  {
    id: 'est-7',
    evaluationRunId: 'run-2026-08',
    evaluationRunCode: 'EVAL-2026.2-NATIONAL',
    animalId: 'anim-1',
    animalName: 'Altair Supernova ET',
    animalIdentifier: 'US-9941203',
    traitId: 'trait-scs',
    traitCode: 'SCS',
    traitName: 'Somatic Cell Score',
    estimateType: 'GEBV',
    value: -0.24,
    unit: 'score',
    accuracy: 0.78,
    reliabilityPct: 61,
    percentile: 89,
    rank: 5,
    totalRanked: 48,
    decile: 2,
  },

  // Altair Supernova ET in previous run-2026-04 (for longitudinal comparison)
  {
    id: 'est-1-prev',
    evaluationRunId: 'run-2026-04',
    evaluationRunCode: 'EVAL-2026.1-SPRING',
    animalId: 'anim-1',
    animalName: 'Altair Supernova ET',
    animalIdentifier: 'US-9941203',
    traitId: 'trait-milk',
    traitCode: 'MILK',
    traitName: '305-Day Mature Milk Yield',
    estimateType: 'GEBV',
    value: 1080.0,
    unit: 'kg',
    accuracy: 0.81,
    reliabilityPct: 66,
    percentile: 94,
    rank: 3,
    totalRanked: 44,
    decile: 1,
  },
  {
    id: 'est-2-prev',
    evaluationRunId: 'run-2026-04',
    evaluationRunCode: 'EVAL-2026.1-SPRING',
    animalId: 'anim-1',
    animalName: 'Altair Supernova ET',
    animalIdentifier: 'US-9941203',
    traitId: 'trait-wwt',
    traitCode: 'WWT',
    traitName: 'Weaning Weight (205-day)',
    estimateType: 'GEBV',
    value: 27.2,
    unit: 'kg',
    accuracy: 0.79,
    reliabilityPct: 62,
    percentile: 89,
    rank: 5,
    totalRanked: 44,
    decile: 2,
  },

  // Ironwood Titan Red in run-2026-08
  {
    id: 'est-8',
    evaluationRunId: 'run-2026-08',
    evaluationRunCode: 'EVAL-2026.2-NATIONAL',
    animalId: 'anim-2',
    animalName: 'Ironwood Titan Red',
    animalIdentifier: 'US-7782341',
    traitId: 'trait-bwt',
    traitCode: 'BWT',
    traitName: 'Birth Weight',
    estimateType: 'EPD',
    value: -0.8,
    unit: 'kg',
    accuracy: 0.94,
    reliabilityPct: 88,
    percentile: 79,
    rank: 9,
    totalRanked: 48,
    decile: 3,
  },
  {
    id: 'est-9',
    evaluationRunId: 'run-2026-08',
    evaluationRunCode: 'EVAL-2026.2-NATIONAL',
    animalId: 'anim-2',
    animalName: 'Ironwood Titan Red',
    animalIdentifier: 'US-7782341',
    traitId: 'trait-wwt',
    traitCode: 'WWT',
    traitName: 'Weaning Weight (205-day)',
    estimateType: 'EPD',
    value: 36.4,
    unit: 'kg',
    accuracy: 0.92,
    reliabilityPct: 85,
    percentile: 98,
    rank: 1,
    totalRanked: 48,
    decile: 1,
  },
  {
    id: 'est-10',
    evaluationRunId: 'run-2026-08',
    evaluationRunCode: 'EVAL-2026.2-NATIONAL',
    animalId: 'anim-2',
    animalName: 'Ironwood Titan Red',
    animalIdentifier: 'US-7782341',
    traitId: 'trait-ywt',
    traitCode: 'YWT',
    traitName: 'Yearling Weight (365-day)',
    estimateType: 'EPD',
    value: 72.8,
    unit: 'kg',
    accuracy: 0.90,
    reliabilityPct: 81,
    percentile: 99,
    rank: 1,
    totalRanked: 48,
    decile: 1,
  },
  {
    id: 'est-11',
    evaluationRunId: 'run-2026-08',
    evaluationRunCode: 'EVAL-2026.2-NATIONAL',
    animalId: 'anim-2',
    animalName: 'Ironwood Titan Red',
    animalIdentifier: 'US-7782341',
    traitId: 'trait-marb',
    traitCode: 'MARB',
    traitName: 'Intramuscular Fat / Marbling Score',
    estimateType: 'EPD',
    value: 1.15,
    unit: 'score',
    accuracy: 0.88,
    reliabilityPct: 77,
    percentile: 97,
    rank: 2,
    totalRanked: 48,
    decile: 1,
  },
  {
    id: 'est-12',
    evaluationRunId: 'run-2026-08',
    evaluationRunCode: 'EVAL-2026.2-NATIONAL',
    animalId: 'anim-2',
    animalName: 'Ironwood Titan Red',
    animalIdentifier: 'US-7782341',
    traitId: 'trait-rea',
    traitCode: 'REA',
    traitName: 'Ribeye Muscle Area',
    estimateType: 'EPD',
    value: 1.04,
    unit: 'sq.cm',
    accuracy: 0.87,
    reliabilityPct: 76,
    percentile: 94,
    rank: 3,
    totalRanked: 48,
    decile: 1,
  },
  {
    id: 'est-13',
    evaluationRunId: 'run-2026-08',
    evaluationRunCode: 'EVAL-2026.2-NATIONAL',
    animalId: 'anim-2',
    animalName: 'Ironwood Titan Red',
    animalIdentifier: 'US-7782341',
    traitId: 'trait-fcr',
    traitCode: 'FCR',
    traitName: 'Feed Conversion Ratio (RFI)',
    estimateType: 'EPD',
    value: -0.42,
    unit: 'ratio',
    accuracy: 0.74,
    reliabilityPct: 55,
    percentile: 95,
    rank: 2,
    totalRanked: 48,
    decile: 1,
  },

  // Meadow Jewel 420 in run-2026-08
  {
    id: 'est-14',
    evaluationRunId: 'run-2026-08',
    evaluationRunCode: 'EVAL-2026.2-NATIONAL',
    animalId: 'anim-3',
    animalName: 'Meadow Jewel 420',
    animalIdentifier: 'US-6619022',
    traitId: 'trait-milk',
    traitCode: 'MILK',
    traitName: '305-Day Mature Milk Yield',
    estimateType: 'EBV',
    value: 480.0,
    unit: 'kg',
    accuracy: 0.68,
    reliabilityPct: 46,
    percentile: 65,
    rank: 16,
    totalRanked: 48,
    decile: 4,
  },
  {
    id: 'est-15',
    evaluationRunId: 'run-2026-08',
    evaluationRunCode: 'EVAL-2026.2-NATIONAL',
    animalId: 'anim-3',
    animalName: 'Meadow Jewel 420',
    animalIdentifier: 'US-6619022',
    traitId: 'trait-fat',
    traitCode: 'FAT_PCT',
    traitName: 'Milk Fat Percentage',
    estimateType: 'EBV',
    value: 0.44,
    unit: '%',
    accuracy: 0.72,
    reliabilityPct: 52,
    percentile: 99,
    rank: 1,
    totalRanked: 48,
    decile: 1,
  },

  // Onyx Black Diamond in run-2026-08
  {
    id: 'est-16',
    evaluationRunId: 'run-2026-08',
    evaluationRunCode: 'EVAL-2026.2-NATIONAL',
    animalId: 'anim-4',
    animalName: 'Onyx Black Diamond',
    animalIdentifier: 'US-8821940',
    traitId: 'trait-wwt',
    traitCode: 'WWT',
    traitName: 'Weaning Weight (205-day)',
    estimateType: 'EPD',
    value: 31.8,
    unit: 'kg',
    accuracy: 0.81,
    reliabilityPct: 66,
    percentile: 92,
    rank: 3,
    totalRanked: 48,
    decile: 1,
  },
  {
    id: 'est-17',
    evaluationRunId: 'run-2026-08',
    evaluationRunCode: 'EVAL-2026.2-NATIONAL',
    animalId: 'anim-4',
    animalName: 'Onyx Black Diamond',
    animalIdentifier: 'US-8821940',
    traitId: 'trait-marb',
    traitCode: 'MARB',
    traitName: 'Intramuscular Fat / Marbling Score',
    estimateType: 'EPD',
    value: 0.92,
    unit: 'score',
    accuracy: 0.79,
    reliabilityPct: 62,
    percentile: 91,
    rank: 4,
    totalRanked: 48,
    decile: 1,
  },
];

export const initialAnimalGeneticMetrics: AnimalGeneticMetric[] = [
  {
    id: 'agm-1',
    animalId: 'anim-1',
    animalName: 'Altair Supernova ET',
    animalIdentifier: 'US-9941203',
    metricType: 'PEDIGREE_INBREEDING_F',
    value: 0.048,
    formattedValue: '4.8%',
    method: 'Wright-Meuwissen 8-Generation Pedigree Path Analysis',
    calculationDate: '2026-08-16',
    source: 'PEDIGREE_ANALYSIS',
    evaluationRunId: 'run-2026-08',
    referencePopulation: 'US Holstein Purebred Registry Herdbook 2026',
    percentileRank: 38,
    notes: 'Well below breed average (8.2%). Safe for wide commercial outcrossing.',
  },
  {
    id: 'agm-2',
    animalId: 'anim-1',
    animalName: 'Altair Supernova ET',
    animalIdentifier: 'US-9941203',
    metricType: 'GENOMIC_INBREEDING_FROH',
    value: 0.052,
    formattedValue: '5.2%',
    method: 'Runs of Homozygosity (ROH > 4Mb sliding window, PLINK v1.9)',
    calculationDate: '2026-08-16',
    source: 'GENOMIC_ANALYSIS',
    evaluationRunId: 'run-2026-08',
    referencePopulation: '100K High Density Genomic Reference Population',
    percentileRank: 42,
    notes: 'Genomic ROH metric closely aligns with 8-generation pedigree inbreeding coefficient.',
  },
  {
    id: 'agm-3',
    animalId: 'anim-1',
    animalName: 'Altair Supernova ET',
    animalIdentifier: 'US-9941203',
    metricType: 'GENOMIC_HETEROZYGOSITY',
    value: 0.342,
    formattedValue: '34.2%',
    method: 'Autosomal Polymorphic SNP Proportion (104K loci)',
    calculationDate: '2026-08-16',
    source: 'GENOMIC_ANALYSIS',
    evaluationRunId: 'run-2026-08',
    referencePopulation: '100K High Density Genomic Reference Population',
    percentileRank: 64,
  },
  {
    id: 'agm-4',
    animalId: 'anim-2',
    animalName: 'Ironwood Titan Red',
    animalIdentifier: 'US-7782341',
    metricType: 'PEDIGREE_INBREEDING_F',
    value: 0.032,
    formattedValue: '3.2%',
    method: 'Wright-Meuwissen 7-Generation Pedigree Path Analysis',
    calculationDate: '2026-08-16',
    source: 'PEDIGREE_ANALYSIS',
    evaluationRunId: 'run-2026-08',
    referencePopulation: 'American Angus Association Foundation Herdbook',
    percentileRank: 26,
    notes: 'Outcross foundation sire line with exceptionally low pedigree coancestry.',
  },
  {
    id: 'agm-5',
    animalId: 'anim-2',
    animalName: 'Ironwood Titan Red',
    animalIdentifier: 'US-7782341',
    metricType: 'GENOMIC_INBREEDING_FROH',
    value: 0.035,
    formattedValue: '3.5%',
    method: 'Runs of Homozygosity (ROH > 4Mb sliding window, 777K BovineHD)',
    calculationDate: '2026-08-16',
    source: 'GENOMIC_ANALYSIS',
    evaluationRunId: 'run-2026-08',
    referencePopulation: 'BovineHD 770K Angus Reference Panel',
    percentileRank: 28,
  },
  {
    id: 'agm-6',
    animalId: 'anim-2',
    animalName: 'Ironwood Titan Red',
    animalIdentifier: 'US-7782341',
    metricType: 'MEAN_KINSHIP',
    value: 0.041,
    formattedValue: '4.1%',
    method: 'Average Kinship Against Active Registered AI Sire Population',
    calculationDate: '2026-08-16',
    source: 'PEDIGREE_ANALYSIS',
    evaluationRunId: 'run-2026-08',
    referencePopulation: 'Active National AI Beef Bull Population',
    percentileRank: 18,
    notes: 'Highly valuable genetic outcross with minimal average kinship to commercial females.',
  },
  {
    id: 'agm-7',
    animalId: 'anim-3',
    animalName: 'Meadow Jewel 420',
    animalIdentifier: 'US-6619022',
    metricType: 'PEDIGREE_INBREEDING_F',
    value: 0.065,
    formattedValue: '6.5%',
    method: 'Wright-Meuwissen 6-Generation Pedigree Path Analysis',
    calculationDate: '2026-08-16',
    source: 'PEDIGREE_ANALYSIS',
    referencePopulation: 'US Jersey Association Herdbook',
    percentileRank: 55,
  },
  {
    id: 'agm-8',
    animalId: 'anim-4',
    animalName: 'Onyx Black Diamond',
    animalIdentifier: 'US-8821940',
    metricType: 'PEDIGREE_INBREEDING_F',
    value: 0.038,
    formattedValue: '3.8%',
    method: 'Wright-Meuwissen 7-Generation Pedigree Path Analysis',
    calculationDate: '2026-08-16',
    source: 'PEDIGREE_ANALYSIS',
    referencePopulation: 'American Angus Association Foundation Herdbook',
    percentileRank: 31,
  },
];
