import {
  AdministrativeBoundary,
  FarmGeometryRecord,
  AnimalMapLocation,
  MovementVectorMap,
  DiseaseEventMap,
  MarketplaceListingMap,
  GeofenceZone,
  GeofenceEventRecord,
  SavedMapView,
} from './bovine-map-types';

/**
 * 1. Administrative Boundaries (Regions & Districts)
 * Realistic polygons with rich agricultural & regulatory statistics
 */
export const initialAdministrativeBoundaries: AdministrativeBoundary[] = [
  {
    id: 'region-tigray',
    code: 'REG-TIG',
    name: 'Tigray Regional State',
    level: 'REGION',
    center: [13.8, 39.2],
    polygon: [
      [14.5, 38.0],
      [14.7, 39.5],
      [14.2, 40.0],
      [13.2, 39.8],
      [12.8, 39.4],
      [13.3, 38.2],
      [14.0, 37.8],
      [14.5, 38.0],
    ],
    statistics: {
      animalCount: 48210,
      farmCount: 184,
      breedingStockCount: 6840,
      birthsYtd: 4120,
      mortalityRate: 1.8,
      vaccinationRate: 91.4,
      genotypeCoverage: 38.6,
      pregnancyRate: 74.2,
      complianceRate: 94.8,
      activeHealthAlerts: 3,
      quarantinedFarmsCount: 1,
    },
  },
  {
    id: 'district-mekelle',
    code: 'DIST-MEK',
    name: 'Mekelle District',
    level: 'DISTRICT',
    parentCode: 'REG-TIG',
    center: [13.49, 39.47],
    polygon: [
      [13.58, 39.4],
      [13.6, 39.55],
      [13.42, 39.57],
      [13.4, 39.42],
      [13.58, 39.4],
    ],
    statistics: {
      animalCount: 14280,
      farmCount: 46,
      breedingStockCount: 2310,
      birthsYtd: 1240,
      mortalityRate: 1.2,
      vaccinationRate: 94.2,
      genotypeCoverage: 44.5,
      pregnancyRate: 78.0,
      complianceRate: 97.1,
      activeHealthAlerts: 1,
      quarantinedFarmsCount: 0,
    },
  },
  {
    id: 'district-shire',
    code: 'DIST-SHI',
    name: 'Shire / Northwestern District',
    level: 'DISTRICT',
    parentCode: 'REG-TIG',
    center: [14.1, 38.28],
    polygon: [
      [14.18, 38.2],
      [14.2, 38.38],
      [14.02, 38.4],
      [14.0, 38.22],
      [14.18, 38.2],
    ],
    statistics: {
      animalCount: 18400,
      farmCount: 58,
      breedingStockCount: 3120,
      birthsYtd: 1680,
      mortalityRate: 1.5,
      vaccinationRate: 96.0,
      genotypeCoverage: 52.8,
      pregnancyRate: 79.5,
      complianceRate: 98.4,
      activeHealthAlerts: 0,
      quarantinedFarmsCount: 0,
    },
  },
  {
    id: 'region-sidama',
    code: 'REG-SID',
    name: 'Sidama Regional State',
    level: 'REGION',
    center: [7.05, 38.48],
    polygon: [
      [7.3, 38.3],
      [7.35, 38.75],
      [6.85, 38.8],
      [6.75, 38.35],
      [7.3, 38.3],
    ],
    statistics: {
      animalCount: 26400,
      farmCount: 92,
      breedingStockCount: 3890,
      birthsYtd: 2450,
      mortalityRate: 2.1,
      vaccinationRate: 88.5,
      genotypeCoverage: 31.0,
      pregnancyRate: 71.3,
      complianceRate: 92.0,
      activeHealthAlerts: 2,
      quarantinedFarmsCount: 1,
    },
  },
  {
    id: 'region-amhara',
    code: 'REG-AMH',
    name: 'Amhara Regional State',
    level: 'REGION',
    center: [11.6, 37.4],
    polygon: [
      [12.4, 36.8],
      [12.6, 38.2],
      [11.0, 38.5],
      [10.8, 37.0],
      [12.4, 36.8],
    ],
    statistics: {
      animalCount: 34100,
      farmCount: 114,
      breedingStockCount: 4200,
      birthsYtd: 2890,
      mortalityRate: 2.4,
      vaccinationRate: 85.0,
      genotypeCoverage: 26.5,
      pregnancyRate: 69.8,
      complianceRate: 89.6,
      activeHealthAlerts: 4,
      quarantinedFarmsCount: 2,
    },
  },
];

/**
 * 2. Detailed Farm Geometry & Paddock Subdivisions
 */
export const initialFarmGeometries: FarmGeometryRecord[] = [
  {
    farmId: 'farm-1',
    center: [8.5414, 39.2689],
    perimeterPolygon: [
      [8.546, 39.263],
      [8.547, 39.274],
      [8.536, 39.276],
      [8.535, 39.264],
      [8.546, 39.263],
    ],
    totalAcreageHectares: 145.8,
    verificationStatus: 'GOVERNMENT_VERIFIED',
    verifiedAt: '2026-03-12T09:30:00Z',
    verifiedBy: 'National Land & Veterinary GIS Registry',
    areas: [
      {
        id: 'area-1-1',
        farmId: 'farm-1',
        name: 'North Breeding Pasture A',
        code: 'PDK-A1',
        type: 'BREEDING_PADDOCK',
        polygon: [
          [8.545, 39.264],
          [8.546, 39.269],
          [8.541, 39.269],
          [8.54, 39.264],
          [8.545, 39.264],
        ],
        acreageHectares: 24.5,
        capacityHead: 35,
        currentOccupancyHead: 22,
        waterSourceAvailable: true,
        shadeAvailable: true,
        active: true,
      },
      {
        id: 'area-1-2',
        farmId: 'farm-1',
        name: 'East Calving & Maternal Unit',
        code: 'CALV-E1',
        type: 'CALVING_AREA',
        polygon: [
          [8.545, 39.269],
          [8.546, 39.273],
          [8.541, 39.273],
          [8.541, 39.269],
          [8.545, 39.269],
        ],
        acreageHectares: 18.2,
        capacityHead: 25,
        currentOccupancyHead: 14,
        waterSourceAvailable: true,
        shadeAvailable: true,
        active: true,
      },
      {
        id: 'area-1-3',
        farmId: 'farm-1',
        name: 'Biosecurity Quarantine Isolation Pen',
        code: 'QUAR-Q1',
        type: 'QUARANTINE_PEN',
        polygon: [
          [8.537, 39.264],
          [8.539, 39.267],
          [8.536, 39.267],
          [8.535, 39.264],
          [8.537, 39.264],
        ],
        acreageHectares: 6.4,
        capacityHead: 10,
        currentOccupancyHead: 2,
        waterSourceAvailable: true,
        shadeAvailable: true,
        active: true,
      },
      {
        id: 'area-1-4',
        farmId: 'farm-1',
        name: 'Primary Handling & Vet Facility',
        code: 'BARN-1',
        type: 'HANDLING_FACILITY',
        polygon: [
          [8.539, 39.268],
          [8.541, 39.271],
          [8.538, 39.271],
          [8.537, 39.268],
          [8.539, 39.268],
        ],
        acreageHectares: 8.5,
        capacityHead: 50,
        currentOccupancyHead: 12,
        waterSourceAvailable: true,
        shadeAvailable: true,
        active: true,
      },
    ],
  },
  {
    farmId: 'farm-2',
    center: [8.7523, 38.9812],
    perimeterPolygon: [
      [8.758, 38.975],
      [8.759, 38.987],
      [8.746, 38.989],
      [8.745, 38.976],
      [8.758, 38.975],
    ],
    totalAcreageHectares: 180.2,
    verificationStatus: 'GPS_VERIFIED',
    verifiedAt: '2026-02-18T14:15:00Z',
    verifiedBy: 'Field Geospatial Surveyor',
    areas: [
      {
        id: 'area-2-1',
        farmId: 'farm-2',
        name: 'Main Beef Grazing Paddock',
        code: 'PDK-B1',
        type: 'PASTURE',
        polygon: [
          [8.756, 38.977],
          [8.757, 38.985],
          [8.75, 38.985],
          [8.748, 38.977],
          [8.756, 38.977],
        ],
        acreageHectares: 48.0,
        capacityHead: 60,
        currentOccupancyHead: 38,
        waterSourceAvailable: true,
        shadeAvailable: true,
        active: true,
      },
      {
        id: 'area-2-2',
        farmId: 'farm-2',
        name: 'AI & Sire Collection Barn',
        code: 'AI-HUB',
        type: 'BARN',
        polygon: [
          [8.749, 38.981],
          [8.751, 38.984],
          [8.747, 38.984],
          [8.747, 38.981],
          [8.749, 38.981],
        ],
        acreageHectares: 5.2,
        capacityHead: 20,
        currentOccupancyHead: 8,
        waterSourceAvailable: true,
        shadeAvailable: true,
        active: true,
      },
    ],
  },
  {
    farmId: 'farm-3',
    center: [7.0541, 38.4812],
    perimeterPolygon: [
      [7.06, 38.475],
      [7.062, 38.488],
      [7.048, 38.489],
      [7.046, 38.476],
      [7.06, 38.475],
    ],
    totalAcreageHectares: 120.0,
    verificationStatus: 'GOVERNMENT_VERIFIED',
    verifiedAt: '2026-01-20T11:00:00Z',
    verifiedBy: 'National Livestock Directorate',
    areas: [
      {
        id: 'area-3-1',
        farmId: 'farm-3',
        name: 'Genomic Nucleus Donor Pasture',
        code: 'GEN-D1',
        type: 'BREEDING_PADDOCK',
        polygon: [
          [7.058, 38.478],
          [7.059, 38.485],
          [7.052, 38.485],
          [7.051, 38.478],
          [7.058, 38.478],
        ],
        acreageHectares: 32.5,
        capacityHead: 40,
        currentOccupancyHead: 28,
        waterSourceAvailable: true,
        shadeAvailable: true,
        active: true,
      },
    ],
  },
  {
    farmId: 'farm-4',
    center: [11.5912, 37.3821],
    perimeterPolygon: [
      [11.6, 37.375],
      [11.602, 37.39],
      [11.583, 37.392],
      [11.581, 37.376],
      [11.6, 37.375],
    ],
    totalAcreageHectares: 210.0,
    verificationStatus: 'SUPERVISOR_VERIFIED',
    verifiedAt: '2026-04-05T16:20:00Z',
    verifiedBy: 'Regional Livestock Supervisor',
    areas: [
      {
        id: 'area-4-1',
        farmId: 'farm-4',
        name: 'Highland Seedstock Grazing Run',
        code: 'SEED-H1',
        type: 'PASTURE',
        polygon: [
          [11.598, 37.378],
          [11.599, 37.388],
          [11.588, 37.388],
          [11.587, 37.378],
          [11.598, 37.378],
        ],
        acreageHectares: 75.0,
        capacityHead: 80,
        currentOccupancyHead: 45,
        waterSourceAvailable: true,
        shadeAvailable: true,
        active: true,
      },
    ],
  },
];

/**
 * 3. Animals on the Map with Location Confidence Taxonomy
 * SENSOR_GPS (Live Collar Tracker with precision)
 * FARM_PADDOCK_LOCATION (RFID Paddock Scanner assignment)
 * EVENT_DERIVED (Last confirmed movement / vet check)
 */
export const initialAnimalLocations: AnimalMapLocation[] = [
  {
    animalId: 'ba-001',
    name: 'GOLDEN STAR 1248',
    primaryIdentifier: 'ET-4822',
    dgr: 'DGR-NG-029382',
    breed: 'Nelore',
    sex: 'MALE',
    breedingStock: true,
    breedingRole: 'AI Sire / Natural Service Sire',
    farmId: 'farm-1',
    farmName: 'Apex Genetics Core Center',
    farmAreaId: 'area-1-1',
    farmAreaName: 'North Breeding Pasture A',
    coordinates: [8.5432, 39.2665],
    locationConfidence: 'SENSOR_GPS',
    precision: 'EXACT',
    accuracyMeters: 4.8,
    recordedAt: '2026-09-08T18:42:15Z',
    deviceId: 'DEV-GPS-9912',
    batteryPct: 92,
    telemetryFreshnessSec: 45,
    healthStatus: 'NORMAL',
    geneticIndex: 138,
    selectionIndexValue: '$B +168.4',
  },
  {
    animalId: 'ba-002',
    name: 'SILVER QUEEN 402',
    primaryIdentifier: 'ET-3910',
    dgr: 'DGR-BR-118491',
    breed: 'Borana',
    sex: 'FEMALE',
    breedingStock: true,
    breedingRole: 'Elite Donor Female',
    farmId: 'farm-1',
    farmName: 'Apex Genetics Core Center',
    farmAreaId: 'area-1-2',
    farmAreaName: 'East Calving & Maternal Unit',
    coordinates: [8.5438, 39.2711],
    locationConfidence: 'FARM_PADDOCK_LOCATION',
    precision: 'EXACT',
    accuracyMeters: 15.0,
    recordedAt: '2026-09-08T18:28:00Z',
    healthStatus: 'NORMAL',
    geneticIndex: 129,
    selectionIndexValue: '$M +82.0',
  },
  {
    animalId: 'ba-003',
    name: 'BARON OF SHENANDOAH',
    primaryIdentifier: 'ET-8819',
    dgr: 'DGR-AN-992014',
    breed: 'Black Angus',
    sex: 'MALE',
    breedingStock: true,
    breedingRole: 'Natural Service Sire',
    farmId: 'farm-2',
    farmName: 'Highland Beef Research Station',
    farmAreaId: 'area-2-1',
    farmAreaName: 'Main Beef Grazing Paddock',
    coordinates: [8.7534, 38.9818],
    locationConfidence: 'SENSOR_GPS',
    precision: 'EXACT',
    accuracyMeters: 6.2,
    recordedAt: '2026-09-08T18:41:30Z',
    deviceId: 'DEV-GPS-4401',
    batteryPct: 78,
    telemetryFreshnessSec: 90,
    healthStatus: 'NORMAL',
    geneticIndex: 142,
    selectionIndexValue: '$B +174.5',
  },
  {
    animalId: 'ba-004',
    name: 'CORONA BELLE 910',
    primaryIdentifier: 'ET-5502',
    dgr: 'DGR-BR-550211',
    breed: 'Borana',
    sex: 'FEMALE',
    breedingStock: true,
    breedingRole: 'Candidate Breeding Female',
    farmId: 'farm-3',
    farmName: 'Emerald Prairie Genomic Nucleus',
    farmAreaId: 'area-3-1',
    farmAreaName: 'Genomic Nucleus Donor Pasture',
    coordinates: [7.0555, 38.4819],
    locationConfidence: 'EVENT_DERIVED',
    precision: 'APPROXIMATE',
    accuracyMeters: 120.0,
    recordedAt: '2026-09-08T12:00:00Z',
    healthStatus: 'NORMAL',
    geneticIndex: 124,
    selectionIndexValue: '$M +71.2',
  },
  {
    animalId: 'ba-005',
    name: 'RED EMPEROR 882',
    primaryIdentifier: 'ET-7714',
    dgr: 'DGR-BR-771409',
    breed: 'Brahman',
    sex: 'MALE',
    breedingStock: true,
    breedingRole: 'AI Sire',
    farmId: 'farm-4',
    farmName: 'Sunrise Pastures Seedstock Hub',
    farmAreaId: 'area-4-1',
    farmAreaName: 'Highland Seedstock Grazing Run',
    coordinates: [11.5932, 37.3845],
    locationConfidence: 'SENSOR_GPS',
    precision: 'EXACT',
    accuracyMeters: 5.5,
    recordedAt: '2026-09-08T18:40:00Z',
    deviceId: 'DEV-GPS-6623',
    batteryPct: 85,
    telemetryFreshnessSec: 180,
    healthStatus: 'QUARANTINE',
    geneticIndex: 131,
    selectionIndexValue: '$B +152.0',
  },
];

/**
 * 4. Geographic Movement Vectors & Flow Routes
 */
export const initialMovementVectors: MovementVectorMap[] = [
  {
    id: 'mov-geo-1',
    referenceNumber: 'MOV-2026-0891',
    fromFarmId: 'farm-1',
    fromFarmName: 'Apex Genetics Core Center (Adama)',
    fromCoordinates: [8.5414, 39.2689],
    toFarmId: 'farm-2',
    toFarmName: 'Highland Beef Station (Bishoftu)',
    toCoordinates: [8.7523, 38.9812],
    volumeHead: 14,
    animalIds: ['ba-003', 'ba-007'],
    movementType: 'BREEDING_TRANSFER',
    movementDate: '2026-09-07T08:00:00Z',
    status: 'IN_TRANSIT',
    carrierName: 'National Livestock Transit Fleet #4',
    vehicleRegistration: 'ET-3-88291',
    reason: 'Nucleus breeding sire deployment for synchronized breeding cycle',
  },
  {
    id: 'mov-geo-2',
    referenceNumber: 'MOV-2026-0842',
    fromFarmId: 'farm-3',
    fromFarmName: 'Emerald Prairie Genomic Nucleus (Hawassa)',
    fromCoordinates: [7.0541, 38.4812],
    toFarmId: 'farm-1',
    toFarmName: 'Apex Genetics Core Center (Adama)',
    toCoordinates: [8.5414, 39.2689],
    volumeHead: 8,
    animalIds: ['ba-004'],
    movementType: 'EMBRYO_DONOR_TRANSFER',
    movementDate: '2026-09-04T10:30:00Z',
    status: 'COMPLETED',
    carrierName: 'Biosecure Climate Hauler Alpha',
    vehicleRegistration: 'ET-2-44109',
    reason: 'High-merit donor transfer for OPU/IVF flush program',
  },
  {
    id: 'mov-geo-3',
    referenceNumber: 'MOV-2026-0914',
    fromFarmId: 'farm-4',
    fromFarmName: 'Sunrise Pastures Seedstock Hub (Bahir Dar)',
    fromCoordinates: [11.5912, 37.3821],
    toFarmId: 'farm-2',
    toFarmName: 'Highland Beef Station (Bishoftu)',
    toCoordinates: [8.7523, 38.9812],
    volumeHead: 20,
    animalIds: ['ba-005'],
    movementType: 'COMMERCIAL_STOCK_SALE',
    movementDate: '2026-09-09T06:00:00Z',
    status: 'PENDING',
    carrierName: 'Highland Agro Freight',
    vehicleRegistration: 'ET-4-19284',
    reason: 'Yearling bulls transfer following Phase III performance indexing',
  },
];

/**
 * 5. Disease Events & Concentric Surveillance Zones (5km, 10km, 25km)
 */
export const initialDiseaseEvents: DiseaseEventMap[] = [
  {
    id: 'he-geo-1',
    caseNumber: 'CASE-BIO-2026-088',
    farmId: 'farm-4',
    farmName: 'Sunrise Pastures Seedstock Hub',
    coordinates: [11.5912, 37.3821],
    diseaseName: 'Foot-and-Mouth Disease (FMD) Serotype O',
    severity: 'CRITICAL',
    status: 'CONFIRMED',
    affectedCount: 6,
    deathsCount: 0,
    startedAt: '2026-09-03T11:20:00Z',
    quarantineActive: true,
    bufferRadiusKm: [5, 10, 25],
    investigatingOfficer: 'Dr. Almaz Kebede (State Epidemiologist)',
    notes: 'Quarantine order #ORD-2026-99 issued. Ring vaccination initiated in 5km buffer radius.',
  },
  {
    id: 'he-geo-2',
    caseNumber: 'CASE-BIO-2026-094',
    farmId: 'farm-1',
    farmName: 'Apex Genetics Core Center',
    coordinates: [8.5414, 39.2689],
    diseaseName: 'Bovine Viral Diarrhea (BVDV Type 2)',
    severity: 'MEDIUM',
    status: 'UNDER_INVESTIGATION',
    affectedCount: 2,
    deathsCount: 0,
    startedAt: '2026-09-06T09:15:00Z',
    quarantineActive: true,
    bufferRadiusKm: [5, 10],
    investigatingOfficer: 'Dr. Michael Tesfaye',
    notes: 'Two isolation pen candidates identified during quarantine intake testing.',
  },
];

/**
 * 6. Marketplace Geographic Listings with Privacy Precision Circles
 */
export const initialMarketplaceListingsMap: MarketplaceListingMap[] = [
  {
    id: 'mkt-geo-1',
    title: 'Elite Nelore Breeding Bull - Proven DNA Certified Sire',
    animalId: 'ba-001',
    animalName: 'GOLDEN STAR 1248',
    listingType: 'LIVE_ANIMAL',
    breed: 'Nelore',
    sex: 'MALE',
    price: 185000,
    currency: 'ETB',
    farmId: 'farm-1',
    farmName: 'Apex Genetics Core Center',
    region: 'Tigray',
    coordinates: [8.5414, 39.2689],
    privacyPrecision: 'APPROXIMATE',
    approximateRadiusMeters: 3000,
    dnaVerified: true,
    geneticIndex: 138,
  },
  {
    id: 'mkt-geo-2',
    title: 'Top 1% Borana Breeding Cow - Embryo Flush Ready',
    animalId: 'ba-002',
    animalName: 'SILVER QUEEN 402',
    listingType: 'LIVE_ANIMAL',
    breed: 'Borana',
    sex: 'FEMALE',
    price: 142000,
    currency: 'ETB',
    farmId: 'farm-1',
    farmName: 'Apex Genetics Core Center',
    region: 'Tigray',
    coordinates: [8.5414, 39.2689],
    privacyPrecision: 'APPROXIMATE',
    approximateRadiusMeters: 3000,
    dnaVerified: true,
    geneticIndex: 129,
  },
  {
    id: 'mkt-geo-3',
    title: 'High-Genetic Merit Angus Bull Straws (Cryo Semen Hub)',
    animalId: 'ba-003',
    animalName: 'BARON OF SHENANDOAH',
    listingType: 'SEMEN',
    breed: 'Black Angus',
    sex: 'MALE',
    price: 1200,
    currency: 'ETB',
    farmId: 'farm-2',
    farmName: 'Highland Beef Station Semen Bank',
    region: 'Tigray',
    coordinates: [8.7523, 38.9812],
    privacyPrecision: 'EXACT',
    approximateRadiusMeters: 500,
    dnaVerified: true,
    geneticIndex: 142,
  },
  {
    id: 'mkt-geo-4',
    title: 'In-Vitro Fertilized Borana x Nelore Cross Embryos (Grade 1)',
    listingType: 'EMBRYO',
    breed: 'Borana Cross',
    price: 9500,
    currency: 'ETB',
    farmId: 'farm-3',
    farmName: 'Emerald Prairie Genomic Embryo Lab',
    region: 'Sidama',
    coordinates: [7.0541, 38.4812],
    privacyPrecision: 'EXACT',
    approximateRadiusMeters: 500,
    dnaVerified: true,
    geneticIndex: 132,
  },
];

/**
 * 7. Geofences & Realtime Perimeter Breach Events
 */
export const initialGeofences: GeofenceZone[] = [
  {
    id: 'geo-fence-1',
    name: 'Apex Genetics Outer Perimeter Geofence',
    type: 'FARM_PERIMETER',
    polygon: [
      [8.546, 39.263],
      [8.547, 39.274],
      [8.536, 39.276],
      [8.535, 39.264],
      [8.546, 39.263],
    ],
    farmId: 'farm-1',
    alertOnEnter: false,
    alertOnExit: true,
    active: true,
  },
  {
    id: 'geo-fence-2',
    name: 'North Breeding Paddock Restricted Enclosure',
    type: 'PADDOCK',
    polygon: [
      [8.545, 39.264],
      [8.546, 39.269],
      [8.541, 39.269],
      [8.54, 39.264],
      [8.545, 39.264],
    ],
    farmId: 'farm-1',
    alertOnEnter: false,
    alertOnExit: true,
    active: true,
  },
  {
    id: 'geo-fence-3',
    name: 'Quarantine Exclusion Zone',
    type: 'QUARANTINE',
    polygon: [
      [8.537, 39.264],
      [8.539, 39.267],
      [8.536, 39.267],
      [8.535, 39.264],
      [8.537, 39.264],
    ],
    farmId: 'farm-1',
    alertOnEnter: true,
    alertOnExit: true,
    active: true,
  },
];

export const initialGeofenceEvents: GeofenceEventRecord[] = [
  {
    id: 'g-evt-1',
    geofenceId: 'geo-fence-2',
    geofenceName: 'North Breeding Paddock Restricted Enclosure',
    animalId: 'ba-001',
    animalName: 'GOLDEN STAR 1248',
    eventType: 'EXITED',
    occurredAt: '2026-09-08T14:18:22Z',
    severity: 'WARNING',
    description: 'Breeding sire exited assigned breeding paddock through South Gate sensor',
  },
  {
    id: 'g-evt-2',
    geofenceId: 'geo-fence-2',
    geofenceName: 'North Breeding Paddock Restricted Enclosure',
    animalId: 'ba-001',
    animalName: 'GOLDEN STAR 1248',
    eventType: 'ENTERED',
    occurredAt: '2026-09-08T14:35:10Z',
    severity: 'INFO',
    description: 'Animal returned to North Breeding Paddock verified by technician barcode tag scan',
  },
];

/**
 * 8. Preset Saved Map Views
 */
export const initialSavedViews: SavedMapView[] = [
  {
    id: 'view-breeding-stock',
    name: 'National Elite Breeding Stock',
    description: 'Nucleus breeding stock, genetic merit scores, and AI sire locations',
    center: [8.6, 39.0],
    zoom: 9,
    baseMap: 'standard',
    overlay: 'BREEDING_STOCK',
    layers: {
      farmBoundaries: true,
      breedingStock: true,
      bulls: true,
      cows: true,
      geneticMerit: true,
    },
    filters: {
      breedingRole: 'ALL',
      farmType: 'ALL',
    },
    isSystemPreset: true,
  },
  {
    id: 'view-health-watch',
    name: 'Biosecurity & Disease Surveillance',
    description: 'Active disease outbreaks, quarantine perimeters, and 5/10/25km buffer rings',
    center: [10.2, 38.0],
    zoom: 7,
    baseMap: 'satellite',
    overlay: 'HEALTH_STATUS',
    layers: {
      diseaseEvents: true,
      quarantineZones: true,
      surveillanceBuffers: true,
      farmBoundaries: true,
      movements: true,
    },
    filters: {
      healthStatus: 'QUARANTINE',
    },
    isSystemPreset: true,
  },
  {
    id: 'view-vaccination-coverage',
    name: 'Government Vaccination Coverage',
    description: 'Regional choropleth showing immunization rates and reporting compliance',
    center: [8.5, 38.5],
    zoom: 7,
    baseMap: 'light',
    overlay: 'VACCINATION',
    layers: {
      regions: true,
      districts: true,
      vaccinationChoropleth: true,
      complianceOverlay: true,
    },
    filters: {},
    isSystemPreset: true,
  },
  {
    id: 'view-movement-flows',
    name: 'Inter-Facility Movement Corridor',
    description: 'Active cattle transfers, carrier vehicles, and origin-destination lines',
    center: [8.65, 39.1],
    zoom: 8,
    baseMap: 'standard',
    overlay: 'POPULATION',
    layers: {
      movements: true,
      farmBoundaries: true,
      animalLocations: true,
    },
    filters: {},
    isSystemPreset: true,
  },
  {
    id: 'view-marketplace-trade',
    name: 'Marketplace Inventory & Semen Hubs',
    description: 'Live cattle for sale, cryogenic semen centers, and approximate radius filters',
    center: [8.2, 38.8],
    zoom: 8,
    baseMap: 'standard',
    overlay: 'POPULATION',
    layers: {
      marketplaceListings: true,
      farmBoundaries: true,
    },
    filters: {},
    isSystemPreset: true,
  },
];
