import {
  MarketplaceListing,
  MarketplaceOffer,
  MarketplaceInquiry,
  MarketplaceReservation,
  MarketplaceOrder,
  MarketplaceInspection,
  SavedSearch,
} from './bovine-marketplace-types';

export const initialMarketplaceListings: MarketplaceListing[] = [
  {
    id: 'list-101',
    assetType: 'LIVE_ANIMAL',
    animalId: 'anim-1', // Apex Foundation Sire 01
    sellerId: 'user-apex-lead',
    sellerName: 'Dr. Evelyn Sterling',
    sellerOrgId: 'org-apex',
    sellerOrgName: 'Apex Bovine Genetics Consortium',
    sellerVerified: true,
    sellerRating: 4.9,
    farmId: 'farm-1',
    farmName: 'Meadowlands Dairy & Genetics Hub',
    region: 'Midwest Genomic Corridor, WI',
    listingType: 'NEGOTIABLE',
    status: 'ACTIVE',
    currency: 'USD',
    askingPrice: 18500,
    minimumPrice: 16000,
    priceNegotiable: true,
    priceHistory: [
      { price: 19500, date: '2026-08-01', reason: 'Initial catalog launch' },
      { price: 18500, date: '2026-08-20', reason: 'Summer bull sale promotion' },
    ],
    availableFrom: '2026-08-01',
    title: 'Apex Foundation Sire 01 — Proven Angus Nucleus Bull',
    description:
      'Elite proven herd sire ranking in the top 2% of the breed for Terminal Index ($B +178.4). Verified parentage through 100K GGP chip, negative for all lethal recessives (AMF, NHF, CAF, DDF). Remarkable progeny growth with over 80 offspring evaluated.',
    highlights: [
      'Top 2% Breed Weaning & Yearling Growth EPDs',
      'Ultrasound Scanned: 88.4 cm² REA with 4.8% Intramuscular Fat (Marbling)',
      '100% Calving Ease Direct (CED +12) on maiden heifers',
      'Complete veterinary breeding soundness exam (BSE) passed with 85% progressive motility',
    ],
    media: [
      {
        id: 'med-1',
        type: 'IMAGE',
        url: 'https://images.unsplash.com/photo-1546445317-29f4545e9d53?auto=format&fit=crop&q=80&w=800',
        title: 'Lateral Profile at 365 Days',
        isPrimary: true,
      },
      {
        id: 'med-2',
        type: 'IMAGE',
        url: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?auto=format&fit=crop&q=80&w=800',
        title: 'Rump Conformation and Rear Stance',
      },
    ],
    documents: [
      {
        id: 'doc-1',
        name: 'Official AAA Pedigree Certificate',
        type: 'PEDIGREE_CERT',
        url: '/docs/pedigree-anim-1.pdf',
        visibility: 'PUBLIC',
        issueDate: '2025-06-12',
        verified: true,
      },
      {
        id: 'doc-2',
        name: 'Neogen GGP HD 100K Genomic Evaluation',
        type: 'GENOMIC_REPORT',
        url: '/docs/genomics-anim-1.pdf',
        visibility: 'PUBLIC',
        issueDate: '2026-01-15',
        verified: true,
      },
      {
        id: 'doc-3',
        name: 'State Veterinary Health & TB/Brucellosis Clearance',
        type: 'VET_HEALTH_CERT',
        url: '/docs/health-anim-1.pdf',
        visibility: 'PUBLIC',
        issueDate: '2026-08-01',
        verified: true,
      },
    ],
    logistics: {
      pickupAvailable: true,
      transportArrangedBy: 'BOTH',
      deliveryRadiusKm: 800,
      estimatedDeliveryCost: 650,
      notes: 'Certified climate-controlled livestock carrier available. Quarantine facility ready for pre-movement hold.',
    },
    privacy: {
      showExactLocation: true,
      showContactPhone: true,
      showContactEmail: true,
    },
    trustBadges: {
      identityVerified: true,
      ownershipVerified: true,
      parentageDnaVerified: true,
      genotyped: true,
      carrierFreeStatus: true,
      healthClearanceCurrent: true,
      registryCertified: true,
    },
    viewCount: 428,
    saveCount: 39,
    inquiryCount: 7,
    offerCount: 3,
    createdAt: '2026-08-01T10:00:00Z',
    publishedAt: '2026-08-01T11:00:00Z',
    updatedAt: '2026-08-20T14:30:00Z',
  },
  {
    id: 'list-102',
    assetType: 'LIVE_ANIMAL',
    animalId: 'anim-2', // Bella 02
    sellerId: 'user-apex-lead',
    sellerName: 'Dr. Evelyn Sterling',
    sellerOrgId: 'org-apex',
    sellerOrgName: 'Apex Bovine Genetics Consortium',
    sellerVerified: true,
    sellerRating: 4.9,
    farmId: 'farm-1',
    farmName: 'Meadowlands Dairy & Genetics Hub',
    region: 'Midwest Genomic Corridor, WI',
    listingType: 'FIXED_PRICE',
    status: 'ACTIVE',
    currency: 'USD',
    askingPrice: 12500,
    priceNegotiable: false,
    availableFrom: '2026-08-10',
    title: 'Bella 02 — High-Index Donor Dam (A2/A2)',
    description:
      'Genomically elite Holstein female selected for superior cheese-yield protein variants (A2/A2 Beta-Casein & BB Kappa-Casein). Over 12 Grade 1 embryos flushed per donor cycle. Excellent functional udder attachments and deep maternal capacity.',
    highlights: [
      'Milk Fat +84 lbs • Protein +62 lbs GEBV',
      'Beta-Casein A2/A2 Verified',
      'Flushed 2x with 100% transferrable Grade 1 blastocysts',
      'Somatic Cell Score (SCS) 2.62 (Top 5% Mastitis Resistance)',
    ],
    media: [
      {
        id: 'med-3',
        type: 'IMAGE',
        url: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?auto=format&fit=crop&q=80&w=800',
        title: 'Donor Dam Profile',
        isPrimary: true,
      },
    ],
    documents: [
      {
        id: 'doc-4',
        name: 'Holstein Association Pedigree & Genetic Merit',
        type: 'PEDIGREE_CERT',
        url: '/docs/pedigree-anim-2.pdf',
        visibility: 'PUBLIC',
        issueDate: '2025-08-14',
        verified: true,
      },
    ],
    logistics: {
      pickupAvailable: true,
      transportArrangedBy: 'SELLER',
      deliveryRadiusKm: 500,
      estimatedDeliveryCost: 400,
      notes: 'Can coordinate direct transfer to approved regional ET clinic.',
    },
    privacy: {
      showExactLocation: true,
      showContactPhone: true,
      showContactEmail: true,
    },
    trustBadges: {
      identityVerified: true,
      ownershipVerified: true,
      parentageDnaVerified: true,
      genotyped: true,
      carrierFreeStatus: true,
      healthClearanceCurrent: true,
      registryCertified: true,
    },
    viewCount: 312,
    saveCount: 28,
    inquiryCount: 5,
    offerCount: 1,
    createdAt: '2026-08-10T09:00:00Z',
    publishedAt: '2026-08-10T09:30:00Z',
    updatedAt: '2026-08-10T09:30:00Z',
  },
  {
    id: 'list-103',
    assetType: 'SEMEN',
    sellerId: 'user-apex-lead',
    sellerName: 'Apex Genetics Cryo Center',
    sellerOrgId: 'org-apex',
    sellerOrgName: 'Apex Bovine Genetics Consortium',
    sellerVerified: true,
    sellerRating: 4.9,
    farmId: 'farm-1',
    farmName: 'Meadowlands Dairy & Genetics Hub',
    region: 'Madison Cryo Vault, WI',
    listingType: 'FIXED_PRICE',
    status: 'ACTIVE',
    currency: 'USD',
    askingPrice: 45, // Price per straw
    availableQuantity: 250,
    priceNegotiable: false,
    availableFrom: '2026-08-01',
    title: 'Apex Foundation Sire 01 — Conventional Semen Straws (0.5ml)',
    description:
      'Certified high-fertility semen straws harvested under CSS (Certified Semen Services) guidelines. High post-thaw progressive motility (>65%) with verified genomic reliability. Packaged in 0.5ml French straws, stored in liquid nitrogen vapor phase.',
    highlights: [
      'CSS Certified Health Tested Collection',
      'High Progressive Post-Thaw Motility: 68%',
      'Sperm Concentration: 32 million cells/dose',
      'Free shipping on orders of 25 straws or more with liquid N2 shipper tank return',
    ],
    semenDetails: {
      batchNumber: 'BATCH-2026-APEX-01',
      collectionDate: '2026-05-18',
      collectionCenter: 'Apex Advanced Cryobiology Lab #4',
      cryoMethod: 'Automated Computer-Controlled Rate Freezer (LN2)',
      qualityGrade: 'CSS Approved / Export Grade',
      motilityPercent: 68,
      concentrationMml: 32,
      availableDoses: 250,
      storageVault: 'Cryo Vault Tank 3B-Row4',
      sexedType: 'CONVENTIONAL',
    },
    media: [
      {
        id: 'med-5',
        type: 'IMAGE',
        url: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&q=80&w=800',
        title: 'Cryo Semen Tank and Straw Packaging',
        isPrimary: true,
      },
    ],
    documents: [
      {
        id: 'doc-5',
        name: 'Semen Analysis & Morphology Certificate',
        type: 'SEMEN_QUALITY_CERT',
        url: '/docs/semen-cert.pdf',
        visibility: 'PUBLIC',
        issueDate: '2026-05-20',
        verified: true,
      },
    ],
    logistics: {
      pickupAvailable: true,
      transportArrangedBy: 'SELLER',
      notes: 'Shipped in certified dry shipper charging dewar. Tank must be returned within 14 business days.',
    },
    privacy: {
      showExactLocation: true,
      showContactPhone: true,
      showContactEmail: true,
    },
    trustBadges: {
      identityVerified: true,
      ownershipVerified: true,
      parentageDnaVerified: true,
      genotyped: true,
      carrierFreeStatus: true,
      healthClearanceCurrent: true,
      registryCertified: true,
    },
    viewCount: 680,
    saveCount: 52,
    inquiryCount: 14,
    offerCount: 8,
    createdAt: '2026-08-01T08:00:00Z',
    publishedAt: '2026-08-01T08:30:00Z',
    updatedAt: '2026-08-25T11:00:00Z',
  },
  {
    id: 'list-104',
    assetType: 'EMBRYO',
    sellerId: 'user-apex-lead',
    sellerName: 'Apex Genetics Cryo Center',
    sellerOrgId: 'org-apex',
    sellerOrgName: 'Apex Bovine Genetics Consortium',
    sellerVerified: true,
    sellerRating: 4.9,
    farmId: 'farm-1',
    farmName: 'Meadowlands Dairy & Genetics Hub',
    region: 'Madison Cryo Vault, WI',
    listingType: 'FIXED_PRICE',
    status: 'ACTIVE',
    currency: 'USD',
    askingPrice: 750, // Price per embryo
    availableQuantity: 8,
    priceNegotiable: true,
    availableFrom: '2026-08-15',
    title: 'Grade 1 IVF Embryos: Bella 02 x Apex Foundation Sire 01',
    description:
      'Premier direct-transfer frozen embryos combining top maternal milk components with extreme muscularity and terminal index growth. Generated via IVF and vitrified at Stage 4/5 (Morula/Blastocyst).',
    highlights: [
      'IETS Certified Grade 1 Embryos',
      'Vitrified for Direct Straw Thaw and Transfer',
      'Expected Progeny Terminal Index: +164',
      'All parents tested negative for genetic defects',
    ],
    embryoDetails: {
      embryoCode: 'EMB-APEX-B02-01',
      donorCowAnimalId: 'anim-2',
      donorName: 'Bella 02',
      sireAnimalId: 'anim-1',
      sireName: 'Apex Foundation Sire 01',
      collectionDate: '2026-06-22',
      stage: 'Stage 4 (Compact Morula) / Stage 5 (Early Blastocyst)',
      grade: 'Grade 1 (Excellent / Uniform)',
      preservation: 'FROZEN',
      quantity: 8,
      storageCenter: 'Apex Advanced Cryobiology Lab',
      ivfOrInVivo: 'IVF',
    },
    media: [
      {
        id: 'med-6',
        type: 'IMAGE',
        url: 'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?auto=format&fit=crop&q=80&w=800',
        title: 'Stereomicroscope Inverted Embryo Imaging',
        isPrimary: true,
      },
    ],
    documents: [
      {
        id: 'doc-6',
        name: 'Official IETS Certificate of Embryo Recovery & Freezing',
        type: 'EMBRYO_STAGE_CERT',
        url: '/docs/embryo-cert.pdf',
        visibility: 'PUBLIC',
        issueDate: '2026-06-23',
        verified: true,
      },
    ],
    logistics: {
      pickupAvailable: true,
      transportArrangedBy: 'SELLER',
      notes: 'Shipped in certified dry shipper charging dewar.',
    },
    privacy: {
      showExactLocation: true,
      showContactPhone: true,
      showContactEmail: true,
    },
    trustBadges: {
      identityVerified: true,
      ownershipVerified: true,
      parentageDnaVerified: true,
      genotyped: true,
      carrierFreeStatus: true,
      healthClearanceCurrent: true,
      registryCertified: true,
    },
    viewCount: 540,
    saveCount: 44,
    inquiryCount: 9,
    offerCount: 4,
    createdAt: '2026-08-15T09:00:00Z',
    publishedAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-08-15T10:00:00Z',
  },
];

export const initialMarketplaceOffers: MarketplaceOffer[] = [
  {
    id: 'off-1',
    listingId: 'list-101',
    listingTitle: 'Apex Foundation Sire 01 — Proven Angus Nucleus Bull',
    assetType: 'LIVE_ANIMAL',
    buyerId: 'user-ranch-buyer',
    buyerName: 'Col. Thomas Vance',
    buyerOrgName: 'Highland Cattle & Genetics Co.',
    sellerId: 'user-apex-lead',
    sellerName: 'Dr. Evelyn Sterling',
    amount: 17000,
    currency: 'USD',
    status: 'COUNTERED',
    message: 'We are very interested in introducing this sire into our commercial crossbreeding program. Offering $17,000 pending veterinary inspection.',
    counterAmount: 17800,
    counterMessage: 'Thank you for the serious offer. We can agree to $17,800 which includes the pre-movement TB testing and health certificate.',
    counterDate: '2026-08-28',
    expiresAt: '2026-09-10T23:59:59Z',
    createdAt: '2026-08-26T14:20:00Z',
    respondedAt: '2026-08-28T10:15:00Z',
  },
  {
    id: 'off-2',
    listingId: 'list-104',
    listingTitle: 'Grade 1 IVF Embryos: Bella 02 x Apex Foundation Sire 01',
    assetType: 'EMBRYO',
    buyerId: 'user-dairy-lead',
    buyerName: 'Sarah Jenkins',
    buyerOrgName: 'Valley Creek Dairy Genetics',
    sellerId: 'user-apex-lead',
    sellerName: 'Apex Genetics Cryo Center',
    amount: 5600, // 8 embryos @ $700 each
    currency: 'USD',
    status: 'ACCEPTED',
    message: 'Offering $700/embryo for all 8 doses. We have synchronized recipients ready for transfer next week.',
    expiresAt: '2026-09-08T23:59:59Z',
    createdAt: '2026-08-29T16:00:00Z',
    respondedAt: '2026-08-30T09:00:00Z',
  },
];

export const initialMarketplaceInquiries: MarketplaceInquiry[] = [
  {
    id: 'inq-1',
    listingId: 'list-101',
    listingTitle: 'Apex Foundation Sire 01 — Proven Angus Nucleus Bull',
    buyerId: 'user-ranch-buyer',
    buyerName: 'Col. Thomas Vance',
    buyerOrgName: 'Highland Cattle & Genetics Co.',
    sellerId: 'user-apex-lead',
    sellerName: 'Dr. Evelyn Sterling',
    subject: 'Inquiry regarding foot structure and claw soundness score',
    message: 'Hello, could you provide the foot angle and claw set scores from the most recent AAA linear classification? Also, is an on-farm physical inspection possible this Friday?',
    inquiryType: 'INSPECTION_REQUEST',
    status: 'AWAITING_REPLY',
    replies: [
      {
        senderId: 'user-apex-lead',
        senderName: 'Dr. Evelyn Sterling',
        message: 'Foot angle was scored 5 (ideal 45-degree slope) and claw set scored 5 (symmetrical, non-curled). You are very welcome to inspect on Friday between 10am and 2pm.',
        timestamp: '2026-08-25 15:40',
      },
    ],
    createdAt: '2026-08-25T11:20:00Z',
  },
  {
    id: 'inq-2',
    listingId: 'list-103',
    listingTitle: 'Apex Foundation Sire 01 — Conventional Semen Straws (0.5ml)',
    buyerId: 'user-breeder-7',
    buyerName: 'Gabriel Santos',
    buyerOrgName: 'Santos Tropical Livestock',
    sellerId: 'user-apex-lead',
    sellerName: 'Apex Genetics Cryo Center',
    subject: 'International export certificates to Brazil / South America',
    message: 'Do you have approved export health protocols for USDA-APHIS / MAPA clearance to Brazil for this batch?',
    inquiryType: 'HEALTH_DOCUMENTS',
    status: 'OPEN',
    replies: [],
    createdAt: '2026-09-02T14:00:00Z',
  },
];

export const initialMarketplaceReservations: MarketplaceReservation[] = [
  {
    id: 'res-1',
    listingId: 'list-101',
    listingTitle: 'Apex Foundation Sire 01 — Proven Angus Nucleus Bull',
    buyerId: 'user-ranch-buyer',
    buyerName: 'Col. Thomas Vance',
    sellerId: 'user-apex-lead',
    sellerName: 'Dr. Evelyn Sterling',
    reservedAt: '2026-08-28T10:15:00Z',
    expiresAt: '2026-09-12T23:59:59Z',
    depositRequired: true,
    depositAmount: 1800,
    depositStatus: 'PAID',
    inspectionRequired: true,
    status: 'INSPECTION_PENDING',
    conditions: 'Subject to on-site veterinary ultrasound and BSE recertification.',
    notes: 'Holding period confirmed with 10% refundable deposit.',
  },
];

export const initialMarketplaceOrders: MarketplaceOrder[] = [
  {
    id: 'ord-881',
    listingId: 'list-104',
    listingTitle: 'Grade 1 IVF Embryos: Bella 02 x Apex Foundation Sire 01',
    assetType: 'EMBRYO',
    quantity: 8,
    buyerId: 'user-dairy-lead',
    buyerName: 'Sarah Jenkins',
    buyerOrgName: 'Valley Creek Dairy Genetics',
    buyerFarmId: 'farm-2',
    sellerId: 'user-apex-lead',
    sellerName: 'Dr. Evelyn Sterling',
    sellerOrgName: 'Apex Bovine Genetics Consortium',
    totalAmount: 5600,
    currency: 'USD',
    status: 'PAYMENT',
    currentStep: 5,
    offerId: 'off-2',
    inspectionStatus: 'WAIVED',
    paymentDetails: {
      paymentMethod: 'ESCROW',
      depositPaid: true,
      depositAmount: 1000,
      finalPaymentPaid: false,
    },
    ownershipTransferDetails: {
      priorOwnerOrgId: 'org-apex',
      newOwnerOrgId: 'org-valley-creek',
      transferAuthorized: true,
    },
    movementDetails: {
      originFarmName: 'Meadowlands Dairy & Genetics Hub',
      destinationFarmName: 'Valley Creek Facility Pen 4',
      transporterName: 'Express Nitrogen Cryo Logistics',
      receivingConfirmed: false,
    },
    timeline: [
      { step: 1, title: 'Offer Submitted & Accepted', status: 'COMPLETED', completedAt: '2026-08-30' },
      { step: 2, title: 'Asset Inventory Reserved', status: 'COMPLETED', completedAt: '2026-08-30' },
      { step: 3, title: 'Inspection / Certificate Verification', status: 'COMPLETED', completedAt: '2026-08-31' },
      { step: 4, title: 'Commercial Agreement Signed', status: 'COMPLETED', completedAt: '2026-09-01' },
      { step: 5, title: 'Escrow Payment Settlement', status: 'CURRENT', notes: 'Awaiting buyer final wire transfer.' },
      { step: 6, title: 'Embryo Ownership Transfer', status: 'UPCOMING' },
      { step: 7, title: 'Liquid Nitrogen Tank Dispatch', status: 'UPCOMING' },
      { step: 8, title: 'Receiving Confirmation & Order Close', status: 'UPCOMING' },
    ],
    createdAt: '2026-08-30T09:00:00Z',
  },
  {
    id: 'ord-880',
    listingId: 'list-101',
    listingTitle: 'Apex Foundation Sire 01 — Proven Angus Nucleus Bull',
    assetType: 'LIVE_ANIMAL',
    animalId: 'anim-1',
    quantity: 1,
    buyerId: 'user-ranch-buyer',
    buyerName: 'Col. Thomas Vance',
    buyerOrgName: 'Highland Cattle & Genetics Co.',
    buyerFarmId: 'farm-3',
    sellerId: 'user-apex-lead',
    sellerName: 'Dr. Evelyn Sterling',
    sellerOrgName: 'Apex Bovine Genetics Consortium',
    totalAmount: 17800,
    currency: 'USD',
    status: 'INSPECTION',
    currentStep: 3,
    offerId: 'off-1',
    reservationId: 'res-1',
    inspectionStatus: 'PENDING',
    paymentDetails: {
      paymentMethod: 'ESCROW',
      depositPaid: true,
      depositAmount: 1800,
      finalPaymentPaid: false,
    },
    timeline: [
      { step: 1, title: 'Counteroffer Accepted ($17,800)', status: 'COMPLETED', completedAt: '2026-08-28' },
      { step: 2, title: 'Asset Reserved with 10% Deposit', status: 'COMPLETED', completedAt: '2026-08-28' },
      { step: 3, title: 'Veterinary On-Site Inspection', status: 'CURRENT', notes: 'Scheduled for 2026-09-08.' },
      { step: 4, title: 'Sales Agreement & Health Permits', status: 'UPCOMING' },
      { step: 5, title: 'Balance Escrow Settlement', status: 'UPCOMING' },
      { step: 6, title: 'Official Studbook Ownership Transfer', status: 'UPCOMING' },
      { step: 7, title: 'Physical Movement & Quarantine', status: 'UPCOMING' },
      { step: 8, title: 'Receiving Confirmed', status: 'UPCOMING' },
    ],
    createdAt: '2026-08-28T10:15:00Z',
  },
];

export const initialMarketplaceInspections: MarketplaceInspection[] = [
  {
    id: 'insp-101',
    orderId: 'ord-880',
    listingId: 'list-101',
    type: 'VETERINARY_CLINICAL',
    requestedBy: 'Col. Thomas Vance',
    inspectorName: 'Dr. Marcus Vance (DVM)',
    scheduledDate: '2026-09-08',
    status: 'SCHEDULED',
    result: 'PENDING',
    findings: 'Pending on-farm examination: auscultation, hoof soundness, palpation, and BSE motility review.',
  },
];

export const initialSavedSearches: SavedSearch[] = [
  {
    id: 'search-1',
    name: 'Top 10% Weaning Weight Angus Bulls',
    query: 'Angus bull WW top 10%',
    assetType: 'LIVE_ANIMAL',
    breed: 'Angus',
    minSelectionIndex: 120,
    carrierFreeOnly: true,
    createdDate: '2026-08-15',
    emailAlerts: true,
  },
  {
    id: 'search-2',
    name: 'A2/A2 Certified Semen Straws',
    query: 'A2/A2 semen',
    assetType: 'SEMEN',
    minPrice: 20,
    maxPrice: 60,
    createdDate: '2026-08-20',
    emailAlerts: true,
  },
  {
    id: 'search-3',
    name: 'Nelore Elite Donor Embryos',
    query: 'Nelore Embryos',
    assetType: 'EMBRYO',
    breed: 'Nelore',
    createdDate: '2026-09-01',
    emailAlerts: false,
  },
];
