import { AnimalMedia, MediaAlbum } from './bovine-types';

export const initialMediaAssets: AnimalMedia[] = [
  // --- ANIMAL 1: Altair Supernova ET (anim-1) ---
  {
    id: 'med-anim1-profile',
    animalId: 'anim-1',
    title: 'Altair Supernova - Official 360 Standing Profile',
    caption: 'Right profile standing conformation showing udder suspension and dairy character.',
    description: 'Captured in direct morning light at the Ames Genomic Nucleus parlor. Clean stance, level rump, high tailhead placement.',
    mediaType: 'PHOTO',
    url: 'https://images.unsplash.com/photo-1546445317-29f4545e9d53?w=1200&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1546445317-29f4545e9d53?w=300&auto=format&fit=crop&q=80',
    takenAt: '2026-08-15T09:30:00Z',
    capturedAt: '2026-08-15T09:30:00Z',
    uploadedAt: '2026-08-15T11:00:00Z',
    capturedBy: 'Marcus Vance (Senior Appraiser)',
    uploadedBy: 'Elena Rostova',
    isIdentityPhoto: true,
    isProfile: true,
    category: 'PROFILE',
    visibility: 'MARKETPLACE_PUBLIC',
    verificationStatus: 'VERIFIED',
    verifiedBy: 'Dr. John Miller',
    verifiedAt: '2026-08-16T10:00:00Z',
    verificationNote: 'Meets official breed association standards for catalog presentation.',
    marketplaceStatus: 'APPROVED',
    marketplaceSelected: true,
    marketplaceOrder: 1,
    stage: 'MATURE',
    tags: ['profile', 'conformation', 'marketplace-primary', 'dairy-cow', 'mature'],
    links: [
      {
        id: 'link-1',
        mediaAssetId: 'med-anim1-profile',
        entityType: 'MARKETPLACE_LISTING',
        entityId: 'mkt-listing-1',
        relationType: 'PROFILE',
        label: 'Commercial Showcase Hero Image',
      },
    ],
    comments: [
      {
        id: 'comm-1',
        mediaId: 'med-anim1-profile',
        authorName: 'Dr. Evelyn Sterling',
        authorRole: 'Lead Geneticist',
        date: '2026-08-16 11:15',
        message: 'Excellent udder cleft definition. Approved for elite donor catalog.',
        isResolved: true,
      },
    ],
    auditHistory: [
      {
        id: 'aud-1',
        mediaId: 'med-anim1-profile',
        action: 'UPLOADED',
        actorName: 'Elena Rostova',
        timestamp: '2026-08-15 11:00',
        details: 'Uploaded via Field Cam app in High-Res mode.',
      },
      {
        id: 'aud-2',
        mediaId: 'med-anim1-profile',
        action: 'VERIFIED',
        actorName: 'Dr. John Miller',
        timestamp: '2026-08-16 10:00',
        details: 'Biometric conformation stamped by Herd Registrar.',
      },
      {
        id: 'aud-3',
        mediaId: 'med-anim1-profile',
        action: 'MARKETPLACE_APPROVED',
        actorName: 'Commercial Desk',
        timestamp: '2026-08-18 14:00',
        details: 'Curated as Primary Slot #1 on Global Marketplace.',
      },
    ],
    fileSize: '3.8 MB',
    checksum: 'sha256-78ab31df982a',
    mimeType: 'image/jpeg',
    width: 2400,
    height: 1800,
  },
  {
    id: 'med-anim1-id-tag',
    animalId: 'anim-1',
    title: 'Primary RFID Ear Tag Close-Up Verification',
    caption: 'Official USDA 840 RFID visual & button tag inspection.',
    description: 'Crisp macro capture showing tamper-evident tag seal #840003129941203 without ear tissue necrosis.',
    mediaType: 'PHOTO',
    url: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=1200&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=300&auto=format&fit=crop&q=80',
    takenAt: '2026-08-15T09:35:00Z',
    capturedAt: '2026-08-15T09:35:00Z',
    uploadedAt: '2026-08-15T11:05:00Z',
    capturedBy: 'Marcus Vance',
    uploadedBy: 'Elena Rostova',
    isIdentityPhoto: false,
    category: 'IDENTIFICATION',
    visibility: 'ORGANIZATION',
    verificationStatus: 'VERIFIED',
    verifiedBy: 'State Livestock Inspector 04',
    verifiedAt: '2026-08-19T08:30:00Z',
    verificationNote: 'Tag serial number cross-referenced with national database.',
    stage: 'MATURE',
    tags: ['identity', 'ear-tag', 'rfid', 'official-audit'],
    links: [],
    fileSize: '2.1 MB',
    checksum: 'sha256-bc9821ef3301',
    mimeType: 'image/jpeg',
    width: 2000,
    height: 1500,
  },
  {
    id: 'med-anim1-walking-video',
    animalId: 'anim-1',
    title: 'Gait & Locomotion Evaluation (4-Pass)',
    caption: 'Biomechanical locomotion recording on concrete run.',
    description: 'Video recording capturing: 1) Walk toward camera, 2) Walk away, 3) Left-side pass, 4) Right-side pass. Locomotion score 1 (Flawless stride).',
    mediaType: 'VIDEO',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1527153857715-3908f2ae5e81?w=300&auto=format&fit=crop&q=80',
    takenAt: '2026-08-15T10:15:00Z',
    capturedAt: '2026-08-15T10:15:00Z',
    uploadedAt: '2026-08-15T11:30:00Z',
    capturedBy: 'Dr. Evelyn Sterling',
    uploadedBy: 'Dr. Evelyn Sterling',
    isIdentityPhoto: false,
    category: 'CONFORMATION',
    visibility: 'MARKETPLACE_PUBLIC',
    verificationStatus: 'VERIFIED',
    verifiedBy: 'Dr. John Miller',
    verifiedAt: '2026-08-16T14:20:00Z',
    marketplaceStatus: 'APPROVED',
    marketplaceSelected: true,
    marketplaceOrder: 5,
    stage: 'MATURE',
    tags: ['gait', 'walking-video', 'locomotion', 'conformation', 'marketplace-video'],
    durationSeconds: 45,
    videoChapters: [
      { timestamp: '00:05', label: 'Walk towards camera (Front limb alignment)' },
      { timestamp: '00:16', label: 'Walk away (Hock straightness & track)' },
      { timestamp: '00:28', label: 'Left profile tracking pass' },
      { timestamp: '00:38', label: 'Rear claw balance review' },
    ],
    links: [
      {
        id: 'link-walk-1',
        mediaAssetId: 'med-anim1-walking-video',
        entityType: 'PERFORMANCE_TEST',
        entityId: 'pt-annual-2026',
        relationType: 'EVIDENCE',
        label: 'Locomotion Benchmark Exam',
      },
    ],
    fileSize: '24.5 MB',
    checksum: 'sha256-video-alt-001',
    mimeType: 'video/mp4',
    width: 1920,
    height: 1080,
  },
  {
    id: 'med-anim1-ultrasound',
    animalId: 'anim-1',
    title: 'Reproductive Ultrasound - Day 42 Viable Embryo',
    caption: 'B-mode reproductive ultrasound cross-section of right uterine horn.',
    description: 'Probe frequency 7.5 MHz linear transrectal. Clear amniotic sac, positive embryonic heartbeat detected, corpus luteum diameter 24mm.',
    mediaType: 'PHOTO',
    url: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=1200&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=300&auto=format&fit=crop&q=80',
    takenAt: '2026-07-20T08:00:00Z',
    capturedAt: '2026-07-20T08:00:00Z',
    uploadedAt: '2026-07-20T09:15:00Z',
    capturedBy: 'Dr. Sarah Jenkins (Veterinarian)',
    uploadedBy: 'Dr. Sarah Jenkins',
    isIdentityPhoto: false,
    category: 'ULTRASOUND',
    visibility: 'FARM_TEAM',
    verificationStatus: 'VERIFIED',
    verifiedBy: 'Dr. Sarah Jenkins',
    verifiedAt: '2026-07-20T09:20:00Z',
    stage: 'MATURE',
    tags: ['ultrasound', 'pregnancy', 'embryo-transfer', 'clinical-record'],
    links: [
      {
        id: 'link-ultrasound-1',
        mediaAssetId: 'med-anim1-ultrasound',
        entityType: 'PREGNANCY_CHECK',
        entityId: 'preg-chk-anim1-jul26',
        relationType: 'ULTRASOUND',
        label: 'Day 42 Gestation Confirmation',
      },
    ],
    comments: [
      {
        id: 'comm-2',
        mediaId: 'med-anim1-ultrasound',
        authorName: 'Dr. Sarah Jenkins',
        date: '2026-07-20 09:30',
        message: 'No uterine fluid or signs of early resorption. Recipient cow doing well.',
        isResolved: true,
      },
    ],
    fileSize: '1.4 MB',
    checksum: 'sha256-echo-88910',
    mimeType: 'image/jpeg',
    width: 1280,
    height: 960,
  },
  {
    id: 'med-anim1-treatment-progress',
    animalId: 'anim-1',
    title: 'Mastitis Therapy Response - Day 5 Post-Infusion',
    caption: 'Quarter milk visual assessment and teat condition photograph.',
    description: 'Right-rear quarter inflammation completely subsided. Milk return clear, no clots or discoloration. Somatic count normalizing.',
    mediaType: 'PHOTO',
    url: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=1200&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=300&auto=format&fit=crop&q=80',
    takenAt: '2026-09-02T16:00:00Z',
    capturedAt: '2026-09-02T16:00:00Z',
    uploadedAt: '2026-09-02T16:45:00Z',
    capturedBy: 'Alex Ramos (Parlor Tech)',
    uploadedBy: 'Alex Ramos',
    isIdentityPhoto: false,
    category: 'TREATMENT',
    visibility: 'FARM_TEAM',
    verificationStatus: 'VERIFIED',
    verifiedBy: 'Dr. Sarah Jenkins',
    verifiedAt: '2026-09-03T08:00:00Z',
    stage: 'MATURE',
    tags: ['treatment', 'health', 'mastitis', 'clinical-follow-up', 'after-treatment'],
    links: [
      {
        id: 'link-treat-1',
        mediaAssetId: 'med-anim1-treatment-progress',
        entityType: 'TREATMENT',
        entityId: 'treat-1',
        relationType: 'AFTER',
        label: 'Spectramast LC Recovery Verification',
      },
      {
        id: 'link-treat-2',
        mediaAssetId: 'med-anim1-treatment-progress',
        entityType: 'HEALTH_EVENT',
        entityId: 'health-case-1',
        relationType: 'EVIDENCE',
        label: 'Clinical Mastitis Flare #2026-H10',
      },
    ],
    fileSize: '2.6 MB',
    checksum: 'sha256-treat-99120',
    mimeType: 'image/jpeg',
    width: 1920,
    height: 1440,
  },
  {
    id: 'med-anim1-yearling-phase',
    animalId: 'anim-1',
    title: 'Yearling Growth Milestone (14 Months)',
    caption: 'Phenotype development and rib depth at 390 kg live weight.',
    description: 'Official Phase III Yearling milestone inspection photo taken on pasture. Scrotal and pelvic measurements recorded concurrently.',
    mediaType: 'PHOTO',
    url: 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=1200&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=300&auto=format&fit=crop&q=80',
    takenAt: '2024-12-10T14:00:00Z',
    capturedAt: '2024-12-10T14:00:00Z',
    uploadedAt: '2024-12-11T09:00:00Z',
    capturedBy: 'Mark Henderson (Herd Manager)',
    uploadedBy: 'Mark Henderson',
    isIdentityPhoto: false,
    category: 'YEARLING_PHASE',
    visibility: 'ORGANIZATION',
    verificationStatus: 'VERIFIED',
    verifiedBy: 'Dr. John Miller',
    verifiedAt: '2024-12-12T10:00:00Z',
    stage: 'YEARLING',
    tags: ['yearling', 'growth', 'phase-3', 'pasture', 'weight-milestone'],
    links: [
      {
        id: 'link-yearling-1',
        mediaAssetId: 'med-anim1-yearling-phase',
        entityType: 'PHENOTYPE_OBSERVATION',
        entityId: 'phen-rec-yr-01',
        relationType: 'EVIDENCE',
        label: 'Yearling Conformation Scorecard',
      },
    ],
    fileSize: '3.1 MB',
    checksum: 'sha256-yr-77881',
    mimeType: 'image/jpeg',
    width: 2400,
    height: 1600,
  },
  {
    id: 'med-anim1-weaning-phase',
    animalId: 'anim-1',
    title: 'Weaning Milestone (205-Day Standard Weight)',
    caption: 'Weaning weight checkpoint at 245 kg.',
    description: 'Clean calf coat, robust muscling, adjusted 205-day weaning weight index 112.',
    mediaType: 'PHOTO',
    url: 'https://images.unsplash.com/photo-1560493676-04071c5f467b?w=1200&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1560493676-04071c5f467b?w=300&auto=format&fit=crop&q=80',
    takenAt: '2024-05-18T10:00:00Z',
    capturedAt: '2024-05-18T10:00:00Z',
    uploadedAt: '2024-05-18T15:00:00Z',
    capturedBy: 'Mark Henderson',
    uploadedBy: 'Mark Henderson',
    isIdentityPhoto: false,
    category: 'WEANING_PHASE',
    visibility: 'ORGANIZATION',
    verificationStatus: 'VERIFIED',
    stage: 'WEANING',
    tags: ['weaning', 'growth', 'phase-2', '205-day-weight'],
    fileSize: '2.5 MB',
    checksum: 'sha256-wn-55210',
    mimeType: 'image/jpeg',
    width: 2000,
    height: 1500,
  },
  {
    id: 'med-anim1-birth-newborn',
    animalId: 'anim-1',
    title: 'Neonatal Calf Vigor & Registration Proof',
    caption: '2 Hours post-birth. Dam suckling observed, navel dipped in 7% iodine.',
    description: 'Birth weight 42.5 kg, single female birth, colostrum 4L received within 2 hours. Ear tag affixed.',
    mediaType: 'PHOTO',
    url: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=1200&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=300&auto=format&fit=crop&q=80',
    takenAt: '2023-10-25T07:15:00Z',
    capturedAt: '2023-10-25T07:15:00Z',
    uploadedAt: '2023-10-25T11:00:00Z',
    capturedBy: 'Night Calving Shift',
    uploadedBy: 'Night Calving Shift',
    isIdentityPhoto: false,
    category: 'NEWBORN',
    visibility: 'ORGANIZATION',
    verificationStatus: 'VERIFIED',
    stage: 'BIRTH',
    tags: ['birth', 'newborn', 'neonatal', 'calving-proof'],
    links: [
      {
        id: 'link-calv-1',
        mediaAssetId: 'med-anim1-birth-newborn',
        entityType: 'CALVING_EVENT',
        entityId: 'calv-supernova-birth',
        relationType: 'EVIDENCE',
        label: 'Calving Registration Dossier',
      },
    ],
    fileSize: '1.9 MB',
    checksum: 'sha256-nb-11200',
    mimeType: 'image/jpeg',
    width: 1800,
    height: 1350,
  },

  // --- ANIMAL 2: Ironwood Titan Red (anim-2) ---
  {
    id: 'med-anim2-profile',
    animalId: 'anim-2',
    title: 'Ironwood Titan Red - Primary Herd Sire Stand',
    caption: 'Official 3-year mature standing conformation of elite AI sire.',
    description: 'Stellar scrotal circumference (43 cm), strong top-line, muscular crest, clean underline. High semen fertility index.',
    mediaType: 'PHOTO',
    url: 'https://images.unsplash.com/photo-1596733430284-f7437764b1a9?w=1200&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1596733430284-f7437764b1a9?w=300&auto=format&fit=crop&q=80',
    takenAt: '2026-08-10T11:00:00Z',
    capturedAt: '2026-08-10T11:00:00Z',
    uploadedAt: '2026-08-10T13:30:00Z',
    capturedBy: 'Tim O’Connor (Stud Master)',
    uploadedBy: 'Tim O’Connor',
    isIdentityPhoto: true,
    isProfile: true,
    category: 'PROFILE',
    visibility: 'MARKETPLACE_PUBLIC',
    verificationStatus: 'VERIFIED',
    verifiedBy: 'Dr. John Miller',
    verifiedAt: '2026-08-11T09:00:00Z',
    marketplaceStatus: 'APPROVED',
    marketplaceSelected: true,
    marketplaceOrder: 1,
    stage: 'MATURE',
    tags: ['sire', 'bull', 'profile', 'marketplace', 'mature', 'ai-stud'],
    links: [
      {
        id: 'link-anim2-sire',
        mediaAssetId: 'med-anim2-profile',
        entityType: 'MARKETPLACE_LISTING',
        entityId: 'mkt-listing-2',
        relationType: 'PROFILE',
        label: 'Official Stud Catalog Feature',
      },
    ],
    fileSize: '4.2 MB',
    checksum: 'sha256-titan-prof-01',
    mimeType: 'image/jpeg',
    width: 2600,
    height: 1950,
  },
  {
    id: 'med-anim2-walkaround-video',
    animalId: 'anim-2',
    title: 'Bull Walkaround & Ring Video (360° View)',
    caption: '360-degree walking video in outdoor soft ring.',
    description: 'Demonstrating docility, stride length, rear leg tracking, testicular tone, and structural balance.',
    mediaType: 'VIDEO',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1596733430284-f7437764b1a9?w=300&auto=format&fit=crop&q=80',
    takenAt: '2026-08-10T11:30:00Z',
    capturedAt: '2026-08-10T11:30:00Z',
    uploadedAt: '2026-08-10T14:00:00Z',
    capturedBy: 'Tim O’Connor',
    uploadedBy: 'Tim O’Connor',
    isIdentityPhoto: false,
    category: 'CONFORMATION',
    visibility: 'MARKETPLACE_PUBLIC',
    verificationStatus: 'VERIFIED',
    verifiedBy: 'Dr. John Miller',
    verifiedAt: '2026-08-11T09:15:00Z',
    marketplaceStatus: 'APPROVED',
    marketplaceSelected: true,
    marketplaceOrder: 2,
    stage: 'MATURE',
    tags: ['walkaround', 'video', 'bull', 'marketplace', 'ring-evaluation'],
    durationSeconds: 60,
    videoChapters: [
      { timestamp: '00:00', label: 'Front head & muzzle inspection' },
      { timestamp: '00:15', label: 'Left rib spring & flank' },
      { timestamp: '00:32', label: 'Rear muscling & scrotal stance' },
      { timestamp: '00:48', label: 'Ring walking turn' },
    ],
    fileSize: '32.1 MB',
    checksum: 'sha256-video-titan-ring',
    mimeType: 'video/mp4',
    width: 1920,
    height: 1080,
  },
  {
    id: 'med-anim2-semen-microscope',
    animalId: 'anim-2',
    title: 'Semen Cryopreservation Lab Analysis (CASA)',
    caption: 'Computer-assisted sperm analysis (CASA) motility field recording.',
    description: 'Post-thaw progressive motility: 78.4%, concentration: 42 x 10⁶ / straw. Normal morphology 92%. Clean test for infectious bovine rhinotracheitis.',
    mediaType: 'PHOTO',
    url: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=1200&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=300&auto=format&fit=crop&q=80',
    takenAt: '2026-08-05T08:30:00Z',
    capturedAt: '2026-08-05T08:30:00Z',
    uploadedAt: '2026-08-05T10:00:00Z',
    capturedBy: 'Genetics Center Technologist',
    uploadedBy: 'Tim O’Connor',
    isIdentityPhoto: false,
    category: 'SEMEN',
    visibility: 'MARKETPLACE_PUBLIC',
    verificationStatus: 'VERIFIED',
    verifiedBy: 'State Veterinary Certifier',
    verifiedAt: '2026-08-06T11:00:00Z',
    marketplaceStatus: 'APPROVED',
    marketplaceSelected: true,
    marketplaceOrder: 3,
    stage: 'MATURE',
    tags: ['semen', 'lab-result', 'casa', 'cryopreservation', 'sire-quality'],
    links: [
      {
        id: 'link-semen-batch-1',
        mediaAssetId: 'med-anim2-semen-microscope',
        entityType: 'SEMEN_COLLECTION',
        entityId: 'sem-col-01',
        relationType: 'EVIDENCE',
        label: 'Cryo Straw Batch #2026-C88 Certificate',
      },
    ],
    fileSize: '1.8 MB',
    checksum: 'sha256-semen-lab-88',
    mimeType: 'image/jpeg',
    width: 1600,
    height: 1200,
  },

  // --- ANIMAL 4: Cloverdale Bella 14 (anim-4) - Health & Wound Recovery ---
  {
    id: 'med-anim4-wound-before',
    animalId: 'anim-4',
    title: 'Hoof Sole Ulcer - Day 0 Initial Presentation',
    caption: 'Right hind medial claw zone 4 sole ulcer before debridement.',
    description: 'Cow presented with grade 3 lameness on September 1. Severe focal hemorrhaging with necrotic sole corium exposed.',
    mediaType: 'PHOTO',
    url: 'https://images.unsplash.com/photo-1527153857715-3908f2ae5e81?w=1200&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1527153857715-3908f2ae5e81?w=300&auto=format&fit=crop&q=80',
    takenAt: '2026-09-01T08:30:00Z',
    capturedAt: '2026-09-01T08:30:00Z',
    uploadedAt: '2026-09-01T09:00:00Z',
    capturedBy: 'Elena Rostova (Technician)',
    uploadedBy: 'Elena Rostova',
    isIdentityPhoto: false,
    category: 'WOUND',
    visibility: 'FARM_TEAM',
    verificationStatus: 'VERIFIED',
    verifiedBy: 'Dr. Sarah Jenkins',
    verifiedAt: '2026-09-01T09:30:00Z',
    stage: 'MATURE',
    tags: ['wound', 'hoof', 'lameness', 'before-treatment', 'day-0', 'clinical-case'],
    links: [
      {
        id: 'link-wound-case-1',
        mediaAssetId: 'med-anim4-wound-before',
        entityType: 'HEALTH_EVENT',
        entityId: 'health-case-4',
        relationType: 'BEFORE',
        label: 'Sole Ulcer Clinical Case #2026-SU04',
      },
    ],
    fileSize: '2.8 MB',
    checksum: 'sha256-wound-d0-anim4',
    mimeType: 'image/jpeg',
    width: 2000,
    height: 1500,
  },
  {
    id: 'med-anim4-wound-after',
    animalId: 'anim-4',
    title: 'Hoof Sole Ulcer - Day 5 Post-Block & Dressing',
    caption: 'Healthy granulation tissue formation with rubber block relief.',
    description: 'Clean cornification initiated. Pain score reduced from 3 to 1. Dressing removed, antiseptic oxytetracycline spray applied.',
    mediaType: 'PHOTO',
    url: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=1200&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=300&auto=format&fit=crop&q=80',
    takenAt: '2026-09-05T10:00:00Z',
    capturedAt: '2026-09-05T10:00:00Z',
    uploadedAt: '2026-09-05T10:30:00Z',
    capturedBy: 'Elena Rostova',
    uploadedBy: 'Elena Rostova',
    isIdentityPhoto: false,
    category: 'TREATMENT',
    visibility: 'FARM_TEAM',
    verificationStatus: 'VERIFIED',
    verifiedBy: 'Dr. Sarah Jenkins',
    verifiedAt: '2026-09-05T11:00:00Z',
    stage: 'MATURE',
    tags: ['treatment', 'hoof', 'recovery', 'after-treatment', 'day-5', 'healing'],
    links: [
      {
        id: 'link-wound-case-2',
        mediaAssetId: 'med-anim4-wound-after',
        entityType: 'HEALTH_EVENT',
        entityId: 'health-case-4',
        relationType: 'AFTER',
        label: 'Sole Ulcer Clinical Case #2026-SU04',
      },
    ],
    fileSize: '2.7 MB',
    checksum: 'sha256-wound-d5-anim4',
    mimeType: 'image/jpeg',
    width: 2000,
    height: 1500,
  },
  {
    id: 'med-anim4-lameness-video',
    animalId: 'anim-4',
    title: 'Post-Treatment Locomotion Check (Recovery)',
    caption: 'Gait recovery check following hoof trimming and block application.',
    description: 'Demonstrating weight-bearing on right hind leg. Animal tracking comfortably on pasture path.',
    mediaType: 'VIDEO',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1527153857715-3908f2ae5e81?w=300&auto=format&fit=crop&q=80',
    takenAt: '2026-09-05T10:15:00Z',
    capturedAt: '2026-09-05T10:15:00Z',
    uploadedAt: '2026-09-05T11:00:00Z',
    capturedBy: 'Elena Rostova',
    uploadedBy: 'Elena Rostova',
    isIdentityPhoto: false,
    category: 'LAMENESS',
    visibility: 'FARM_TEAM',
    verificationStatus: 'VERIFIED',
    stage: 'MATURE',
    tags: ['lameness', 'walking-video', 'hoof-recovery', 'clinical-evaluation'],
    durationSeconds: 30,
    videoChapters: [
      { timestamp: '00:02', label: 'Paddock walk-out' },
      { timestamp: '00:15', label: 'Right hind leg strike observation' },
    ],
    fileSize: '16.8 MB',
    checksum: 'sha256-vid-lame-anim4',
    mimeType: 'video/mp4',
    width: 1920,
    height: 1080,
  },
];

export const initialMediaAlbums: MediaAlbum[] = [
  // anim-1 Albums
  {
    id: 'alb-anim1-identity',
    animalId: 'anim-1',
    name: 'Official Identification Dossier',
    description: 'Certified biometric imagery, RFID scans, muzzle prints, and ear tag verification.',
    coverUrl: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=800&auto=format&fit=crop&q=80',
    isSystem: true,
    category: 'IDENTIFICATION',
    mediaIds: ['med-anim1-profile', 'med-anim1-id-tag'],
    createdAt: '2026-08-15T11:10:00Z',
  },
  {
    id: 'alb-anim1-marketplace',
    animalId: 'anim-1',
    name: 'Marketplace Showcase Selection',
    description: 'Curated high-resolution media approved for public breeding auction and commercial listings.',
    coverUrl: 'https://images.unsplash.com/photo-1546445317-29f4545e9d53?w=800&auto=format&fit=crop&q=80',
    isSystem: true,
    category: 'MARKETPLACE',
    mediaIds: ['med-anim1-profile', 'med-anim1-walking-video'],
    createdAt: '2026-08-18T14:10:00Z',
  },
  {
    id: 'alb-anim1-growth',
    animalId: 'anim-1',
    name: 'Lifecycle & Phase Development (Birth to Mature)',
    description: 'Visual tracking from neonatal calving, 205-day weaning weight, to 14-month yearling milestone.',
    coverUrl: 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=800&auto=format&fit=crop&q=80',
    isSystem: true,
    category: 'GROWTH',
    mediaIds: ['med-anim1-birth-newborn', 'med-anim1-weaning-phase', 'med-anim1-yearling-phase', 'med-anim1-profile'],
    createdAt: '2026-08-15T11:15:00Z',
  },
  {
    id: 'alb-anim1-clinical',
    animalId: 'anim-1',
    name: 'Reproductive & Veterinary Case Logs',
    description: 'Ultrasound scans, antibiotic quarter therapy follow-ups, and lactation health evidence.',
    coverUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&auto=format&fit=crop&q=80',
    isSystem: true,
    category: 'HEALTH',
    mediaIds: ['med-anim1-ultrasound', 'med-anim1-treatment-progress'],
    createdAt: '2026-09-02T16:50:00Z',
  },

  // anim-2 Albums
  {
    id: 'alb-anim2-sire',
    animalId: 'anim-2',
    name: 'Commercial Sire Presentation Suite',
    description: 'Comprehensive evaluation suite including 360 ring video and cryo semen CASA lab proof.',
    coverUrl: 'https://images.unsplash.com/photo-1596733430284-f7437764b1a9?w=800&auto=format&fit=crop&q=80',
    isSystem: true,
    category: 'MARKETPLACE',
    mediaIds: ['med-anim2-profile', 'med-anim2-walkaround-video', 'med-anim2-semen-microscope'],
    createdAt: '2026-08-10T14:15:00Z',
  },

  // anim-4 Albums
  {
    id: 'alb-anim4-recovery',
    animalId: 'anim-4',
    name: 'Sole Ulcer Clinical Healing Tracking',
    description: 'Chronological photo & gait monitoring tracking claw corium recovery from Day 0 through Day 5.',
    coverUrl: 'https://images.unsplash.com/photo-1527153857715-3908f2ae5e81?w=800&auto=format&fit=crop&q=80',
    isSystem: false,
    category: 'HEALTH',
    mediaIds: ['med-anim4-wound-before', 'med-anim4-wound-after', 'med-anim4-lameness-video'],
    createdAt: '2026-09-01T09:15:00Z',
  },
];
